// Generated by tools/generate_ibl_material_contracts.py.
// Do not edit this file by hand.
constexpr std::array<IblMaterialShaderDefinition, 41>
    kIblMaterialShaderDefinitions{ {
        {
            "DFComposite_00_05f5cabf",
            IDR_IBL_MATERIAL_00_PS,
            {
                11104,
                {
                    0x05u, 0xF5u, 0xCAu, 0xBFu,
                    0x7Eu, 0xDCu, 0xAAu, 0xF6u,
                    0x95u, 0x80u, 0x5Fu, 0xFBu,
                    0x32u, 0x8Au, 0xD3u, 0x6Du,
                },
            },
            {
                12592,
                {
                    0xB4u, 0xF5u, 0x9Au, 0xCDu,
                    0xCBu, 0x58u, 0xA9u, 0x7Du,
                    0x79u, 0x0Fu, 0x04u, 0xCAu,
                    0x5Au, 0xBDu, 0xB3u, 0xB8u,
                },
            },
        },
        {
            "DFComposite_01_05fa2982",
            IDR_IBL_MATERIAL_01_PS,
            {
                11208,
                {
                    0x05u, 0xFAu, 0x29u, 0x82u,
                    0x24u, 0xCDu, 0x5Bu, 0x2Eu,
                    0x25u, 0x0Bu, 0x7Au, 0x75u,
                    0x21u, 0x13u, 0x1Fu, 0xBAu,
                },
            },
            {
                12696,
                {
                    0x86u, 0x17u, 0x02u, 0x5Du,
                    0x47u, 0xBFu, 0x98u, 0x31u,
                    0x8Cu, 0x57u, 0x8Au, 0x31u,
                    0x75u, 0x9Fu, 0xF0u, 0x39u,
                },
            },
        },
        {
            "DFComposite_02_127c7bb7",
            IDR_IBL_MATERIAL_02_PS,
            {
                3424,
                {
                    0x12u, 0x7Cu, 0x7Bu, 0xB7u,
                    0xC3u, 0x93u, 0x63u, 0xBFu,
                    0xB6u, 0x7Eu, 0x02u, 0xCBu,
                    0xEBu, 0x31u, 0x08u, 0x18u,
                },
            },
            {
                4952,
                {
                    0x16u, 0x43u, 0x69u, 0xEEu,
                    0x29u, 0xEBu, 0x82u, 0xACu,
                    0x14u, 0x39u, 0xB3u, 0xC8u,
                    0x55u, 0xE0u, 0x22u, 0x70u,
                },
            },
        },
        {
            "DFComposite_03_12876af2",
            IDR_IBL_MATERIAL_03_PS,
            {
                5204,
                {
                    0x12u, 0x87u, 0x6Au, 0xF2u,
                    0xF3u, 0x85u, 0xB4u, 0x1Cu,
                    0x0Du, 0xDDu, 0x45u, 0x58u,
                    0xB8u, 0x59u, 0xF5u, 0xF7u,
                },
            },
            {
                6692,
                {
                    0x41u, 0xEBu, 0xA8u, 0x3Du,
                    0xF5u, 0xE8u, 0xB6u, 0x61u,
                    0xBBu, 0x36u, 0x53u, 0xF0u,
                    0xE4u, 0x6Fu, 0x5Eu, 0xDDu,
                },
            },
        },
        {
            "DFComposite_04_182696bc",
            IDR_IBL_MATERIAL_04_PS,
            {
                5096,
                {
                    0x18u, 0x26u, 0x96u, 0xBCu,
                    0x27u, 0xB5u, 0xEDu, 0x33u,
                    0x94u, 0xB9u, 0x50u, 0xDCu,
                    0xC1u, 0x52u, 0x66u, 0xAFu,
                },
            },
            {
                6584,
                {
                    0xD4u, 0x5Fu, 0xFEu, 0xABu,
                    0x69u, 0xF0u, 0x3Au, 0x7Du,
                    0x0Cu, 0xCBu, 0xD8u, 0xEBu,
                    0x80u, 0x15u, 0x95u, 0x79u,
                },
            },
        },
        {
            "DFComposite_05_237ceacb",
            IDR_IBL_MATERIAL_05_PS,
            {
                10888,
                {
                    0x23u, 0x7Cu, 0xEAu, 0xCBu,
                    0x01u, 0x20u, 0x71u, 0x1Au,
                    0x60u, 0x5Bu, 0x69u, 0xC1u,
                    0xBFu, 0x78u, 0x8Bu, 0x3Bu,
                },
            },
            {
                12376,
                {
                    0x69u, 0x91u, 0xD2u, 0xDBu,
                    0x60u, 0x45u, 0xAEu, 0xACu,
                    0x31u, 0xD6u, 0xBBu, 0x1Au,
                    0x9Fu, 0x52u, 0x8Fu, 0xC6u,
                },
            },
        },
        {
            "DFComposite_06_33ca4f05",
            IDR_IBL_MATERIAL_06_PS,
            {
                9252,
                {
                    0x33u, 0xCAu, 0x4Fu, 0x05u,
                    0xDCu, 0x8Bu, 0xBDu, 0x98u,
                    0xE9u, 0x68u, 0x59u, 0x11u,
                    0x3Bu, 0xEAu, 0x32u, 0xC9u,
                },
            },
            {
                10740,
                {
                    0xBAu, 0xD5u, 0xB8u, 0x38u,
                    0x65u, 0xEDu, 0xD9u, 0x9Eu,
                    0xA0u, 0x61u, 0xF2u, 0x64u,
                    0xFAu, 0xDFu, 0xB6u, 0xC7u,
                },
            },
        },
        {
            "DFComposite_07_3843512b",
            IDR_IBL_MATERIAL_07_PS,
            {
                5016,
                {
                    0x38u, 0x43u, 0x51u, 0x2Bu,
                    0x6Eu, 0xC9u, 0x93u, 0x87u,
                    0x45u, 0xDDu, 0xA5u, 0x8Bu,
                    0x4Cu, 0xB7u, 0xDEu, 0x15u,
                },
            },
            {
                6504,
                {
                    0x4Au, 0x5Bu, 0xBCu, 0x69u,
                    0xE7u, 0xBFu, 0xD0u, 0xE5u,
                    0xA7u, 0x47u, 0x44u, 0x04u,
                    0x8Fu, 0x51u, 0x98u, 0x9Cu,
                },
            },
        },
        {
            "DFComposite_08_3b4ace2c",
            IDR_IBL_MATERIAL_08_PS,
            {
                9464,
                {
                    0x3Bu, 0x4Au, 0xCEu, 0x2Cu,
                    0xE4u, 0xB1u, 0x3Au, 0x96u,
                    0x7Fu, 0xA3u, 0x8Du, 0xC8u,
                    0x58u, 0x0Eu, 0x99u, 0xA5u,
                },
            },
            {
                10952,
                {
                    0xD3u, 0xD8u, 0xCFu, 0x4Cu,
                    0xE2u, 0x1Eu, 0xFCu, 0x62u,
                    0x9Du, 0x86u, 0x41u, 0x63u,
                    0x92u, 0x3Eu, 0x0Fu, 0xA9u,
                },
            },
        },
        {
            "DFComposite_09_3c3cc20b",
            IDR_IBL_MATERIAL_09_PS,
            {
                3588,
                {
                    0x3Cu, 0x3Cu, 0xC2u, 0x0Bu,
                    0x57u, 0xA8u, 0x2Eu, 0x9Fu,
                    0x49u, 0x0Fu, 0xDFu, 0xFBu,
                    0xECu, 0x68u, 0xD2u, 0x73u,
                },
            },
            {
                5116,
                {
                    0x97u, 0x45u, 0x3Du, 0x02u,
                    0xE5u, 0x84u, 0xA3u, 0xEAu,
                    0x07u, 0xB3u, 0x01u, 0x72u,
                    0x50u, 0x96u, 0xA0u, 0xE8u,
                },
            },
        },
        {
            "DFComposite_10_3ec58c35",
            IDR_IBL_MATERIAL_10_PS,
            {
                5320,
                {
                    0x3Eu, 0xC5u, 0x8Cu, 0x35u,
                    0x94u, 0x9Bu, 0xF9u, 0x7Au,
                    0xE2u, 0x37u, 0x7Bu, 0x90u,
                    0x9Du, 0x61u, 0xE7u, 0xF7u,
                },
            },
            {
                6808,
                {
                    0xD2u, 0x11u, 0x63u, 0xF7u,
                    0x8Du, 0x4Du, 0x27u, 0x5Du,
                    0x27u, 0x58u, 0xA2u, 0x65u,
                    0x64u, 0x4Au, 0xF1u, 0x53u,
                },
            },
        },
        {
            "DFComposite_11_4c76cbf2",
            IDR_IBL_MATERIAL_11_PS,
            {
                5124,
                {
                    0x4Cu, 0x76u, 0xCBu, 0xF2u,
                    0x39u, 0x25u, 0xBAu, 0xC1u,
                    0xB6u, 0xBCu, 0xF4u, 0x75u,
                    0x08u, 0xF6u, 0x64u, 0x4Du,
                },
            },
            {
                6612,
                {
                    0x4Cu, 0x63u, 0x35u, 0x84u,
                    0xEBu, 0x9Cu, 0xE3u, 0xDCu,
                    0x8Du, 0x2Fu, 0x22u, 0x93u,
                    0x2Du, 0xF3u, 0x76u, 0x1Eu,
                },
            },
        },
        {
            "DFComposite_12_4d6870ba",
            IDR_IBL_MATERIAL_12_PS,
            {
                9564,
                {
                    0x4Du, 0x68u, 0x70u, 0xBAu,
                    0x7Du, 0x54u, 0x98u, 0xE7u,
                    0x29u, 0xB3u, 0x19u, 0x5Fu,
                    0x7Du, 0xCDu, 0xF9u, 0x78u,
                },
            },
            {
                11684,
                {
                    0x3Fu, 0xCDu, 0x53u, 0xB6u,
                    0xF7u, 0x0Au, 0xF4u, 0xD8u,
                    0x33u, 0x96u, 0x98u, 0xB0u,
                    0xE4u, 0x33u, 0xA1u, 0x0Bu,
                },
            },
        },
        {
            "DFComposite_13_4eff5e0d",
            IDR_IBL_MATERIAL_13_PS,
            {
                5312,
                {
                    0x4Eu, 0xFFu, 0x5Eu, 0x0Du,
                    0xF8u, 0x32u, 0x9Du, 0x29u,
                    0xE1u, 0x72u, 0x18u, 0x97u,
                    0xF4u, 0x28u, 0xD2u, 0x37u,
                },
            },
            {
                6800,
                {
                    0x96u, 0x19u, 0xBFu, 0xAFu,
                    0x14u, 0x59u, 0x65u, 0x7Cu,
                    0x0Fu, 0x11u, 0xD0u, 0xE5u,
                    0x6Cu, 0x83u, 0xEAu, 0x46u,
                },
            },
        },
        {
            "DFComposite_14_5a125823",
            IDR_IBL_MATERIAL_14_PS,
            {
                5408,
                {
                    0x5Au, 0x12u, 0x58u, 0x23u,
                    0x47u, 0x71u, 0x42u, 0xE0u,
                    0xFDu, 0xC1u, 0x67u, 0x14u,
                    0x24u, 0x73u, 0x67u, 0xDDu,
                },
            },
            {
                6896,
                {
                    0xFFu, 0xD3u, 0x6Cu, 0x8Du,
                    0x5Eu, 0x77u, 0xA8u, 0x1Eu,
                    0xBDu, 0x77u, 0x5Cu, 0xEDu,
                    0x56u, 0xCFu, 0xC9u, 0x18u,
                },
            },
        },
        {
            "DFComposite_15_618ab40a",
            IDR_IBL_MATERIAL_15_PS,
            {
                3272,
                {
                    0x61u, 0x8Au, 0xB4u, 0x0Au,
                    0xD8u, 0x39u, 0xB7u, 0x52u,
                    0xB5u, 0x46u, 0x78u, 0x58u,
                    0x6Du, 0x98u, 0x73u, 0x65u,
                },
            },
            {
                4800,
                {
                    0x62u, 0x62u, 0x70u, 0x48u,
                    0x38u, 0x4Fu, 0xC3u, 0x40u,
                    0xFFu, 0x57u, 0xB2u, 0x34u,
                    0xC7u, 0xA0u, 0xA1u, 0x00u,
                },
            },
        },
        {
            "DFComposite_16_67fc05f4",
            IDR_IBL_MATERIAL_16_PS,
            {
                3304,
                {
                    0x67u, 0xFCu, 0x05u, 0xF4u,
                    0xBEu, 0xBDu, 0x9Fu, 0xFFu,
                    0x8Au, 0x81u, 0xE6u, 0xF6u,
                    0x4Fu, 0xE0u, 0x8Bu, 0x29u,
                },
            },
            {
                4832,
                {
                    0xAEu, 0x06u, 0xDEu, 0xCBu,
                    0x0Au, 0x59u, 0x70u, 0x65u,
                    0x97u, 0x10u, 0xD8u, 0x9Eu,
                    0x0Bu, 0x20u, 0x66u, 0xA1u,
                },
            },
        },
        {
            "DFComposite_17_69644eba",
            IDR_IBL_MATERIAL_17_PS,
            {
                5160,
                {
                    0x69u, 0x64u, 0x4Eu, 0xBAu,
                    0x82u, 0x19u, 0x58u, 0x4Au,
                    0xDAu, 0xD6u, 0x05u, 0x48u,
                    0x86u, 0xDAu, 0x80u, 0xA0u,
                },
            },
            {
                6648,
                {
                    0x53u, 0x29u, 0xD1u, 0x02u,
                    0x3Fu, 0xA3u, 0x7Bu, 0x5Bu,
                    0x86u, 0x64u, 0x70u, 0x81u,
                    0x2Du, 0xB6u, 0xCFu, 0xA0u,
                },
            },
        },
        {
            "DFComposite_18_83191af2",
            IDR_IBL_MATERIAL_18_PS,
            {
                5192,
                {
                    0x83u, 0x19u, 0x1Au, 0xF2u,
                    0x68u, 0x5Bu, 0xCDu, 0x2Cu,
                    0x24u, 0xE3u, 0xA5u, 0x46u,
                    0xEBu, 0x62u, 0xA1u, 0x32u,
                },
            },
            {
                6680,
                {
                    0x0Bu, 0x7Cu, 0x2Cu, 0x5Eu,
                    0x3Eu, 0xC7u, 0x11u, 0x96u,
                    0xE6u, 0xC3u, 0x32u, 0x37u,
                    0x8Au, 0xF6u, 0xB3u, 0x33u,
                },
            },
        },
        {
            "DFComposite_19_93edc6af",
            IDR_IBL_MATERIAL_19_PS,
            {
                9348,
                {
                    0x93u, 0xEDu, 0xC6u, 0xAFu,
                    0x41u, 0xCBu, 0xB2u, 0xD2u,
                    0x90u, 0x96u, 0x2Eu, 0x99u,
                    0x5Au, 0x4Fu, 0xCEu, 0x25u,
                },
            },
            {
                11468,
                {
                    0x42u, 0x0Au, 0x9Cu, 0x20u,
                    0xF3u, 0x51u, 0x5Bu, 0x96u,
                    0x3Au, 0x39u, 0xA8u, 0x07u,
                    0x76u, 0x18u, 0xB2u, 0xE6u,
                },
            },
        },
        {
            "DFComposite_20_93f4d80a",
            IDR_IBL_MATERIAL_20_PS,
            {
                3372,
                {
                    0x93u, 0xF4u, 0xD8u, 0x0Au,
                    0x48u, 0x9Cu, 0x3Cu, 0x1Fu,
                    0x9Fu, 0xB8u, 0x45u, 0x7Bu,
                    0xBBu, 0xB6u, 0xDAu, 0x4Bu,
                },
            },
            {
                4900,
                {
                    0x8Fu, 0xF3u, 0x0Cu, 0x92u,
                    0x67u, 0x16u, 0x0Au, 0x9Bu,
                    0xCFu, 0xA9u, 0x0Eu, 0x84u,
                    0x69u, 0x5Du, 0x5Eu, 0xAAu,
                },
            },
        },
        {
            "DFComposite_21_a1c51753",
            IDR_IBL_MATERIAL_21_PS,
            {
                10992,
                {
                    0xA1u, 0xC5u, 0x17u, 0x53u,
                    0xF0u, 0xCCu, 0xD8u, 0x3Fu,
                    0x96u, 0x99u, 0x0Du, 0xCDu,
                    0x09u, 0x40u, 0xA5u, 0x36u,
                },
            },
            {
                12480,
                {
                    0x2Eu, 0x6Fu, 0x89u, 0x21u,
                    0xC0u, 0x5Au, 0xF1u, 0x85u,
                    0x07u, 0x75u, 0x1Bu, 0x56u,
                    0x5Fu, 0xC4u, 0xF9u, 0xB1u,
                },
            },
        },
        {
            "DFComposite_22_a2f0b6c3",
            IDR_IBL_MATERIAL_22_PS,
            {
                10780,
                {
                    0xA2u, 0xF0u, 0xB6u, 0xC3u,
                    0xC1u, 0xD8u, 0x3Fu, 0xBCu,
                    0x75u, 0x00u, 0x48u, 0xFBu,
                    0xE3u, 0x0Fu, 0x06u, 0x2Au,
                },
            },
            {
                12268,
                {
                    0xC9u, 0xD3u, 0x6Cu, 0x22u,
                    0x47u, 0xB9u, 0x5Au, 0xAAu,
                    0x32u, 0xF0u, 0xFFu, 0x02u,
                    0x36u, 0x0Eu, 0xA7u, 0x66u,
                },
            },
        },
        {
            "DFComposite_23_a5f7c7bd",
            IDR_IBL_MATERIAL_23_PS,
            {
                5204,
                {
                    0xA5u, 0xF7u, 0xC7u, 0xBDu,
                    0x0Cu, 0xBAu, 0x2Fu, 0x60u,
                    0x6Cu, 0x45u, 0xC2u, 0x53u,
                    0xEBu, 0x76u, 0x11u, 0xE9u,
                },
            },
            {
                6692,
                {
                    0x7Du, 0x05u, 0x57u, 0x15u,
                    0xA5u, 0xBDu, 0x8Du, 0x50u,
                    0x04u, 0xEEu, 0xB0u, 0xE4u,
                    0x96u, 0x8Au, 0xF4u, 0x81u,
                },
            },
        },
        {
            "DFComposite_24_a8327fff",
            IDR_IBL_MATERIAL_24_PS,
            {
                10996,
                {
                    0xA8u, 0x32u, 0x7Fu, 0xFFu,
                    0xEFu, 0x3Fu, 0x9Du, 0xD2u,
                    0x1Fu, 0x66u, 0x69u, 0xF9u,
                    0x12u, 0x18u, 0x52u, 0x03u,
                },
            },
            {
                12484,
                {
                    0xCCu, 0x9Eu, 0x16u, 0xBDu,
                    0x87u, 0xB0u, 0xF8u, 0xC3u,
                    0xE8u, 0xD4u, 0xFDu, 0x96u,
                    0x4Fu, 0x73u, 0x3Eu, 0x9Fu,
                },
            },
        },
        {
            "DFComposite_25_aa07c786",
            IDR_IBL_MATERIAL_25_PS,
            {
                3520,
                {
                    0xAAu, 0x07u, 0xC7u, 0x86u,
                    0x90u, 0x32u, 0xEBu, 0x3Au,
                    0x4Bu, 0xD1u, 0xBDu, 0x16u,
                    0x46u, 0xEFu, 0xDAu, 0x22u,
                },
            },
            {
                5048,
                {
                    0xB5u, 0x12u, 0x1Cu, 0x8Du,
                    0xF6u, 0x2Eu, 0x08u, 0x21u,
                    0xAAu, 0xC9u, 0xA1u, 0x88u,
                    0x18u, 0x9Au, 0x0Bu, 0xCBu,
                },
            },
        },
        {
            "DFComposite_26_af688028",
            IDR_IBL_MATERIAL_26_PS,
            {
                3392,
                {
                    0xAFu, 0x68u, 0x80u, 0x28u,
                    0x35u, 0x97u, 0xF0u, 0xA1u,
                    0x3Fu, 0x3Au, 0x39u, 0x0Eu,
                    0xDDu, 0x68u, 0x48u, 0x48u,
                },
            },
            {
                4920,
                {
                    0xB6u, 0xF9u, 0x71u, 0xE6u,
                    0x78u, 0xA7u, 0xD4u, 0x6Au,
                    0xE4u, 0x47u, 0x31u, 0xB2u,
                    0xA3u, 0x75u, 0xBEu, 0x2Au,
                },
            },
        },
        {
            "DFComposite_27_b4314b33",
            IDR_IBL_MATERIAL_27_PS,
            {
                3492,
                {
                    0xB4u, 0x31u, 0x4Bu, 0x33u,
                    0x0Cu, 0x8Du, 0x12u, 0xA9u,
                    0xF0u, 0x85u, 0x42u, 0xB8u,
                    0xA5u, 0xC0u, 0x22u, 0xE9u,
                },
            },
            {
                5020,
                {
                    0x4Eu, 0x86u, 0xB5u, 0x9Cu,
                    0x16u, 0x50u, 0xD8u, 0xA7u,
                    0x75u, 0xE1u, 0xCFu, 0x54u,
                    0xE1u, 0xA8u, 0xCFu, 0x1Fu,
                },
            },
        },
        {
            "DFComposite_28_bcd6111c",
            IDR_IBL_MATERIAL_28_PS,
            {
                3384,
                {
                    0xBCu, 0xD6u, 0x11u, 0x1Cu,
                    0x0Bu, 0xADu, 0x9Eu, 0x84u,
                    0x77u, 0x97u, 0xA6u, 0xD0u,
                    0x31u, 0x10u, 0x8Au, 0xA8u,
                },
            },
            {
                4912,
                {
                    0xD4u, 0xB8u, 0x9Du, 0xB8u,
                    0x05u, 0xBEu, 0x01u, 0x27u,
                    0xB7u, 0x81u, 0x04u, 0x1Au,
                    0x92u, 0x2Au, 0x41u, 0x9Bu,
                },
            },
        },
        {
            "DFComposite_29_bf35d56c",
            IDR_IBL_MATERIAL_29_PS,
            {
                5300,
                {
                    0xBFu, 0x35u, 0xD5u, 0x6Cu,
                    0x33u, 0x85u, 0x54u, 0x07u,
                    0x3Fu, 0x37u, 0xC9u, 0x4Au,
                    0x66u, 0x30u, 0x52u, 0x52u,
                },
            },
            {
                6788,
                {
                    0x6Du, 0x27u, 0x66u, 0x1Du,
                    0xA0u, 0xBCu, 0x58u, 0x4Cu,
                    0x36u, 0xF3u, 0x59u, 0xF6u,
                    0x9Au, 0x78u, 0xCBu, 0x11u,
                },
            },
        },
        {
            "DFComposite_30_c22cdaf9",
            IDR_IBL_MATERIAL_30_PS,
            {
                9248,
                {
                    0xC2u, 0x2Cu, 0xDAu, 0xF9u,
                    0xEBu, 0xA9u, 0x12u, 0x4Bu,
                    0x3Bu, 0x7Eu, 0xF2u, 0x8Eu,
                    0x50u, 0x13u, 0x74u, 0x4Bu,
                },
            },
            {
                10736,
                {
                    0x20u, 0x27u, 0xC1u, 0x85u,
                    0x9Cu, 0x03u, 0x17u, 0xD4u,
                    0x38u, 0x3Du, 0x93u, 0x70u,
                    0xF6u, 0x87u, 0x01u, 0x27u,
                },
            },
        },
        {
            "DFComposite_31_c7212564",
            IDR_IBL_MATERIAL_31_PS,
            {
                3488,
                {
                    0xC7u, 0x21u, 0x25u, 0x64u,
                    0x14u, 0x44u, 0xC8u, 0xACu,
                    0x71u, 0xAEu, 0x92u, 0x3Bu,
                    0x35u, 0x67u, 0x95u, 0x4Bu,
                },
            },
            {
                5016,
                {
                    0x65u, 0xACu, 0xC1u, 0x75u,
                    0x87u, 0x26u, 0x68u, 0x01u,
                    0xA1u, 0xDFu, 0xDCu, 0x72u,
                    0x2Bu, 0x3Bu, 0xB1u, 0xAAu,
                },
            },
        },
        {
            "DFComposite_32_c80f14ce",
            IDR_IBL_MATERIAL_32_PS,
            {
                9136,
                {
                    0xC8u, 0x0Fu, 0x14u, 0xCEu,
                    0x79u, 0x4Cu, 0x85u, 0xA1u,
                    0x62u, 0xDBu, 0x77u, 0x0Bu,
                    0xCBu, 0x18u, 0x00u, 0x99u,
                },
            },
            {
                10624,
                {
                    0xFEu, 0xE1u, 0x95u, 0x2Du,
                    0x29u, 0xB6u, 0xA4u, 0x9Fu,
                    0xE7u, 0xA3u, 0x89u, 0xFEu,
                    0x02u, 0x3Du, 0x7Fu, 0x17u,
                },
            },
        },
        {
            "DFComposite_33_ccb5c170",
            IDR_IBL_MATERIAL_33_PS,
            {
                3316,
                {
                    0xCCu, 0xB5u, 0xC1u, 0x70u,
                    0x0Au, 0xCAu, 0x81u, 0x0Bu,
                    0x0Cu, 0xD0u, 0x3Eu, 0x08u,
                    0x0Cu, 0x36u, 0x23u, 0xBBu,
                },
            },
            {
                4844,
                {
                    0x73u, 0x75u, 0x44u, 0x7Du,
                    0xEFu, 0x42u, 0xD6u, 0x84u,
                    0x2Du, 0x13u, 0x3Bu, 0x4Eu,
                    0x0Au, 0x1Bu, 0xC9u, 0xDCu,
                },
            },
        },
        {
            "DFComposite_34_d2ea118d",
            IDR_IBL_MATERIAL_34_PS,
            {
                3284,
                {
                    0xD2u, 0xEAu, 0x11u, 0x8Du,
                    0xBBu, 0x2Au, 0x5Fu, 0xE0u,
                    0xD2u, 0x00u, 0x9Fu, 0x25u,
                    0xCBu, 0x27u, 0x23u, 0x43u,
                },
            },
            {
                4812,
                {
                    0x2Au, 0xD3u, 0xE0u, 0xD2u,
                    0x59u, 0xD3u, 0x06u, 0x6Au,
                    0x4Du, 0x19u, 0xB2u, 0xE2u,
                    0xD7u, 0xBCu, 0xEAu, 0xF3u,
                },
            },
        },
        {
            "DFComposite_35_d4640e27",
            IDR_IBL_MATERIAL_35_PS,
            {
                5084,
                {
                    0xD4u, 0x64u, 0x0Eu, 0x27u,
                    0x52u, 0xEEu, 0x85u, 0xC9u,
                    0xC5u, 0x87u, 0x2Bu, 0x4Du,
                    0x8Du, 0x7Cu, 0x04u, 0xEDu,
                },
            },
            {
                6572,
                {
                    0x3Cu, 0x5Cu, 0x48u, 0xD5u,
                    0x6Fu, 0x66u, 0x43u, 0xDFu,
                    0xB5u, 0xA8u, 0xD8u, 0xB8u,
                    0x21u, 0x46u, 0x9Eu, 0xFBu,
                },
            },
        },
        {
            "DFComposite_36_e633fa0d",
            IDR_IBL_MATERIAL_36_PS,
            {
                9036,
                {
                    0xE6u, 0x33u, 0xFAu, 0x0Du,
                    0x0Au, 0xABu, 0x32u, 0xDAu,
                    0xA3u, 0xE9u, 0xF2u, 0x85u,
                    0x88u, 0xC9u, 0xE7u, 0xBCu,
                },
            },
            {
                10524,
                {
                    0x16u, 0xACu, 0x42u, 0x05u,
                    0x16u, 0x25u, 0x12u, 0x2Cu,
                    0x64u, 0x8Cu, 0x8Bu, 0x41u,
                    0x09u, 0xBEu, 0xE1u, 0x1Cu,
                },
            },
        },
        {
            "DFComposite_37_e7b19714",
            IDR_IBL_MATERIAL_37_PS,
            {
                9352,
                {
                    0xE7u, 0xB1u, 0x97u, 0x14u,
                    0x82u, 0x31u, 0x31u, 0x36u,
                    0xCDu, 0x85u, 0xD4u, 0x6Au,
                    0x28u, 0xD1u, 0x81u, 0x86u,
                },
            },
            {
                10840,
                {
                    0x61u, 0x08u, 0xA1u, 0xD0u,
                    0x78u, 0x06u, 0xFFu, 0x99u,
                    0x4Cu, 0x7Fu, 0x10u, 0x29u,
                    0x0Bu, 0xB0u, 0x7Fu, 0x32u,
                },
            },
        },
        {
            "DFComposite_38_eb839491",
            IDR_IBL_MATERIAL_38_PS,
            {
                11100,
                {
                    0xEBu, 0x83u, 0x94u, 0x91u,
                    0xABu, 0x08u, 0xEEu, 0x92u,
                    0xFCu, 0x48u, 0x59u, 0x90u,
                    0x94u, 0x5Bu, 0xBEu, 0xC5u,
                },
            },
            {
                13220,
                {
                    0x81u, 0x52u, 0xDAu, 0x47u,
                    0x91u, 0x9Fu, 0xB4u, 0x1Fu,
                    0xCEu, 0xCEu, 0xA8u, 0x6Fu,
                    0xC4u, 0xDFu, 0x50u, 0x0Eu,
                },
            },
        },
        {
            "DFComposite_39_f77db52d",
            IDR_IBL_MATERIAL_39_PS,
            {
                5104,
                {
                    0xF7u, 0x7Du, 0xB5u, 0x2Du,
                    0x3Du, 0x4Du, 0x4Au, 0x3Au,
                    0x3Au, 0xB0u, 0xB0u, 0x2Du,
                    0x4Eu, 0xA5u, 0xFFu, 0xA0u,
                },
            },
            {
                6592,
                {
                    0xB9u, 0xDBu, 0x11u, 0xCCu,
                    0x26u, 0xAAu, 0xFAu, 0xBFu,
                    0x8Fu, 0x8Cu, 0x29u, 0xD9u,
                    0xC0u, 0x14u, 0x94u, 0x25u,
                },
            },
        },
        {
            "DFComposite_40_fc24da7b",
            IDR_IBL_MATERIAL_40_PS,
            {
                11316,
                {
                    0xFCu, 0x24u, 0xDAu, 0x7Bu,
                    0xBDu, 0xADu, 0x03u, 0x60u,
                    0xE2u, 0x21u, 0xFCu, 0x9Eu,
                    0x45u, 0xADu, 0x2Eu, 0x9Fu,
                },
            },
            {
                13436,
                {
                    0xEEu, 0x65u, 0xEBu, 0x1Cu,
                    0xF4u, 0x09u, 0xFFu, 0xA9u,
                    0x6Du, 0xEBu, 0x8Bu, 0x68u,
                    0xFBu, 0x3Du, 0x99u, 0x27u,
                },
            },
        },
    } };
