// Generated by tools/generate_complex_environment_contracts.py.
// Do not edit this file by hand.
inline constexpr std::array<std::uint16_t, 288>
    kComplexEnvironmentProducerByLinearContract{ {
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 110u, 52u, 63u, 8u,
        0u, 0u, 0u, 10u, 81u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        64u, 58u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 1u, 108u, 0u, 0u, 0u, 0u, 0u, 0u, 109u,
        24u, 0u, 0u, 0u, 0u, 0u, 0u, 99u, 74u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 15u, 68u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 26u, 62u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 12u, 72u, 41u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 11u, 66u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 78u, 50u, 0u, 0u,
        0u, 0u, 103u, 56u, 30u, 51u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 89u, 0u, 0u, 33u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
        84u, 0u, 44u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    } };

inline constexpr std::size_t
    kComplexEnvironmentShaderContractCount = 33;
