//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[8];                     // Offset:    0 Size:   128
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampFaceDetail                    sampler      NA          NA             s8      1 
// SampAdditionalAlpha               sampler      NA          NA            s12      1 
// SampBoneTintLookup                sampler      NA          NA            s13      1 
// SampBoneTintPalette               sampler      NA          NA            s14      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexSpecular                       texture  float4          2d             t2      1 
// TexFaceDetail                     texture  float4          2d             t8      1 
// TexAdditionalAlpha                texture  float4          2d            t12      1 
// TexBoneTintLookup                 texture  float4          2d            t13      1 
// TexBoneTintPalette                texture  float4          2d            t14      1 
// TexAdditionalAlphaNoise           texture  float4          2d            t15      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 6      w        1     NONE   float      w
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    1   xyzw        6     NONE   float      w
// EYEINDEX                 0   x           7     NONE    uint   x   
// SV_IsFrontFace           0   x           8    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[8], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s8, mode_default
dcl_sampler s12, mode_default
dcl_sampler s13, mode_default
dcl_sampler s14, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.w
dcl_input_ps constant v7.x
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 5
ne r0.xy, cb2[5].ywyy, l(0.000000, 0.000000, 0.000000, 0.000000)
if_nz r0.x
  ge r0.xz, v0.xxyx, -v0.xxyx
  movc r0.xz, r0.xxzx, l(1.000000,0,1.000000,0), l(-1.000000,0,-1.000000,0)
  mul r1.xy, r0.xzxx, v0.xyxx
  mul r1.xy, r1.xyxx, l(0.250000, 0.250000, 0.000000, 0.000000)
  frc r1.xy, r1.xyxx
  mul r0.xz, r0.xxzx, r1.xxyx
  mul r0.xz, r0.xxzx, l(4.000000, 0.000000, 4.000000, 0.000000)
  ftoi r1.xy, r0.xzxx
  mov r1.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r0.x, r1.xyzw, t15.xyzw
  add r0.x, -r0.x, l(0.500000)
  mad r0.x, cb2[5].y, r0.x, cb2[5].z
  add r0.x, r0.x, l(-0.500000)
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
if_nz r0.y
  mov r0.x, v4.w
  mov r0.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t12.wxyz, s12
  add r0.x, -r0.x, cb2[5].x
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
mov r0.x, v4.w
mov r0.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r1.xyz, r0.xyxx, t0.xyzw, s0
sample_indexable(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t8.xywz, s8
add r0.z, -r2.z, l(1.000000)
mul r0.z, r0.z, v1.w
mad r0.z, -r0.z, l(0.300000), l(1.000000)
mul r1.xyz, r0.zzzz, r1.xyzx
sample_indexable(texture2d)(float,float,float,float) r3.xz, r0.xyxx, t13.yxwz, s13
frc r3.y, cb2[6].x
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r3.xyxx, t14.xyzw, s14
log r3.xyw, |r4.xyxz|
mul r3.xyw, r3.xyxw, cb5[1].xxxx
exp r3.xyw, r3.xyxw
mul r3.xyw, r3.xyxw, cb5[3].wwww
movc r3.xyw, cb5[0].xxxx, r3.xyxw, r4.xyxz
mul r3.xyw, r4.wwww, r3.xyxw
mul r3.xyz, r3.zzzz, r3.xywx
mul r3.xyz, r3.xyzx, v6.wwww
mul r3.xyz, r3.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
eq r0.z, cb2[4].w, l(-1.000000)
mad r2.zw, -cb2[4].wwwz, cb12[50].xxxx, l(0.000000, 0.000000, 1.000000, 1.000000)
movc r0.z, r0.z, l(1.000000), r2.z
log r4.xyz, |r1.xyzx|
mul r4.xyz, r4.xyzx, cb5[1].xxxx
exp r4.xyz, r4.xyzx
mul r4.xyz, r4.xyzx, cb5[3].wwww
movc r1.xyz, cb5[0].xxxx, r4.xyzx, r1.xyzx
mad o0.xyz, r0.zzzz, r1.xyzx, r3.xyzx
dp3 r0.z, v3.xyzx, v3.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, v3.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.zw, r0.xyxx, t2.zwxy, s2
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t1.xyzw, s1
mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.w, r0.xyxx, r0.xyxx
min r1.w, r1.w, l(1.000000)
add r1.w, -r1.w, l(1.000000)
sqrt r3.z, r1.w
add r4.xy, r2.xyxx, r2.xyxx
mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.w, r2.xyxx, r2.xyxx
min r1.w, r1.w, l(1.000000)
add r1.w, -r1.w, l(1.000000)
sqrt r4.z, r1.w
add r2.xyz, r4.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
mad r2.xyz, v1.wwww, r2.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
dp3 r1.w, r2.xyzx, r2.xyzx
rsq r1.w, r1.w
mad r3.xy, r2.xyxx, r1.wwww, r0.xyxx
dp3 r0.x, r3.xyzx, r3.xyzx
rsq r0.x, r0.x
mul r3.xyz, r0.xxxx, r3.xyzx
movc r3.w, v8.x, r3.z, -r3.z
dp3 r0.x, r1.xyzx, r3.xywx
min r1.z, r0.x, l(0.000000)
dp3 r0.x, v1.xyzx, v1.xyzx
rsq r0.x, r0.x
mul r2.xyz, r0.xxxx, v1.xyzx
dp3 r1.x, r2.xyzx, r3.xywx
dp3 r0.x, v2.xyzx, v2.xyzx
rsq r0.x, r0.x
mul r2.xyz, r0.xxxx, v2.xyzx
dp3 r1.y, r2.xyzx, r3.xywx
dp3 r0.x, r1.xyzx, r1.xyzx
rsq r0.x, r0.x
mul r1.xyz, r0.xxxx, r1.xyzx
mad r0.x, r1.z, l(-8.000000), l(8.000000)
sqrt r0.x, r0.x
div r0.xy, r1.xyxx, r0.xxxx
add o1.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
add r0.x, -cb2[7].z, cb2[7].w
lt r0.y, cb2[7].w, l(0.000000)
movc r0.y, r0.y, l(0), cb12[50].x
mad r0.x, r0.y, r0.x, cb2[7].z
mul r0.y, r0.y, cb2[7].w
ne r1.x, cb2[7].y, l(0.000000)
movc r0.x, r1.x, r0.x, r0.y
mul r0.x, r0.x, l(0.020000)
sqrt o2.z, r0.x
ne r0.x, l(0.000000), cb12[50].x
ne r1.xy, cb2[4].yxyy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.x, r0.x, r1.x
or r0.x, r1.y, r0.x
and o2.x, r0.x, l(0x3f800000)
mul o2.y, cb2[7].x, l(0.003922)
mov_sat o2.w, cb2[7].x
mul r0.x, cb2[4].z, cb12[50].x
mad r0.x, r0.z, r2.w, r0.x
add r0.yz, -cb2[0].xxyx, cb2[2].xxyx
mad r0.yz, r0.yyzy, cb12[50].xxxx, cb2[0].xxyx
mul r0.yz, r0.yyzy, cb2[0].xxyx
ge r1.xy, cb2[2].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.yz, r1.xxyx, r0.yyzy, cb2[0].xxyx
mul o3.xy, r0.wxww, r0.yzyy
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
ishl r0.x, v7.x, l(2)
iadd r1.xyzw, r0.xxxx, l(66, 63, 64, 54)
mov r2.xyz, v4.xyzx
mov r2.w, l(1.000000)
dp4 r0.y, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r1.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r1.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r0.yz, r1.xxyx, r0.yyyy
mov r2.xyz, v5.xyzx
mov r2.w, l(1.000000)
dp4 r0.w, cb12[r1.w + 0].xyzw, r2.xyzw
iadd r1.xy, r0.xxxx, l(51, 52, 0, 0)
dp4 r3.x, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r3.y, cb12[r1.y + 0].xyzw, r2.xyzw
div r0.xw, r3.xxxy, r0.wwww
add r0.xy, -r0.xwxx, r0.yzyy
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
mov o0.w, cb2[0].z
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(0.019608)
ret 
// Approximately 150 instruction slots used
