//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[9];                     // Offset:    0 Size:   144
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampHairDirection                 sampler      NA          NA             s3      1 
// SampGradientRemap                 sampler      NA          NA             s5      1 
// SampAdditionalAlpha               sampler      NA          NA            s12      1 
// SampBoneTintLookup                sampler      NA          NA            s13      1 
// SampBoneTintPalette               sampler      NA          NA            s14      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexHairDirection                  texture  float4          2d             t3      1 
// TexGradientRemap                  texture  float4          2d             t5      1 
// TexAdditionalAlpha                texture  float4          2d            t12      1 
// TexBoneTintLookup                 texture  float4          2d            t13      1 
// TexBoneTintPalette                texture  float4          2d            t14      1 
// TexAdditionalAlphaNoise           texture  float4          2d            t15      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    0   xyzw        6     NONE   float   x  w
// COLOR                    1   xyzw        7     NONE   float      w
// EYEINDEX                 0   x           8     NONE    uint   x   
// SV_IsFrontFace           0   x           9    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[9], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s3, mode_default
dcl_sampler s5, mode_default
dcl_sampler s12, mode_default
dcl_sampler s13, mode_default
dcl_sampler s14, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xw
dcl_input_ps linear v7.w
dcl_input_ps constant v8.x
dcl_input_ps_sgv constant v9.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 6
ne r0.xy, cb2[6].ywyy, l(0.000000, 0.000000, 0.000000, 0.000000)
if_nz r0.x
  ge r0.xz, v0.xxyx, -v0.xxyx
  movc r0.xz, r0.xxzx, l(1.000000,0,1.000000,0), l(-1.000000,0,-1.000000,0)
  mul r1.xy, r0.xzxx, v0.xyxx
  mul r1.xy, r1.xyxx, l(0.250000, 0.250000, 0.000000, 0.000000)
  frc r1.xy, r1.xyxx
  mul r0.xz, r0.xxzx, r1.xxyx
  mul r0.xz, r0.xxzx, l(4.000000, 0.000000, 4.000000, 0.000000)
  ftoi r1.xy, r0.xzxx
  mov r1.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r0.x, r1.xyzw, t15.xyzw
  add r0.x, -r0.x, l(0.500000)
  mad r0.x, cb2[6].y, r0.x, cb2[6].z
  add r0.x, r0.x, l(-0.500000)
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
if_nz r0.y
  mov r0.x, v4.w
  mov r0.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t12.wxyz, s12
  add r0.x, -r0.x, cb2[6].x
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
mov r0.x, v4.w
mov r0.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r0.zw, r0.xyxx, t0.xzyw, s0
mad r0.w, r0.w, v6.w, -cb2[1].w
lt r0.w, r0.w, l(0.000000)
discard_nz r0.w
log r0.w, v6.x
mul r0.w, r0.w, l(0.454545)
exp r0.w, r0.w
add r0.w, r0.w, cb2[2].x
add r1.y, r0.w, l(-1.000000)
log r0.w, r0.z
mul r0.w, r0.w, l(0.454545)
exp r1.x, r0.w
sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t5.xyzw, s5, l(0.000000)
sample_indexable(texture2d)(float,float,float,float) r2.xz, r0.xyxx, t13.yxwz, s13
frc r2.y, cb2[7].x
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.xyxx, t14.xyzw, s14
log r2.xyw, |r3.xyxz|
mul r2.xyw, r2.xyxw, cb5[1].xxxx
exp r2.xyw, r2.xyxw
mul r2.xyw, r2.xyxw, cb5[3].wwww
movc r2.xyw, cb5[0].xxxx, r2.xyxw, r3.xyxz
mul r2.xyw, r3.wwww, r2.xyxw
mul r2.xyz, r2.zzzz, r2.xywx
mul r2.xyz, r2.xyzx, v7.wwww
mul r2.xyz, r2.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
eq r0.w, cb2[5].w, l(-1.000000)
mad r1.w, -cb2[5].w, cb12[50].x, l(1.000000)
movc r0.w, r0.w, l(1.000000), r1.w
log r3.xyz, |r1.xyzx|
mul r3.xyz, r3.xyzx, cb5[1].xxxx
exp r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, cb5[3].wwww
movc r1.xyz, cb5[0].xxxx, r3.xyzx, r1.xyzx
mad o0.xyz, r0.wwww, r1.xyzx, r2.xyzx
dp3 r0.w, v3.xyzx, v3.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, v3.xyzx
sample_indexable(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t3.xyzw, s3
mad r2.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3 r0.w, r2.xyzx, r2.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r2.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t1.xyzw, s1
mad r3.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.x, r3.xyxx, r3.xyxx
min r0.x, r0.x, l(1.000000)
add r0.x, -r0.x, l(1.000000)
sqrt r0.x, r0.x
movc r3.z, v9.x, r0.x, -r0.x
dp3 r0.x, r1.xyzx, r3.xyzx
min r4.z, r0.x, l(0.000000)
dp3 r0.x, v1.xyzx, v1.xyzx
rsq r0.x, r0.x
mul r0.xyw, r0.xxxx, v1.xyxz
dp3 r4.x, r0.xywx, r3.xyzx
dp3 r1.w, v2.xyzx, v2.xyzx
rsq r1.w, r1.w
mul r5.xyz, r1.wwww, v2.xyzx
dp3 r4.y, r5.xyzx, r3.xyzx
dp3 r1.w, r4.xyzx, r4.xyzx
rsq r1.w, r1.w
mul r3.xyz, r1.wwww, r4.xyzx
mad r1.w, r3.z, l(-8.000000), l(8.000000)
sqrt r1.w, r1.w
div r3.xy, r3.xyxx, r1.wwww
add o1.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
add r1.w, -cb2[8].z, cb2[8].w
lt r2.w, cb2[8].w, l(0.000000)
movc r2.w, r2.w, l(0), cb12[50].x
mad r1.w, r2.w, r1.w, cb2[8].z
mul r2.w, r2.w, cb2[8].w
ne r3.x, cb2[8].y, l(0.000000)
movc r1.w, r3.x, r1.w, r2.w
mul r1.w, r1.w, l(0.020000)
sqrt o2.z, r1.w
ne r1.w, l(0.000000), cb12[50].x
ne r3.xy, cb2[5].yxyy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r1.w, r1.w, r3.x
or r1.w, r3.y, r1.w
and o2.x, r1.w, l(0x3f800000)
mul o2.y, cb2[8].x, l(0.003922)
mov_sat o2.w, cb2[8].x
dp3 o3.x, r0.xywx, r2.xyzx
dp3 o3.y, r5.xyzx, r2.xyzx
dp3 o3.z, r1.xyzx, r2.xyzx
max r0.x, cb8[0].x, l(0.000010)
div r0.xyw, cb2[1].xyxz, r0.xxxx
log r0.xyw, |r0.xyxw|
mul r0.xyw, r0.xyxw, cb5[1].yyyy
exp r0.xyw, r0.xyxw
mul r0.xyw, r0.xyxw, cb8[0].xxxx
mul r0.xyw, r0.xyxw, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xywx, cb2[1].xyzx
ishl r0.x, v8.x, l(2)
iadd r1.xyzw, r0.xxxx, l(66, 63, 64, 54)
mov r2.xyz, v4.xyzx
mov r2.w, l(1.000000)
dp4 r0.y, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r1.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r1.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r0.yw, r1.xxxy, r0.yyyy
mov r2.xyz, v5.xyzx
mov r2.w, l(1.000000)
dp4 r1.x, cb12[r1.w + 0].xyzw, r2.xyzw
iadd r1.yz, r0.xxxx, l(0, 51, 52, 0)
dp4 r3.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r3.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r1.xy, r3.xyxx, r1.xxxx
add r0.xy, r0.ywyy, -r1.xyxx
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
mov o0.w, r0.z
mov o3.w, l(0.003922)
ret 
// Approximately 141 instruction slots used
