//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[11];                    // Offset:    0 Size:   176
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[51];                   // Offset:    0 Size:   816
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampMeatCuffDiffuse               sampler      NA          NA             s9      1 
// SampMeatCuffNormal                sampler      NA          NA            s10      1 
// SampMeatCuffSpecular              sampler      NA          NA            s11      1 
// SampAdditionalAlpha               sampler      NA          NA            s12      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexSpecular                       texture  float4          2d             t2      1 
// TexMeatCuffDiffuse                texture  float4          2d             t9      1 
// TexMeatCuffNormal                 texture  float4          2d            t10      1 
// TexMeatCuffSpecular               texture  float4          2d            t11      1 
// TexAdditionalAlpha                texture  float4          2d            t12      1 
// TexAdditionalAlphaNoise           texture  float4          2d            t15      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float      w
// TEXCOORD                 4   xyzw        5     NONE   float      w
// COLOR                    0   xyzw        6     NONE   float   xyzw
// TEXCOORD                 6   xy          7     NONE   float   x   
// TEXCOORD                 7   xyz         8     NONE   float   xyz 
// TEXCOORD                 8   xyz         9     NONE   float   xyz 
// TEXCOORD                 9   xyz        10     NONE   float   xyz 
// EYEINDEX                 0   x          11     NONE    uint       
// SV_IsFrontFace           0   x          12    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyzw        4   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[11], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[51], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_sampler s12, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.w
dcl_input_ps linear v5.w
dcl_input_ps linear v6.xyzw
dcl_input_ps linear v7.x
dcl_input_ps linear v8.xyz
dcl_input_ps linear v9.xyz
dcl_input_ps linear v10.xyz
dcl_input_ps_sgv constant v12.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_temps 13
ne r0.xy, cb2[9].ywyy, l(0.000000, 0.000000, 0.000000, 0.000000)
if_nz r0.x
  ge r0.xz, v0.xxyx, -v0.xxyx
  movc r0.xz, r0.xxzx, l(1.000000,0,1.000000,0), l(-1.000000,0,-1.000000,0)
  mul r1.xy, r0.xzxx, v0.xyxx
  mul r1.xy, r1.xyxx, l(0.250000, 0.250000, 0.000000, 0.000000)
  frc r1.xy, r1.xyxx
  mul r0.xz, r0.xxzx, r1.xxyx
  mul r0.xz, r0.xxzx, l(4.000000, 0.000000, 4.000000, 0.000000)
  ftoi r1.xy, r0.xzxx
  mov r1.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r0.x, r1.xyzw, t15.xyzw
  add r0.x, -r0.x, l(0.500000)
  mad r0.x, cb2[9].y, r0.x, cb2[9].z
  add r0.x, r0.x, l(-0.500000)
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
if_nz r0.y
  mov r0.x, v4.w
  mov r0.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t12.wxyz, s12
  add r0.x, -r0.x, cb2[9].x
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
dp3 r0.x, v1.xyzx, v1.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, v1.xyzx
dp3 r0.w, v2.xyzx, v2.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, v2.xyzx
dp3 r0.w, v3.xyzx, v3.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, v3.xyzx
lt r0.w, v7.x, l(0.000000)
lt r1.w, l(10.000000), v7.x
or r0.w, r0.w, r1.w
if_nz r0.w
  mov r3.x, v4.w
  mov r3.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r3.xyxx, t0.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r3.xyxx, t1.xyzw, s1
  sample_indexable(texture2d)(float,float,float,float) r3.xy, r3.xyxx, t2.xyzw, s2
  mad r5.xyz, r5.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
  movc r5.w, v12.x, r5.y, -r5.y
  dp3 r6.x, r0.xyzx, r5.xzwx
  dp3 r6.y, r1.xyzx, r5.xzwx
  dp3 r0.w, r2.xyzx, r5.xzwx
  mul r5.xyzw, r4.xyzw, v6.xyzw
  log r7.xyz, |cb2[3].xyzx|
  mul r7.xyz, r7.xyzx, l(0.454545, 0.454545, 0.454545, 0.000000)
  exp r7.xyz, r7.xyzx
  log r8.xyz, |r5.xyzx|
  mul r8.xyz, r8.xyzx, l(0.454545, 0.454545, 0.454545, 0.000000)
  exp r8.xyz, r8.xyzx
  add r9.xyz, r8.xyzx, r8.xyzx
  mul r10.xyz, r8.xyzx, r8.xyzx
  mad r11.xyz, -r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r10.xyz, r10.xyzx, r11.xyzx
  mad r10.xyz, r9.xyzx, r7.xyzx, r10.xyzx
  sqrt r8.xyz, r8.xyzx
  mad r11.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
  add r12.xyz, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r9.xyz, r9.xyzx, r12.xyzx
  mad r8.xyz, r8.xyzx, r11.xyzx, r9.xyzx
  lt r7.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  movc r7.xyz, r7.xyzx, r10.xyzx, r8.xyzx
  log r7.xyz, |r7.xyzx|
  mul r7.xyz, r7.xyzx, l(2.200000, 2.200000, 2.200000, 0.000000)
  exp r7.xyz, r7.xyzx
  mad r4.xyz, -r4.xyzx, v6.xyzx, r7.xyzx
  mad r5.xyz, cb2[3].wwww, r4.xyzx, r5.xyzx
  discard_nz l(-1)
else 
  dp3 r1.w, cb2[7].xyzx, v8.xyzx
  mad r1.w, r1.w, l(0.500000), l(0.500000)
  dp3 r2.w, cb2[8].xyzx, v8.xyzx
  lt r2.w, l(0.000000), r2.w
  mul r3.z, r1.w, l(0.500000)
  mad r1.w, -r1.w, l(0.500000), l(1.000000)
  movc r4.x, r2.w, r3.z, r1.w
  mul r4.y, v7.x, l(0.100000)
  add r3.zw, -r4.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
  sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r3.zwzz, t9.xyzw, s9
  sample_indexable(texture2d)(float,float,float,float) r3.xy, r3.zwzz, t11.xyzw, s11
  sample_indexable(texture2d)(float,float,float,float) r3.zw, r4.xyxx, t10.zwxy, s10
  mad r3.zw, r3.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
  dp2 r1.w, r3.zwzz, r3.zwzz
  add r1.w, -r1.w, l(1.000000)
  sqrt r1.w, r1.w
  mul r4.xyz, r3.zzzz, v9.xyzx
  mad r4.xyz, r3.wwww, v10.xyzx, r4.xyzx
  mad r4.xyz, r1.wwww, v8.xyzx, r4.xyzx
  dp3 r1.w, r4.xyzx, r4.xyzx
  rsq r1.w, r1.w
  mul r4.xyz, r1.wwww, r4.xyzx
  dp3 r6.x, r0.xyzx, r4.xyzx
  dp3 r6.y, r1.xyzx, r4.xyzx
  dp3 r0.w, r2.xyzx, r4.xyzx
endif 
add r0.xy, -cb2[0].xyxx, cb2[4].xyxx
mad r0.xy, r0.xyxx, cb12[50].xxxx, cb2[0].xyxx
mul r0.xy, r0.xyxx, cb2[0].xyxx
ge r1.xy, cb2[4].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.xy, r1.xyxx, r0.xyxx, cb2[0].xyxx
mul r0.z, cb2[6].z, cb12[50].x
mad r1.xy, -cb2[6].zwzz, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mad r0.z, r3.x, r1.x, r0.z
mul o3.x, r3.y, r0.x
mul o3.y, r0.z, r0.y
min r6.z, r0.w, l(0.000000)
dp3 r0.x, r6.xyzx, r6.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, r6.xyzx
mov o1.z, -r0.z
mad r0.z, r0.z, l(-8.000000), l(8.000000)
sqrt r0.z, r0.z
div r0.xy, r0.xyxx, r0.zzzz
add o1.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
lt r0.x, cb2[10].w, l(0.000000)
movc r0.x, r0.x, l(0), cb12[50].x
add r0.y, -cb2[10].z, cb2[10].w
ne r0.z, cb2[10].y, l(0.000000)
mad r0.y, r0.x, r0.y, cb2[10].z
mul r0.x, r0.x, cb2[10].w
movc r0.x, r0.z, r0.y, r0.x
mul r0.x, r0.x, l(0.020000)
sqrt o2.z, r0.x
ne r0.x, cb12[50].x, l(0.000000)
ne r0.yz, cb2[6].yyxy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x
and o2.x, r0.x, l(0x3f800000)
mul o2.y, cb2[10].x, l(0.003922)
mov_sat o2.w, cb2[10].x
eq r0.x, cb2[2].y, l(1.000000)
movc r0.x, r0.x, r5.w, l(1.000000)
mul r0.y, r0.x, cb2[2].x
mad r0.x, cb2[2].x, r0.x, l(-0.015686)
lt r0.x, r0.x, l(0.000000)
discard_nz r0.x
eq r0.x, cb2[6].w, l(-1.000000)
movc r0.x, r0.x, l(1.000000), r1.y
log r1.xyz, |r5.xyzx|
mul r1.xyz, r1.xyzx, cb5[1].xxxx
exp r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, cb5[3].wwww
movc r1.xyz, cb5[0].xxxx, r1.xyzx, r5.xyzx
mul o0.xyz, r0.xxxx, r1.xyzx
max r0.x, cb8[0].x, l(0.000010)
div r0.xzw, cb2[1].xxyz, r0.xxxx
log r0.xzw, |r0.xxzw|
mul r0.xzw, r0.xxzw, cb5[1].yyyy
exp r0.xzw, r0.xxzw
mul r0.xzw, r0.xxzw, cb8[0].xxxx
mul r0.xzw, r0.xxzw, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xzwx, cb2[1].xyzx
mov o0.w, r0.y
mov o1.w, r0.y
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(0.019608)
mov o4.w, r0.y
ret 
// Approximately 164 instruction slots used
