//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[6];                     // Offset:    0 Size:    96
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
// Resource bind info for CombinedMaterials
// {
//
//   struct CombinedMaterialData
//   {
//       
//       float4 material;               // Offset:    0
//       float4 emitColorAndAlphaReference;// Offset:   16
//       float4 interpolationAndProperties;// Offset:   32
//       float4 reserved;               // Offset:   48
//       uint4 textureSlices;           // Offset:   64
//       uint gradientTextureSlice;     // Offset:   80
//       float gradientRow;             // Offset:   84
//       float depth;                   // Offset:   88
//
//   } $Element;                        // Offset:    0 Size:    92
//
// }
//
// Resource bind info for CombinedDepths
// {
//
//   struct CombinedDepthData
//   {
//       
//       float4 reserved[6];            // Offset:    0
//       float value;                   // Offset:   96
//
//   } $Element;                        // Offset:    0 Size:   100
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampAdditionalAlpha               sampler      NA          NA            s12      1 
// TexDiffuse                        texture  float4     2darray             t0      1 
// TexNormal                         texture  float4     2darray             t1      1 
// TexSpecular                       texture  float4     2darray             t2      1 
// CombinedMaterials                 texture  struct         r/o             t4      1 
// CombinedDepths                    texture  struct         r/o             t6      1 
// TexAdditionalAlpha                texture  float4          2d            t12      1 
// TexAdditionalAlphaNoise           texture  float4          2d            t15      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    0   xyzw        6     NONE   float   xyzw
// COLOR                    2   x           7     NONE    uint   x   
// EYEINDEX                 0    y          7     NONE    uint    y  
// SV_IsFrontFace           0   x           8    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[6], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s12, mode_default
dcl_resource_texture2darray (float,float,float,float) t0
dcl_resource_texture2darray (float,float,float,float) t1
dcl_resource_texture2darray (float,float,float,float) t2
dcl_resource_structured t4, 92
dcl_resource_structured t6, 100
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyzw
dcl_input_ps constant v7.x
dcl_input_ps constant v7.y
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 10
ne r0.xy, cb2[5].ywyy, l(0.000000, 0.000000, 0.000000, 0.000000)
if_nz r0.x
  ge r0.xz, v0.xxyx, -v0.xxyx
  movc r0.xz, r0.xxzx, l(1.000000,0,1.000000,0), l(-1.000000,0,-1.000000,0)
  mul r1.xy, r0.xzxx, v0.xyxx
  mul r1.xy, r1.xyxx, l(0.250000, 0.250000, 0.000000, 0.000000)
  frc r1.xy, r1.xyxx
  mul r0.xz, r0.xxzx, r1.xxyx
  mul r0.xz, r0.xxzx, l(4.000000, 0.000000, 4.000000, 0.000000)
  ftoi r1.xy, r0.xzxx
  mov r1.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r0.x, r1.xyzw, t15.xyzw
  add r0.x, -r0.x, l(0.500000)
  mad r0.x, cb2[5].y, r0.x, cb2[5].z
  add r0.x, r0.x, l(-0.500000)
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
if_nz r0.y
  mov r0.x, v4.w
  mov r0.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t12.wxyz, s12
  add r0.x, -r0.x, cb2[5].x
  lt r0.x, r0.x, l(0.000000)
  discard_nz r0.x
endif 
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r0.xyzw, v7.x, l(0), t4.xyzw
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r1.xyzw, v7.x, l(16), t4.xyzw
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r2.xyzw, v7.x, l(32), t4.xyzw
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r3.xyz, v7.x, l(64), t4.xyzx
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r3.w, v7.x, l(88), t4.xxxx
utof r3.xyz, r3.xyzx
mov r4.x, v4.w
mov r4.y, v5.w
mov r4.zw, r3.xxxy
sample_indexable(texture2darray)(float,float,float,float) r5.xyzw, r4.xyzx, t0.xyzw, s0
mul r5.xyz, r5.xyzx, v6.xyzx
mad r1.w, r5.w, v6.w, -r1.w
lt r1.w, r1.w, l(0.000000)
discard_nz r1.w
sample_indexable(texture2darray)(float,float,float,float) r4.zw, r4.xywx, t1.zwxy, s1
mad r6.xy, r4.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.w, r6.xyxx, r6.xyxx
min r1.w, r1.w, l(1.000000)
add r1.w, -r1.w, l(1.000000)
sqrt r1.w, r1.w
movc r6.z, v8.x, r1.w, -r1.w
dp3 r1.w, v3.xyzx, v3.xyzx
rsq r1.w, r1.w
mul r7.xyz, r1.wwww, v3.xyzx
dp3 r1.w, v1.xyzx, v1.xyzx
rsq r1.w, r1.w
mul r8.xyz, r1.wwww, v1.xyzx
dp3 r8.x, r8.xyzx, r6.xyzx
dp3 r1.w, v2.xyzx, v2.xyzx
rsq r1.w, r1.w
mul r9.xyz, r1.wwww, v2.xyzx
dp3 r8.y, r9.xyzx, r6.xyzx
dp3 r1.w, r7.xyzx, r6.xyzx
min r8.z, r1.w, l(0.000000)
dp3 r1.w, r8.xyzx, r8.xyzx
rsq r1.w, r1.w
mul r6.xyz, r1.wwww, r8.xyzx
mad r1.w, r6.z, l(-8.000000), l(8.000000)
sqrt r1.w, r1.w
div r4.zw, r6.xxxy, r1.wwww
add o1.xy, r4.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
mov r3.xy, r4.xyxx
sample_indexable(texture2darray)(float,float,float,float) r3.xy, r3.xyzx, t2.xyzw, s2
mad r4.xy, -r2.zwzz, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r1.w, r2.z, cb12[50].x
mad r1.w, r3.x, r4.x, r1.w
eq r4.xzw, r2.yyxw, l(-1.000000, 0.000000, -1.000000, -1.000000)
movc r2.zw, r4.xxxz, l(0,0,0,0), cb12[50].xxxx
add r2.xy, -r0.xyxx, r2.yxyy
mad r2.xy, r2.xyxx, r2.zwzz, r0.xyxx
mul o3.x, r2.x, r3.y
mul r0.x, r0.y, r1.w
mul o3.y, r2.y, r0.x
mul o3.z, r0.w, l(0.010000)
mul r0.x, r3.w, l(0.020000)
sqrt o2.z, r0.x
ne r0.x, l(0.000000), cb12[50].x
ne r0.yw, cb2[4].xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.x, r0.w, r0.x
or r0.x, r0.x, r0.y
and o2.x, r0.x, l(0x3f800000)
ld_structured_indexable(structured_buffer, stride=100)(mixed,mixed,mixed,mixed) r0.x, v7.x, l(96), t6.xxxx
mul o2.y, r0.x, l(0.003922)
mov_sat o2.w, r0.x
movc r0.x, r4.w, l(1.000000), r4.y
log r2.xyz, |r5.xyzx|
mul r2.xyz, r2.xyzx, cb5[1].xxxx
exp r2.xyz, r2.xyzx
mul r2.xyz, r2.xyzx, cb5[3].wwww
movc r2.xyz, cb5[0].xxxx, r2.xyzx, r5.xyzx
mul o0.xyz, r0.xxxx, r2.xyzx
max r0.x, cb8[0].x, l(0.000010)
div r0.xyw, r1.xyxz, r0.xxxx
log r0.xyw, |r0.xyxw|
mul r0.xyw, r0.xyxw, cb5[1].yyyy
exp r0.xyw, r0.xyxw
mul r0.xyw, r0.xyxw, cb8[0].xxxx
mul r0.xyw, r0.xyxw, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xywx, r1.xyzx
ishl r0.x, v7.y, l(2)
iadd r1.xyzw, r0.xxxx, l(66, 63, 64, 54)
mov r2.xyz, v4.xyzx
mov r2.w, l(1.000000)
dp4 r0.y, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r1.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r1.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r0.yw, r1.xxxy, r0.yyyy
mov r2.xyz, v5.xyzx
mov r2.w, l(1.000000)
dp4 r1.x, cb12[r1.w + 0].xyzw, r2.xyzw
iadd r1.yz, r0.xxxx, l(0, 51, 52, 0)
dp4 r3.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r3.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r1.xy, r3.xyxx, r1.xxxx
add r0.xy, r0.ywyy, -r1.xyxx
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
mov o0.w, r0.z
mov o3.w, l(1.000000)
ret 
// Approximately 125 instruction slots used
