#define LINEAR_LIGHTING_ALPHA_TEST 1
#define LINEAR_LIGHTING_BONE_TINTING 1
#define LINEAR_LIGHTING_GRADIENT_HAIR 1
#define LINEAR_LIGHTING_GRADIENT_REMAP 1
#define LINEAR_LIGHTING_HAIR 1
#define LINEAR_LIGHTING_VERTEX_COLOR 1
#include "DefaultSixMrt_L4_00000002.LinearLightingCandidate.hlsl"
