#define LINEAR_LIGHTING_BONE_TINTING 1
#define LINEAR_LIGHTING_FACE_DETAIL 1
#define LINEAR_LIGHTING_VERTEX_COLOR 1
#define LINEAR_LIGHTING_VERTEX_ALPHA 0
#include "DefaultSixMrt_L4_00000002.LinearLightingCandidate.hlsl"
