//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions:
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[8];                     // Offset:    0 Size:   128
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer ComplexEnvironmentMaterialDraw
// {
//
//   uint enableComplexEnvironmentMaterial;// Offset:    0 Size:     4
//   float3 complexEnvironmentMaterialPadding;// Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1
// SampNormal                        sampler      NA          NA             s1      1
// SampSpecular                      sampler      NA          NA             s2      1
// SampGradientRemap                 sampler      NA          NA             s5      1
// SampBoneTintLookup                sampler      NA          NA            s13      1
// SampBoneTintPalette               sampler      NA          NA            s14      1
// TexDiffuse                        texture  float4          2d             t0      1
// TexNormal                         texture  float4          2d             t1      1
// TexSpecular                       texture  float4          2d             t2      1
// TexGradientRemap                  texture  float4          2d             t5      1
// TexBoneTintLookup                 texture  float4          2d            t13      1
// TexBoneTintPalette                texture  float4          2d            t14      1
// PerMaterial                       cbuffer      NA          NA            cb2      1
// LinearLightingFrame               cbuffer      NA          NA            cb5      1
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1
// ComplexEnvironmentMaterialDraw    cbuffer      NA          NA           cb11      1
// PerGeometry                       cbuffer      NA          NA           cb12      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float
// TEXCOORD                 0   xyz         1     NONE   float   xyz
// TEXCOORD                 1   xyz         2     NONE   float   xyz
// TEXCOORD                 2   xyz         3     NONE   float   xyz
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    1   xyzw        6     NONE   float      w
// EYEINDEX                 0   x           7     NONE    uint   x
// SV_IsFrontFace           0   x           8    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz
// SV_Target                5   xy          5   TARGET   float   xy
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[8], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB11[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s5, mode_default
dcl_sampler s13, mode_default
dcl_sampler s14, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.w
dcl_input_ps constant v7.x
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 6
mov r0.x, v4.w
mov r0.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r0.zw, r0.xyxx, t0.xzyw, s0
add r0.w, r0.w, -cb2[1].w
lt r0.w, r0.w, l(0.000000)
discard_nz r0.w
log r0.z, r0.z
mul r0.z, r0.z, l(0.454545)
exp r1.x, r0.z
mov r1.y, cb2[2].x
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, r1.xyxx, t5.xyzw, s5, l(0.000000)
sample_indexable(texture2d)(float,float,float,float) r2.xz, r0.xyxx, t13.yxwz, s13
frc r2.y, cb2[6].x
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r2.xyxx, t14.xyzw, s14
log r2.xyw, |r3.xyxz|
mul r2.xyw, r2.xyxw, cb5[1].xxxx
exp r2.xyw, r2.xyxw
mul r2.xyw, r2.xyxw, cb5[3].wwww
movc r2.xyw, cb5[0].xxxx, r2.xyxw, r3.xyxz
mul r2.xyw, r3.wwww, r2.xyxw
mul r2.xyz, r2.zzzz, r2.xywx
mul r2.xyz, r2.xyzx, v6.wwww
mul r2.xyz, r2.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
eq r0.z, cb2[5].w, l(-1.000000)
mad r3.xy, -cb2[5].wzww, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
movc r0.z, r0.z, l(1.000000), r3.x
mul r3.xzw, r1.xxyz, cb5[3].wwww
movc r1.xyz, cb5[0].xxxx, r3.xzwx, r1.xyzx
mad r1.xyz, r0.zzzz, r1.xyzx, r2.xyzx
dp3 r0.z, v3.xyzx, v3.xyzx
rsq r0.z, r0.z
mul r2.xyz, r0.zzzz, v3.xyzx
sample_indexable(texture2d)(float,float,float,float) r3.xzw, r0.xyxx, t2.zwxy, s2
if_nz cb11[0].x
  sample_l_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.xyxx, t2.xyzw, s2, l(15.000000)
  add r5.xyz, -r4.yzzy, r4.xxyx
  lt r5.xyz, |r5.xyzx|, l(0.015686, 0.015686, 0.015686, 0.000000)
  and r0.z, r5.y, r5.x
  and r0.z, r5.z, r0.z
  lt r5.xyzw, r4.xyzw, l(0.015686, 0.015686, 0.015686, 0.984314)
  and r0.w, r5.y, r5.x
  and r0.w, r5.z, r0.w
  lt r2.w, l(0.015686), r4.w
  and r0.w, r0.w, r2.w
  and r0.w, r5.w, r0.w
  not r0.z, r0.z
  or r0.z, r0.w, r0.z
  and r0.z, r0.z, r5.w
  lt r0.w, l(0.015686), r3.w
  and r0.z, r0.w, r0.z
  mov_sat r3.x, r3.x
  mad r4.x, -r3.x, l(0.500000), l(1.000000)
  add r0.w, -r3.x, l(1.000000)
  max r4.y, r0.w, l(0.003922)
  movc r4.xz, r0.zzzz, r4.yyxy, l(1.000000,0,1.000000,0)
else
  mov r4.xz, l(1.000000,0,1.000000,0)
endif
mul o0.xyz, r1.xyzx, r4.xxxx
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t1.xyzw, s1
mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.w, r0.xyxx, r0.xyxx
min r0.w, r0.w, l(1.000000)
add r0.w, -r0.w, l(1.000000)
sqrt r0.w, r0.w
movc r0.z, v8.x, r0.w, -r0.w
dp3 r0.w, r2.xyzx, r0.xyzx
min r1.z, r0.w, l(0.000000)
dp3 r0.w, v1.xyzx, v1.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, v1.xyzx
dp3 r1.x, r2.xyzx, r0.xyzx
dp3 r0.w, v2.xyzx, v2.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, v2.xyzx
dp3 r1.y, r2.xyzx, r0.xyzx
dp3 r0.x, r1.xyzx, r1.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, r1.xyzx
mad r0.z, r0.z, l(-8.000000), l(8.000000)
sqrt r0.z, r0.z
div r0.xy, r0.xyxx, r0.zzzz
add o1.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
add r0.x, -cb2[7].z, cb2[7].w
lt r0.y, cb2[7].w, l(0.000000)
movc r0.y, r0.y, l(0), cb12[50].x
mad r0.x, r0.y, r0.x, cb2[7].z
mul r0.y, r0.y, cb2[7].w
ne r0.z, cb2[7].y, l(0.000000)
movc r0.x, r0.z, r0.x, r0.y
mul r0.x, r0.x, l(0.020000)
sqrt o2.z, r0.x
ne r0.x, l(0.000000), cb12[50].x
ne r0.yz, cb2[5].yyxy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x
and o2.x, r0.x, l(0x3f800000)
mul o2.y, cb2[7].x, l(0.003922)
mov_sat o2.w, cb2[7].x
mul r0.x, cb2[5].z, cb12[50].x
mad r0.x, r3.z, r3.y, r0.x
mul r0.y, r1.w, r3.w
add r0.zw, -cb2[0].xxxy, cb2[3].xxxy
mad r0.zw, r0.zzzw, cb12[50].xxxx, cb2[0].xxxy
mul r0.zw, r0.zzzw, cb2[0].xxxy
ge r1.xy, cb2[3].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.zw, r1.xxxy, r0.zzzw, cb2[0].xxxy
mul r4.xy, r0.yxyy, r0.zwzz
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
ishl r0.x, v7.x, l(2)
iadd r1.xyzw, r0.xxxx, l(66, 63, 64, 54)
mov r2.xyz, v4.xyzx
mov r2.w, l(1.000000)
dp4 r0.y, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r1.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r1.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r0.yz, r1.xxyx, r0.yyyy
mov r2.xyz, v5.xyzx
mov r2.w, l(1.000000)
dp4 r0.w, cb12[r1.w + 0].xyzw, r2.xyzw
iadd r1.xy, r0.xxxx, l(51, 52, 0, 0)
dp4 r3.x, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r3.y, cb12[r1.y + 0].xyzw, r2.xyzw
div r0.xw, r3.xxxy, r0.wwww
add r0.xy, -r0.xwxx, r0.yzyy
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
mov o0.w, cb2[0].z
mul r4.w, cb2[0].w, l(0.010000)
mov o3.xyzw, r4.xywz
ret
// Approximately 137 instruction slots used
