//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[6];                     // Offset:    0 Size:    96
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
// Resource bind info for CombinedMaterials
// {
//
//   struct CombinedMaterialData
//   {
//       
//       float4 material;               // Offset:    0
//       float4 emitColorAndAlphaReference;// Offset:   16
//       float4 interpolationAndProperties;// Offset:   32
//       float4 reserved;               // Offset:   48
//       uint4 textureSlices;           // Offset:   64
//       uint gradientTextureSlice;     // Offset:   80
//       float gradientRow;             // Offset:   84
//       float depth;                   // Offset:   88
//
//   } $Element;                        // Offset:    0 Size:    92
//
// }
//
// Resource bind info for CombinedDepths
// {
//
//   struct CombinedDepthData
//   {
//       
//       float4 reserved[6];            // Offset:    0
//       float value;                   // Offset:   96
//
//   } $Element;                        // Offset:    0 Size:   100
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampGradientRemap                 sampler      NA          NA             s5      1 
// TexDiffuse                        texture  float4     2darray             t0      1 
// TexNormal                         texture  float4     2darray             t1      1 
// TexSpecular                       texture  float4     2darray             t2      1 
// CombinedMaterials                 texture  struct         r/o             t4      1 
// TexGradientRemap                  texture  float4     2darray             t5      1 
// CombinedDepths                    texture  struct         r/o             t6      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    2   x           6     NONE    uint   x   
// EYEINDEX                 0    y          6     NONE    uint    y  
// SV_IsFrontFace           0   x           7    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[6], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s5, mode_default
dcl_resource_texture2darray (float,float,float,float) t0
dcl_resource_texture2darray (float,float,float,float) t1
dcl_resource_texture2darray (float,float,float,float) t2
dcl_resource_structured t4, 92
dcl_resource_texture2darray (float,float,float,float) t5
dcl_resource_structured t6, 100
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps constant v6.x
dcl_input_ps constant v6.y
dcl_input_ps_sgv constant v7.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 8
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r0.xyz, v6.x, l(64), t4.xyzx
utof r0.xyz, r0.xyzx
mov r1.zw, r0.xxxy
mov r1.x, v4.w
mov r1.y, v5.w
sample_indexable(texture2darray)(float,float,float,float) r2.xy, r1.xyzx, t0.ywxz, s0
sample_indexable(texture2darray)(float,float,float,float) r1.zw, r1.xywx, t1.zwxy, s1
mov r0.xy, r1.xyxx
sample_indexable(texture2darray)(float,float,float,float) r0.xy, r0.xyzx, t2.xyzw, s2
mad r1.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r3.xyzw, v6.x, l(16), t4.xyzw
add r0.z, r2.y, -r3.w
log r0.w, r2.x
mul r0.w, r0.w, l(0.454545)
exp r2.x, r0.w
lt r0.z, r0.z, l(0.000000)
discard_nz r0.z
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r4.xyz, v6.x, l(80), t4.xyzx
utof r2.z, r4.x
mov r2.y, r4.y
mul r0.z, r4.z, l(0.020000)
sqrt o2.z, r0.z
sample_l_indexable(texture2darray)(float,float,float,float) r2.xyzw, r2.xyzx, t5.xyzw, s5, l(0.000000)
log r4.xyz, |r2.xyzx|
mul r4.xyz, r4.xyzx, cb5[1].xxxx
exp r4.xyz, r4.xyzx
mul r4.xyz, r4.xyzx, cb5[3].wwww
movc r2.xyz, cb5[0].xxxx, r4.xyzx, r2.xyzx
mul r0.y, r0.y, r2.w
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r4.xyzw, v6.x, l(32), t4.xyzw
mad r0.zw, -r4.zzzw, cb12[50].xxxx, l(0.000000, 0.000000, 1.000000, 1.000000)
eq r5.xyz, r4.yxwy, l(-1.000000, -1.000000, -1.000000, 0.000000)
movc r0.w, r5.z, l(1.000000), r0.w
movc r5.xy, r5.xyxx, l(0,0,0,0), cb12[50].xxxx
mul o0.xyz, r2.xyzx, r0.wwww
ld_structured_indexable(structured_buffer, stride=92)(mixed,mixed,mixed,mixed) r2.xyzw, v6.x, l(0), t4.xyzw
mov o0.w, r2.z
dp3 r0.w, v3.xyzx, v3.xyzx
rsq r0.w, r0.w
mul r6.xyz, r0.wwww, v3.xyzx
dp2 r0.w, r1.xyxx, r1.xyxx
min r0.w, r0.w, l(1.000000)
add r0.w, -r0.w, l(1.000000)
sqrt r0.w, r0.w
movc r1.z, v7.x, r0.w, -r0.w
dp3 r0.w, r6.xyzx, r1.xyzx
min r6.z, r0.w, l(0.000000)
dp3 r0.w, v1.xyzx, v1.xyzx
rsq r0.w, r0.w
mul r7.xyz, r0.wwww, v1.xyzx
dp3 r6.x, r7.xyzx, r1.xyzx
dp3 r0.w, v2.xyzx, v2.xyzx
rsq r0.w, r0.w
mul r7.xyz, r0.wwww, v2.xyzx
dp3 r6.y, r7.xyzx, r1.xyzx
dp3 r0.w, r6.xyzx, r6.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r6.xyzx
mad r0.w, r1.z, l(-8.000000), l(8.000000)
sqrt r0.w, r0.w
div r1.xy, r1.xyxx, r0.wwww
add o1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
ne r0.w, l(0.000000), cb12[50].x
ne r1.xy, cb2[5].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.w, r0.w, r1.y
or r0.w, r0.w, r1.x
and o2.x, r0.w, l(0x3f800000)
ld_structured_indexable(structured_buffer, stride=100)(mixed,mixed,mixed,mixed) r0.w, v6.x, l(96), t6.xxxx
mul o2.y, r0.w, l(0.003922)
mov_sat o2.w, r0.w
mul r0.w, r4.z, cb12[50].x
add r1.xy, -r2.xyxx, r4.yxyy
mad r1.xy, r1.xyxx, r5.xyxx, r2.xyxx
mad r0.x, r0.x, r0.z, r0.w
mul r0.x, r0.x, r2.y
mul o3.z, r2.w, l(0.010000)
mul o3.xy, r0.yxyy, r1.xyxx
mov o3.w, l(1.000000)
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, r3.xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, r3.xyzx
mov r0.xyz, v4.xyzx
mov r0.w, l(1.000000)
ishl r1.x, v6.y, l(2)
iadd r2.xyzw, r1.xxxx, l(66, 63, 64, 54)
iadd r1.xy, r1.xxxx, l(51, 52, 0, 0)
dp4 r1.z, cb12[r2.x + 0].xyzw, r0.xyzw
dp4 r2.x, cb12[r2.y + 0].xyzw, r0.xyzw
dp4 r2.y, cb12[r2.z + 0].xyzw, r0.xyzw
div r0.xy, r2.xyxx, r1.zzzz
mov r3.xyz, v5.xyzx
mov r3.w, l(1.000000)
dp4 r0.z, cb12[r2.w + 0].xyzw, r3.xyzw
dp4 r2.x, cb12[r1.x + 0].xyzw, r3.xyzw
dp4 r2.y, cb12[r1.y + 0].xyzw, r3.xyzw
div r0.zw, r2.xxxy, r0.zzzz
add r0.xy, -r0.zwzz, r0.xyxx
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
ret 
// Approximately 104 instruction slots used
