//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions:
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[11];                    // Offset:    0 Size:   176
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[51];                   // Offset:    0 Size:   816
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1
// SampNormal                        sampler      NA          NA             s1      1
// SampSpecular                      sampler      NA          NA             s2      1
// SampDismembermentDiffuse          sampler      NA          NA             s9      1
// SampDismembermentNormal           sampler      NA          NA            s10      1
// SampDismembermentSpecular         sampler      NA          NA            s11      1
// TexDiffuse                        texture  float4          2d             t0      1
// TexNormal                         texture  float4          2d             t1      1
// TexSpecular                       texture  float4          2d             t2      1
// TexDismembermentDiffuse           texture  float4          2d             t9      1
// TexDismembermentNormal            texture  float4          2d            t10      1
// TexDismembermentSpecular          texture  float4          2d            t11      1
// PerMaterial                       cbuffer      NA          NA            cb2      1
// LinearLightingFrame               cbuffer      NA          NA            cb5      1
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1
// PerGeometry                       cbuffer      NA          NA           cb12      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float
// TEXCOORD                 0   xy          1     NONE   float   xy
// TEXCOORD                 4     zw        1     NONE   float     zw
// COLOR                    0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyz         3     NONE   float   xyz
// TEXCOORD                 2   xyz         4     NONE   float   xyz
// TEXCOORD                 3   xyz         5     NONE   float   xyz
// TEXCOORD                 5   xy          6     NONE   float    y
// EYEINDEX                 0   x           7     NONE    uint
// SV_IsFrontFace           0   x           8    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyzw        4   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[11], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[51], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.zw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.y
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_temps 6
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0
lt r1.x, l(0.000000), v6.y
sample_indexable(texture2d)(float,float,float,float) r1.yz, v1.zwzz, t11.zxyw, s11
sample_indexable(texture2d)(float,float,float,float) r2.xy, v1.xyxx, t2.xyzw, s2
movc r2.xy, r1.xxxx, r1.zyzz, r2.yxyy
if_nz r1.x
  sample_indexable(texture2d)(float,float,float,float) r1.yz, v1.zwzz, t10.zxyw, s10
  mad r3.xy, r1.yzyy, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r1.y, r3.xyxx, r3.xyxx
  add r1.y, -r1.y, l(1.000000)
  sqrt r3.z, r1.y
  dp3 r4.x, cb2[6].xyzx, r3.xyzx
  dp3 r4.y, cb2[7].xyzx, r3.xyzx
  dp3 r1.y, cb2[8].xyzx, r3.xyzx
else
  sample_indexable(texture2d)(float,float,float,float) r1.zw, v1.xyxx, t1.zwxy, s1
  mad r3.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r1.z, r3.xyxx, r3.xyxx
  min r1.z, r1.z, l(1.000000)
  add r1.z, -r1.z, l(1.000000)
  sqrt r1.z, r1.z
  movc r3.z, v8.x, r1.z, -r1.z
  dp3 r1.z, v3.xyzx, v3.xyzx
  rsq r1.z, r1.z
  mul r5.xyz, r1.zzzz, v3.xyzx
  dp3 r4.x, r5.xyzx, r3.xyzx
  dp3 r1.z, v4.xyzx, v4.xyzx
  rsq r1.z, r1.z
  mul r5.xyz, r1.zzzz, v4.xyzx
  dp3 r4.y, r5.xyzx, r3.xyzx
  dp3 r1.z, v5.xyzx, v5.xyzx
  rsq r1.z, r1.z
  mul r5.xyz, r1.zzzz, v5.xyzx
  dp3 r1.y, r5.xyzx, r3.xyzx
endif
add r1.zw, -cb2[0].xxxy, cb2[3].xxxy
mad r1.zw, r1.zzzw, cb12[50].xxxx, cb2[0].xxxy
mul r1.zw, r1.zzzw, cb2[0].xxxy
ge r3.xy, cb2[3].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r1.zw, r3.xxxy, r1.zzzw, cb2[0].xxxy
mul r2.w, cb2[5].z, cb12[50].x
mad r3.xy, -cb2[5].zwzz, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mad r2.z, r2.y, r3.x, r2.w
mul o3.xy, r1.zwzz, r2.xzxx
min r4.z, r1.y, l(0.000000)
dp3 r1.y, r4.xyzx, r4.xyzx
rsq r1.y, r1.y
mul r1.yzw, r1.yyyy, r4.xxyz
mov o1.z, -r1.w
mad r1.w, r1.w, l(-8.000000), l(8.000000)
sqrt r1.w, r1.w
div r1.yz, r1.yyzy, r1.wwww
add o1.xy, r1.yzyy, l(0.500000, 0.500000, 0.000000, 0.000000)
lt r1.y, cb2[10].w, l(0.000000)
movc r1.y, r1.y, l(0), cb12[50].x
add r1.z, -cb2[10].z, cb2[10].w
ne r1.w, cb2[10].y, l(0.000000)
mad r1.z, r1.y, r1.z, cb2[10].z
mul r1.y, r1.y, cb2[10].w
movc r1.y, r1.w, r1.z, r1.y
mul r1.y, r1.y, l(0.020000)
sqrt o2.z, r1.y
ne r1.y, cb12[50].x, l(0.000000)
ne r1.zw, cb2[5].yyyx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r1.y, r1.z, r1.y
or r1.y, r1.w, r1.y
and o2.x, r1.y, l(0x3f800000)
mul o2.y, cb2[10].x, l(0.003922)
mov_sat o2.w, cb2[10].x
mul r0.xyzw, r0.wxyz, v2.wxyz
eq r1.y, cb2[2].y, l(1.000000)
movc r0.x, r1.y, r0.x, l(1.000000)
mul r1.y, r0.x, cb2[2].x
mad r0.x, cb2[2].x, r0.x, l(-0.015686)
lt r0.x, r0.x, l(0.000000)
discard_nz r0.x
sample_indexable(texture2d)(float,float,float,float) r2.xyz, v1.zwzz, t9.xyzw, s9
movc r0.xyz, r1.xxxx, r2.xyzx, r0.yzwy
eq r0.w, cb2[5].w, l(-1.000000)
movc r0.w, r0.w, l(1.000000), r3.y
log r1.xzw, |r0.xxyz|
mul r1.xzw, r1.xxzw, cb5[1].xxxx
exp r1.xzw, r1.xxzw
mul r1.xzw, r1.xxzw, cb5[3].wwww
movc r0.xyz, cb5[0].xxxx, r1.xzwx, r0.xyzx
mul o0.xyz, r0.xyzx, r0.wwww
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
mov o0.w, r1.y
mov o1.w, r1.y
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, r1.y
mov o4.w, r1.y
ret
// Approximately 100 instruction slots used
