//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[6];                     // Offset:    0 Size:    96
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampFaceDetail                    sampler      NA          NA             s8      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexSpecular                       texture  float4          2d             t2      1 
// TexFaceDetail                     texture  float4          2d             t8      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 6      w        1     NONE   float      w
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// EYEINDEX                 0   x           6     NONE    uint   x   
// SV_IsFrontFace           0   x           7    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[6], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s8, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t8
dcl_input_ps linear v1.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps constant v6.x
dcl_input_ps_sgv constant v7.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 4
mov r0.x, v4.w
mov r0.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyxx, t0.xyzw, s0
add r0.z, r1.w, -cb2[1].w
lt r0.z, r0.z, l(0.000000)
discard_nz r0.z
sample_indexable(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t8.xywz, s8
add r0.z, -r2.z, l(1.000000)
mul r0.z, r0.z, v1.w
mad r0.z, -r0.z, l(0.300000), l(1.000000)
mul r1.xyz, r0.zzzz, r1.xyzx
log r3.xyz, |r1.xyzx|
mul r3.xyz, r3.xyzx, cb5[1].xxxx
exp r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, cb5[3].wwww
movc r1.xyz, cb5[0].xxxx, r3.xyzx, r1.xyzx
eq r0.z, cb2[4].w, l(-1.000000)
mad r2.zw, -cb2[4].wwwz, cb12[50].xxxx, l(0.000000, 0.000000, 1.000000, 1.000000)
movc r0.z, r0.z, l(1.000000), r2.z
mul o0.xyz, r1.xyzx, r0.zzzz
mov o0.w, cb2[0].z
mad r0.zw, r2.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
add r1.xy, r2.xyxx, r2.xyxx
dp2 r0.z, r0.zwzz, r0.zwzz
min r0.z, r0.z, l(1.000000)
add r0.z, -r0.z, l(1.000000)
sqrt r1.z, r0.z
add r1.xyz, r1.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
mad r1.xyz, v1.wwww, r1.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
dp3 r0.z, r1.xyzx, r1.xyzx
rsq r0.z, r0.z
sample_indexable(texture2d)(float,float,float,float) r1.zw, r0.xyxx, t1.zwxy, s1
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t2.xyzw, s2
mad r1.zw, r1.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
mad r2.xy, r1.xyxx, r0.zzzz, r1.zwzz
dp2 r0.z, r1.zwzz, r1.zwzz
min r0.z, r0.z, l(1.000000)
add r0.z, -r0.z, l(1.000000)
sqrt r2.z, r0.z
dp3 r0.z, r2.xyzx, r2.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, r2.xyzx
movc r1.w, v7.x, r1.z, -r1.z
dp3 r0.z, v3.xyzx, v3.xyzx
rsq r0.z, r0.z
mul r2.xyz, r0.zzzz, v3.xyzx
dp3 r0.z, r2.xyzx, r1.xywx
min r2.z, r0.z, l(0.000000)
dp3 r0.z, v1.xyzx, v1.xyzx
rsq r0.z, r0.z
mul r3.xyz, r0.zzzz, v1.xyzx
dp3 r2.x, r3.xyzx, r1.xywx
dp3 r0.z, v2.xyzx, v2.xyzx
rsq r0.z, r0.z
mul r3.xyz, r0.zzzz, v2.xyzx
dp3 r2.y, r3.xyzx, r1.xywx
dp3 r0.z, r2.xyzx, r2.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, r2.xyzx
mad r0.z, r1.z, l(-8.000000), l(8.000000)
sqrt r0.z, r0.z
div r0.zw, r1.xxxy, r0.zzzz
add o1.xy, r0.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
add r0.z, -cb2[5].z, cb2[5].w
lt r0.w, cb2[5].w, l(0.000000)
movc r0.w, r0.w, l(0), cb12[50].x
mad r0.z, r0.w, r0.z, cb2[5].z
mul r0.w, r0.w, cb2[5].w
ne r1.x, cb2[5].y, l(0.000000)
movc r0.z, r1.x, r0.z, r0.w
mul r0.z, r0.z, l(0.020000)
sqrt o2.z, r0.z
ne r0.z, l(0.000000), cb12[50].x
ne r1.xy, cb2[4].yxyy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.z, r0.z, r1.x
or r0.z, r1.y, r0.z
and o2.x, r0.z, l(0x3f800000)
mul o2.y, cb2[5].x, l(0.003922)
mov_sat o2.w, cb2[5].x
mul r0.z, cb2[4].z, cb12[50].x
mad r0.x, r0.x, r2.w, r0.z
add r0.zw, -cb2[0].xxxy, cb2[2].xxxy
mad r0.zw, r0.zzzw, cb12[50].xxxx, cb2[0].xxxy
mul r0.zw, r0.zzzw, cb2[0].xxxy
ge r1.xy, cb2[2].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.zw, r1.xxxy, r0.zzzw, cb2[0].xxxy
mul o3.xy, r0.yxyy, r0.zwzz
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(0.019608)
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
mov r0.xyz, v4.xyzx
mov r0.w, l(1.000000)
ishl r1.x, v6.x, l(2)
iadd r2.xyzw, r1.xxxx, l(66, 63, 64, 54)
iadd r1.xy, r1.xxxx, l(51, 52, 0, 0)
dp4 r1.z, cb12[r2.x + 0].xyzw, r0.xyzw
dp4 r2.x, cb12[r2.y + 0].xyzw, r0.xyzw
dp4 r2.y, cb12[r2.z + 0].xyzw, r0.xyzw
div r0.xy, r2.xyxx, r1.zzzz
mov r3.xyz, v5.xyzx
mov r3.w, l(1.000000)
dp4 r0.z, cb12[r2.w + 0].xyzw, r3.xyzw
dp4 r2.x, cb12[r1.x + 0].xyzw, r3.xyzw
dp4 r2.y, cb12[r1.y + 0].xyzw, r3.xyzw
div r0.zw, r2.xxxy, r0.zzzz
add r0.xy, -r0.zwzz, r0.xyxx
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
ret 
// Approximately 115 instruction slots used
