//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions:
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[10];                    // Offset:    0 Size:   160
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1
// SampNormal                        sampler      NA          NA             s1      1
// SampSpecular                      sampler      NA          NA             s2      1
// SampGlow                          sampler      NA          NA             s3      1
// SampDismembermentDiffuse          sampler      NA          NA             s9      1
// SampDismembermentNormal           sampler      NA          NA            s10      1
// SampDismembermentSpecular         sampler      NA          NA            s11      1
// TexDiffuse                        texture  float4          2d             t0      1
// TexNormal                         texture  float4          2d             t1      1
// TexSpecular                       texture  float4          2d             t2      1
// TexGlow                           texture  float4          2d             t3      1
// TexDismembermentDiffuse           texture  float4          2d             t9      1
// TexDismembermentNormal            texture  float4          2d            t10      1
// TexDismembermentSpecular          texture  float4          2d            t11      1
// PerMaterial                       cbuffer      NA          NA            cb2      1
// LinearLightingFrame               cbuffer      NA          NA            cb5      1
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1
// PerGeometry                       cbuffer      NA          NA           cb12      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float
// TEXCOORD                 0   xy          1     NONE   float   xy
// TEXCOORD                 4     zw        1     NONE   float     zw
// COLOR                    0   xyzw        2     NONE   float   xyz
// TEXCOORD                 1   xyz         3     NONE   float   xyz
// TEXCOORD                 2   xyz         4     NONE   float   xyz
// TEXCOORD                 3   xyz         5     NONE   float   xyz
// TEXCOORD                 5   xy          6     NONE   float    y
// POSITION                 1   xyzw        7     NONE   float   xyz
// POSITION                 2   xyzw        8     NONE   float
// EYEINDEX                 0   x           9     NONE    uint   x
// SV_IsFrontFace           0   x          10    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz
// SV_Target                5   xy          5   TARGET   float   xy
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[10], immediateIndexed
dcl_constantbuffer CB5[6], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.zw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.y
dcl_input_ps linear v7.xyz
dcl_input_ps constant v9.x
dcl_input_ps_sgv constant v10.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 4
lt r0.x, l(0.000000), v6.y
if_nz r0.x
  sample_indexable(texture2d)(float,float,float,float) r0.yz, v1.zwzz, t11.zxyw, s11
  sample_indexable(texture2d)(float,float,float,float) r1.xy, v1.zwzz, t10.xyzw, s10
  mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.w, r1.xyxx, r1.xyxx
  add r0.w, -r0.w, l(1.000000)
  sqrt r1.z, r0.w
  dp3 r2.x, cb2[5].xyzx, r1.xyzx
  dp3 r2.y, cb2[6].xyzx, r1.xyzx
  dp3 r0.w, cb2[7].xyzx, r1.xyzx
  min r2.z, r0.w, l(0.000000)
else
  sample_indexable(texture2d)(float,float,float,float) r0.yz, v1.xyxx, t2.zxyw, s2
  sample_indexable(texture2d)(float,float,float,float) r1.xy, v1.xyxx, t1.xyzw, s1
  mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.w, r1.xyxx, r1.xyxx
  min r0.w, r0.w, l(1.000000)
  add r0.w, -r0.w, l(1.000000)
  sqrt r0.w, r0.w
  movc r1.z, v10.x, r0.w, -r0.w
  dp3 r0.w, v3.xyzx, v3.xyzx
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, v3.xyzx
  dp3 r2.x, r3.xyzx, r1.xyzx
  dp3 r0.w, v4.xyzx, v4.xyzx
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, v4.xyzx
  dp3 r2.y, r3.xyzx, r1.xyzx
  dp3 r0.w, v5.xyzx, v5.xyzx
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, v5.xyzx
  dp3 r0.w, r3.xyzx, r1.xyzx
  min r2.z, r0.w, l(0.000000)
endif
dp3 r0.w, r2.xyzx, r2.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r2.xyzx
mad r0.w, r1.z, l(-8.000000), l(8.000000)
sqrt r0.w, r0.w
div r1.xy, r1.xyxx, r0.wwww
add o1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
add r1.xy, -cb2[0].xyxx, cb2[2].xyxx
mad r1.xy, r1.xyxx, cb12[50].xxxx, cb2[0].xyxx
mul r1.xy, r1.xyxx, cb2[0].xyxx
ge r1.zw, cb2[2].xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r1.xy, r1.zwzz, r1.xyxx, cb2[0].xyxx
mul r0.w, cb2[4].z, cb12[50].x
mad r1.zw, -cb2[4].zzzw, cb12[50].xxxx, l(0.000000, 0.000000, 1.000000, 1.000000)
mad r0.y, r0.y, r1.z, r0.w
mul o3.xy, r0.zyzz, r1.xyxx
lt r0.y, cb2[9].w, l(0.000000)
movc r0.y, r0.y, l(0), cb12[50].x
add r0.z, -cb2[9].z, cb2[9].w
ne r0.w, cb2[9].y, l(0.000000)
mad r0.z, r0.y, r0.z, cb2[9].z
mul r0.y, r0.y, cb2[9].w
movc r0.y, r0.w, r0.z, r0.y
mul r0.y, r0.y, l(0.020000)
sqrt o2.z, r0.y
ne r0.y, l(0.000000), cb12[50].x
ne r0.zw, cb2[4].yyyx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.y, r0.z, r0.y
or r0.y, r0.w, r0.y
and o2.x, r0.y, l(0x3f800000)
mul o2.y, cb2[9].x, l(0.003922)
mov_sat o2.w, cb2[9].x
if_nz r0.x
  sample_indexable(texture2d)(float,float,float,float) r0.xyz, v1.zwzz, t9.xyzw, s9
else
  sample_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t0.xyzw, s0
  mul r0.xyz, r1.xyzx, v2.xyzx
endif
eq r0.w, cb2[4].w, l(-1.000000)
movc r0.w, r0.w, l(1.000000), r1.w
log r1.xyz, |r0.xyzx|
mul r1.xyz, r1.xyzx, cb5[1].xxxx
exp r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, cb5[3].wwww
movc r0.xyz, cb5[0].xxxx, r1.xyzx, r0.xyzx
mul o0.xyz, r0.xyzx, r0.wwww
ishl r0.x, v9.x, l(2)
iadd r1.xyzw, r0.xxxx, l(66, 63, 64, 54)
mov r2.xyz, v7.xyzx
mov r2.w, l(1.000000)
dp4 r0.y, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r1.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r1.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r0.yz, r1.xxyx, r0.yyyy
dp4 r0.w, cb12[r1.w + 0].xyzw, r2.xyzw
iadd r1.xy, r0.xxxx, l(51, 52, 0, 0)
dp4 r3.x, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r3.y, cb12[r1.y + 0].xyzw, r2.xyzw
div r0.xw, r3.xxxy, r0.wwww
add r0.xy, -r0.xwxx, r0.yzyy
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r0.xyz, v1.xyxx, t3.xyzw, s3
log r1.xyz, |r0.xyzx|
mul r1.xyz, r1.xyzx, cb5[1].zzzz
exp r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, cb5[5].xxxx
movc r0.xyz, cb5[0].xxxx, r1.xyzx, r0.xyzx
max r0.w, cb8[0].x, l(0.000010)
div r1.xyz, cb2[1].xyzx, r0.wwww
log r1.xyz, |r1.xyzx|
mul r1.xyz, r1.xyzx, cb5[1].yyyy
exp r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, cb8[0].xxxx
mul r1.xyz, r1.xyzx, cb5[4].wwww
movc r1.xyz, cb5[0].xxxx, r1.xyzx, cb2[1].xyzx
mul o4.xyz, r0.xyzx, r1.xyzx
mov o0.w, cb2[0].z
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(1.000000)
ret
// Approximately 115 instruction slots used
