//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions:
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[7];                     // Offset:    0 Size:   112
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[51];                   // Offset:    0 Size:   816
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1
// SampNormal                        sampler      NA          NA             s1      1
// SampSpecular                      sampler      NA          NA             s2      1
// SampGlow                          sampler      NA          NA             s3      1
// TexDiffuse                        texture  float4          2d             t0      1
// TexNormal                         texture  float4          2d             t1      1
// TexSpecular                       texture  float4          2d             t2      1
// TexGlow                           texture  float4          2d             t3      1
// PerMaterial                       cbuffer      NA          NA            cb2      1
// LinearLightingFrame               cbuffer      NA          NA            cb5      1
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1
// PerGeometry                       cbuffer      NA          NA           cb12      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float
// TEXCOORD                 0   xyz         1     NONE   float   xyz
// TEXCOORD                 1   xyz         2     NONE   float   xyz
// TEXCOORD                 2   xyz         3     NONE   float   xyz
// TEXCOORD                 3   xyzw        4     NONE   float      w
// TEXCOORD                 4   xyzw        5     NONE   float      w
// EYEINDEX                 0   x           6     NONE    uint
// SV_IsFrontFace           0   x           7    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyzw        4   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[7], immediateIndexed
dcl_constantbuffer CB5[6], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[51], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.w
dcl_input_ps linear v5.w
dcl_input_ps_sgv constant v7.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_temps 5
eq r0.x, cb2[2].y, l(1.000000)
mov r1.x, v4.w
mov r1.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyxx, t0.xyzw, s0
movc r0.x, r0.x, r2.w, l(1.000000)
mad r0.y, r0.x, cb2[2].x, l(-0.015686)
mul r0.x, r0.x, cb2[2].x
lt r0.y, r0.y, l(0.000000)
discard_nz r0.y
eq r0.y, cb2[5].w, l(-1.000000)
mad r0.zw, -cb2[5].wwwz, cb12[50].xxxx, l(0.000000, 0.000000, 1.000000, 1.000000)
movc r0.y, r0.y, l(1.000000), r0.z
log r3.xyz, |r2.xyzx|
mul r3.xyz, r3.xyzx, cb5[1].xxxx
exp r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, cb5[3].wwww
movc r2.xyz, cb5[0].xxxx, r3.xyzx, r2.xyzx
mul o0.xyz, r0.yyyy, r2.xyzx
mov o0.w, r0.x
dp3 r0.y, v3.xyzx, v3.xyzx
rsq r0.y, r0.y
mul r2.xyz, r0.yyyy, v3.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.yz, r1.xyxx, t1.zxyw, s1
mad r3.xy, r0.yzyy, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.y, r3.xyxx, r3.xyxx
min r0.y, r0.y, l(1.000000)
add r0.y, -r0.y, l(1.000000)
sqrt r0.y, r0.y
movc r3.z, v7.x, r0.y, -r0.y
dp3 r0.y, r2.xyzx, r3.xyzx
min r2.z, r0.y, l(0.000000)
dp3 r0.y, v1.xyzx, v1.xyzx
rsq r0.y, r0.y
mul r4.xyz, r0.yyyy, v1.xyzx
dp3 r2.x, r4.xyzx, r3.xyzx
dp3 r0.y, v2.xyzx, v2.xyzx
rsq r0.y, r0.y
mul r4.xyz, r0.yyyy, v2.xyzx
dp3 r2.y, r4.xyzx, r3.xyzx
dp3 r0.y, r2.xyzx, r2.xyzx
rsq r0.y, r0.y
mul r2.xyz, r0.yyyy, r2.xyzx
mad r0.y, r2.z, l(-8.000000), l(8.000000)
sqrt r0.y, r0.y
div r0.yz, r2.xxyx, r0.yyyy
mov o1.z, -r2.z
add o1.xy, r0.yzyy, l(0.500000, 0.500000, 0.000000, 0.000000)
mov o1.w, r0.x
add r0.y, -cb2[6].z, cb2[6].w
lt r0.z, cb2[6].w, l(0.000000)
movc r0.z, r0.z, l(0), cb12[50].x
mad r0.y, r0.z, r0.y, cb2[6].z
mul r0.z, r0.z, cb2[6].w
ne r1.z, cb2[6].y, l(0.000000)
movc r0.y, r1.z, r0.y, r0.z
mul r0.y, r0.y, l(0.020000)
sqrt o2.z, r0.y
ne r0.y, cb12[50].x, l(0.000000)
ne r1.zw, cb2[5].yyyx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.y, r0.y, r1.z
or r0.y, r1.w, r0.y
and o2.x, r0.y, l(0x3f800000)
mul o2.y, cb2[6].x, l(0.003922)
mov_sat o2.w, cb2[6].x
sample_indexable(texture2d)(float,float,float,float) r0.yz, r1.xyxx, t2.zxyw, s2
sample_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t3.xyzw, s3
mul r1.w, cb2[5].z, cb12[50].x
mad r0.y, r0.y, r0.w, r1.w
add r2.xy, -cb2[0].xyxx, cb2[3].xyxx
mad r2.xy, r2.xyxx, cb12[50].xxxx, cb2[0].xyxx
mul r2.xy, r2.xyxx, cb2[0].xyxx
ge r2.zw, cb2[3].xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r2.xy, r2.zwzz, r2.xyxx, cb2[0].xyxx
mul o3.xy, r0.zyzz, r2.xyxx
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, r0.x
mov o4.w, r0.x
log r0.xyz, |r1.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].zzzz
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb5[5].xxxx
movc r0.xyz, cb5[0].xxxx, r0.xyzx, r1.xyzx
max r0.w, cb8[0].x, l(0.000010)
div r1.xyz, cb2[1].xyzx, r0.wwww
log r1.xyz, |r1.xyzx|
mul r1.xyz, r1.xyzx, cb5[1].yyyy
exp r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, cb8[0].xxxx
mul r1.xyz, r1.xyzx, cb5[4].wwww
movc r1.xyz, cb5[0].xxxx, r1.xyzx, cb2[1].xyzx
mul o4.xyz, r0.xyzx, r1.xyzx
ret
// Approximately 92 instruction slots used
