#define LINEAR_LIGHTING_ALPHA_TEST 1
#define LINEAR_LIGHTING_FORCE_EARLY_DEPTH 0
#define LINEAR_LIGHTING_GRADIENT_REMAP 1
#define LINEAR_LIGHTING_VERTEX_COLOR 1
#include "DefaultSixMrt_L4_00000002.LinearLightingCandidate.hlsl"
