//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Note: shader requires additional functionality:
//       Early depth-stencil
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[8];                     // Offset:    0 Size:   128
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[51];                   // Offset:    0 Size:   816
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampGradientRemap                 sampler      NA          NA             s5      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexSpecular                       texture  float4          2d             t2      1 
// TexGradientRemap                  texture  float4          2d             t5      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float      w
// TEXCOORD                 4   xyzw        5     NONE   float      w
// COLOR                    0   xyzw        6     NONE   float   x  w
// EYEINDEX                 0   x           7     NONE    uint       
// SV_IsFrontFace           0   x           8    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyzw        4   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | forceEarlyDepthStencil
dcl_constantbuffer CB2[8], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[51], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s5, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t5
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.w
dcl_input_ps linear v5.w
dcl_input_ps linear v6.xw
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_temps 4
mov r0.x, v4.w
mov r0.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r0.zw, r0.xyxx, t0.xzyw, s0
mad r1.x, r0.w, v6.w, -cb2[1].w
lt r1.x, r1.x, l(0.000000)
discard_nz r1.x
eq r1.x, cb2[2].y, l(1.000000)
mul r0.w, r0.w, v6.w
log r0.z, r0.z
mul r0.z, r0.z, l(0.454545)
exp r2.x, r0.z
movc r0.z, r1.x, r0.w, l(1.000000)
mad r0.w, r0.z, cb2[2].x, l(-0.015686)
mul r0.z, r0.z, cb2[2].x
lt r0.w, r0.w, l(0.000000)
discard_nz r0.w
log r0.w, v6.x
mul r0.w, r0.w, l(0.454545)
exp r0.w, r0.w
add r0.w, r0.w, cb2[3].x
add r2.y, r0.w, l(-1.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, r2.xyxx, t5.xyzw, s5, l(0.000000)
log r2.xyz, |r1.xyzx|
mul r2.xyz, r2.xyzx, cb5[1].xxxx
exp r2.xyz, r2.xyzx
mul r2.xyz, r2.xyzx, cb5[3].wwww
movc r1.xyz, cb5[0].xxxx, r2.xyzx, r1.xyzx
eq r0.w, cb2[6].w, l(-1.000000)
mad r2.xy, -cb2[6].wzww, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
movc r0.w, r0.w, l(1.000000), r2.x
mul o0.xyz, r1.xyzx, r0.wwww
mov o0.w, r0.z
dp3 r0.w, v3.xyzx, v3.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, v3.xyzx
sample_indexable(texture2d)(float,float,float,float) r2.xz, r0.xyxx, t1.xzyw, s1
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t2.xyzw, s2
mad r3.xy, r2.xzxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.w, r3.xyxx, r3.xyxx
min r0.w, r0.w, l(1.000000)
add r0.w, -r0.w, l(1.000000)
sqrt r0.w, r0.w
movc r3.z, v8.x, r0.w, -r0.w
dp3 r0.w, r1.xyzx, r3.xyzx
min r1.z, r0.w, l(0.000000)
dp3 r0.w, v1.xyzx, v1.xyzx
rsq r0.w, r0.w
mul r2.xzw, r0.wwww, v1.xxyz
dp3 r1.x, r2.xzwx, r3.xyzx
dp3 r0.w, v2.xyzx, v2.xyzx
rsq r0.w, r0.w
mul r2.xzw, r0.wwww, v2.xxyz
dp3 r1.y, r2.xzwx, r3.xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx
mad r0.w, r1.z, l(-8.000000), l(8.000000)
sqrt r0.w, r0.w
div r1.xy, r1.xyxx, r0.wwww
mov o1.z, -r1.z
add o1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mov o1.w, r0.z
add r0.w, -cb2[7].z, cb2[7].w
lt r1.x, cb2[7].w, l(0.000000)
movc r1.x, r1.x, l(0), cb12[50].x
mad r0.w, r1.x, r0.w, cb2[7].z
mul r1.x, r1.x, cb2[7].w
ne r1.y, cb2[7].y, l(0.000000)
movc r0.w, r1.y, r0.w, r1.x
mul r0.w, r0.w, l(0.020000)
sqrt o2.z, r0.w
ne r0.w, cb12[50].x, l(0.000000)
ne r1.xy, cb2[6].yxyy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.w, r0.w, r1.x
or r0.w, r1.y, r0.w
and o2.x, r0.w, l(0x3f800000)
mul o2.y, cb2[7].x, l(0.003922)
mov_sat o2.w, cb2[7].x
add r1.xy, -cb2[0].xyxx, cb2[4].xyxx
mad r1.xy, r1.xyxx, cb12[50].xxxx, cb2[0].xyxx
mul r1.xy, r1.xyxx, cb2[0].xyxx
ge r2.xz, cb2[4].xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r1.xy, r2.xzxx, r1.xyxx, cb2[0].xyxx
mul r0.y, r0.y, r1.x
mul o3.x, r1.w, r0.y
mul r0.y, cb2[6].z, cb12[50].x
mad r0.x, r0.x, r2.y, r0.y
mul o3.y, r0.x, r1.y
mov o3.w, r0.z
mov o4.w, r0.z
mul o3.z, cb2[0].w, l(0.010000)
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
ret 
// Approximately 100 instruction slots used
