//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions:
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[6];                     // Offset:    0 Size:    96
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
// cbuffer PerInstance
// {
//
//   float4 cb13[900];                  // Offset:    0 Size: 14400
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1
// SampNormal                        sampler      NA          NA             s1      1
// SampSpecular                      sampler      NA          NA             s2      1
// TexDiffuse                        texture  float4          2d             t0      1
// TexNormal                         texture  float4          2d             t1      1
// TexSpecular                       texture  float4          2d             t2      1
// PerMaterial                       cbuffer      NA          NA            cb2      1
// LinearLightingFrame               cbuffer      NA          NA            cb5      1
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1
// PerGeometry                       cbuffer      NA          NA           cb12      1
// PerInstance                       cbuffer      NA          NA           cb13      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float
// TEXCOORD                 0   xyz         1     NONE   float   xyz
// TEXCOORD                 1   xyz         2     NONE   float   xyz
// TEXCOORD                 2   xyz         3     NONE   float   xyz
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    2   x           6     NONE    uint   x
// EYEINDEX                 0    y          6     NONE    uint    y
// SV_IsFrontFace           0   x           7    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz
// SV_Target                5   xy          5   TARGET   float   xy
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[6], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_constantbuffer CB13[900], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps constant v6.x
dcl_input_ps constant v6.y
dcl_input_ps_sgv constant v7.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 5
eq r0.x, cb2[4].w, l(-1.000000)
mad r0.yz, -cb2[4].wwzw, cb12[50].xxxx, l(0.000000, 1.000000, 1.000000, 0.000000)
movc r0.x, r0.x, l(1.000000), r0.y
mov r1.x, v4.w
mov r1.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r2.xyz, r1.xyxx, t0.xyzw, s0
log r3.xyz, |r2.xyzx|
mul r3.xyz, r3.xyzx, cb5[1].xxxx
exp r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, cb5[3].wwww
movc r2.xyz, cb5[0].xxxx, r3.xyzx, r2.xyzx
mul o0.xyz, r0.xxxx, r2.xyzx
imad r0.xy, v6.xxxx, l(6, 6, 0, 0), l(4, 5, 0, 0)
mov o0.w, cb13[r0.x + 0].z
dp3 r0.w, v3.xyzx, v3.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, v3.xyzx
sample_indexable(texture2d)(float,float,float,float) r1.zw, r1.xyxx, t1.zwxy, s1
sample_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t2.xyzw, s2
mad r3.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.w, r3.xyxx, r3.xyxx
min r0.w, r0.w, l(1.000000)
add r0.w, -r0.w, l(1.000000)
sqrt r0.w, r0.w
movc r3.z, v7.x, r0.w, -r0.w
dp3 r0.w, r2.xyzx, r3.xyzx
min r2.z, r0.w, l(0.000000)
dp3 r0.w, v1.xyzx, v1.xyzx
rsq r0.w, r0.w
mul r4.xyz, r0.wwww, v1.xyzx
dp3 r2.x, r4.xyzx, r3.xyzx
dp3 r0.w, v2.xyzx, v2.xyzx
rsq r0.w, r0.w
mul r4.xyz, r0.wwww, v2.xyzx
dp3 r2.y, r4.xyzx, r3.xyzx
dp3 r0.w, r2.xyzx, r2.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r2.xyzx
mad r0.w, r2.z, l(-8.000000), l(8.000000)
sqrt r0.w, r0.w
div r1.zw, r2.xxxy, r0.wwww
add o1.xy, r1.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
add r0.w, -cb2[5].z, cb2[5].w
lt r1.z, cb2[5].w, l(0.000000)
movc r1.z, r1.z, l(0), cb12[50].x
mad r0.w, r1.z, r0.w, cb2[5].z
mul r1.z, r1.z, cb2[5].w
ne r1.w, cb2[5].y, l(0.000000)
movc r0.w, r1.w, r0.w, r1.z
mul r0.w, r0.w, l(0.020000)
sqrt o2.z, r0.w
ne r0.w, l(0.000000), cb12[50].x
ne r1.zw, cb2[4].yyyx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.w, r0.w, r1.z
or r0.w, r1.w, r0.w
and o2.x, r0.w, l(0x3f800000)
mul o2.y, cb2[5].x, l(0.003922)
mov_sat o2.w, cb2[5].x
mul r0.w, cb2[4].z, cb12[50].x
mad r0.z, r1.x, r0.z, r0.w
mul o3.x, r1.y, cb13[r0.x + 0].x
mul o3.y, r0.z, cb13[r0.x + 0].y
mov o3.w, l(1.000000)
mul o3.z, l(0.010000), cb13[r0.x + 0].w
max r0.x, cb8[0].x, l(0.000010)
div r0.xzw, cb13[r0.y + 0].xxyz, r0.xxxx
log r0.xzw, |r0.xxzw|
mul r0.xzw, r0.xxzw, cb5[1].yyyy
exp r0.xzw, r0.xxzw
mul r0.xzw, r0.xxzw, cb8[0].xxxx
mul r0.xzw, r0.xxzw, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xzwx, cb13[r0.y + 0].xyzx
mov r0.xyz, v4.xyzx
mov r0.w, l(1.000000)
ishl r1.x, v6.y, l(2)
iadd r2.xyzw, r1.xxxx, l(66, 63, 64, 54)
iadd r1.xy, r1.xxxx, l(51, 52, 0, 0)
dp4 r1.z, cb12[r2.x + 0].xyzw, r0.xyzw
dp4 r2.x, cb12[r2.y + 0].xyzw, r0.xyzw
dp4 r2.y, cb12[r2.z + 0].xyzw, r0.xyzw
div r0.xy, r2.xyxx, r1.zzzz
mov r3.xyz, v5.xyzx
mov r3.w, l(1.000000)
dp4 r0.z, cb12[r2.w + 0].xyzw, r3.xyzw
dp4 r2.x, cb12[r1.x + 0].xyzw, r3.xyzw
dp4 r2.y, cb12[r1.y + 0].xyzw, r3.xyzw
div r0.zw, r2.xxxy, r0.zzzz
add r0.xy, -r0.zwzz, r0.xyxx
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
ret
// Approximately 90 instruction slots used
