//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[9];                     // Offset:    0 Size:   144
//
// }
//
// cbuffer LandscapeLodGlobals
// {
//
//   float4 cb0;                        // Offset:    0 Size:    16
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
// Resource bind info for LandscapeIndices
// {
//
//   struct LandscapeLayerIndices
//   {
//       
//       float4 reserved0;              // Offset:    0
//       float2 reserved1;              // Offset:   16
//       uint lodTextureSlice;          // Offset:   24
//       uint diffuse0;                 // Offset:   28
//       uint normal0;                  // Offset:   32
//       uint specular0;                // Offset:   36
//       uint diffuse1;                 // Offset:   40
//       uint normal1;                  // Offset:   44
//       uint specular1;                // Offset:   48
//       uint diffuse2;                 // Offset:   52
//       uint normal2;                  // Offset:   56
//       uint specular2;                // Offset:   60
//       uint diffuse3;                 // Offset:   64
//       uint normal3;                  // Offset:   68
//       uint specular3;                // Offset:   72
//
//   } $Element;                        // Offset:    0 Size:    76
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Samp0                             sampler      NA          NA             s0      1 
// Samp1                             sampler      NA          NA             s1      1 
// Samp2                             sampler      NA          NA             s2      1 
// Samp3                             sampler      NA          NA             s3      1 
// SampLandscapeLodDiffuse           sampler      NA          NA            s13      1 
// SampLandscapeLodNormal            sampler      NA          NA            s15      1 
// TexDiffuseLayers                  texture  float4     2darray             t0      1 
// TexNormalLayers                   texture  float4     2darray             t1      1 
// TexSpecularLayers                 texture  float4     2darray             t2      1 
// TexLodMultiplierLayers            texture  float4     2darray             t3      1 
// LandscapeIndices                  texture  struct         r/o             t4      1 
// TexLandscapeLodDiffuse            texture  float4          2d            t13      1 
// TexLandscapeLodNormal             texture  float4          2d            t15      1 
// LandscapeLodGlobals               cbuffer      NA          NA            cb0      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    0   xyzw        6     NONE   float   xyz 
// COLOR                    2   x           7     NONE    uint   x   
// EYEINDEX                 0    y          7     NONE    uint    y  
// TEXCOORD                 6   xy          8     NONE   float   xy  
// TEXCOORD                 7   xyzw        9     NONE   float   xyzw
// TEXCOORD                 8   xyz        10     NONE   float   xyz 
// SV_IsFrontFace           0   x          11    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[9], immediateIndexed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s13, mode_default
dcl_sampler s15, mode_default
dcl_resource_texture2darray (float,float,float,float) t0
dcl_resource_texture2darray (float,float,float,float) t1
dcl_resource_texture2darray (float,float,float,float) t2
dcl_resource_texture2darray (float,float,float,float) t3
dcl_resource_structured t4, 76
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyz
dcl_input_ps constant v7.x
dcl_input_ps constant v7.y
dcl_input_ps linear v8.xy
dcl_input_ps linear v9.xyzw
dcl_input_ps linear v10.xyz
dcl_input_ps_sgv constant v11.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 8
ld_structured_indexable(structured_buffer, stride=76)(mixed,mixed,mixed,mixed) r0.xyzw, v7.x, l(24), t4.xyzw
ld_structured_indexable(structured_buffer, stride=76)(mixed,mixed,mixed,mixed) r1.xyzw, v7.x, l(40), t4.xyzw
ld_structured_indexable(structured_buffer, stride=76)(mixed,mixed,mixed,mixed) r2.xyzw, v7.x, l(56), t4.xyzw
lt r3.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), v9.xyzw
if_nz r3.x
  utof r0.yzw, r0.yyzw
  mov r4.x, v4.w
  mov r4.y, v5.w
  mov r4.zw, r0.yyyz
  sample_indexable(texture2darray)(float,float,float,float) r5.xyz, r4.xyzx, t0.xyzw, s0
  sample_indexable(texture2darray)(float,float,float,float) r4.zw, r4.xywx, t1.zwxy, s1
  mov r0.yz, r4.xxyx
  sample_indexable(texture2darray)(float,float,float,float) r0.yz, r0.yzwy, t2.zxyw, s2
  mad r4.xy, r4.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.w, r4.xyxx, r4.xyxx
  min r0.w, r0.w, l(1.000000)
  add r0.w, -r0.w, l(1.000000)
  sqrt r4.z, r0.w
  mul r5.xyz, r5.xyzx, v9.xxxx
  mul r4.xyz, r4.xyzx, v9.xxxx
  mul r0.yz, r0.yyzy, v9.xxxx
else 
  mov r5.xyz, l(0,0,0,0)
  mov r4.xyz, l(0,0,0,0)
  mov r0.yz, l(0,0,0,0)
endif 
if_nz r3.y
  utof r1.xyz, r1.xyzx
  mov r6.x, v4.w
  mov r6.y, v5.w
  mov r6.zw, r1.xxxy
  sample_indexable(texture2darray)(float,float,float,float) r7.xyz, r6.xyzx, t0.xyzw, s0
  sample_indexable(texture2darray)(float,float,float,float) r3.xy, r6.xywx, t1.xyzw, s1
  mov r1.xy, r6.xyxx
  sample_indexable(texture2darray)(float,float,float,float) r1.xy, r1.xyzx, t2.xyzw, s2
  mad r6.xy, r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.w, r6.xyxx, r6.xyxx
  min r0.w, r0.w, l(1.000000)
  add r0.w, -r0.w, l(1.000000)
  sqrt r6.z, r0.w
  mad r5.xyz, r7.xyzx, v9.yyyy, r5.xyzx
  mad r4.xyz, r6.xyzx, v9.yyyy, r4.xyzx
  mad r0.yz, r1.xxyx, v9.yyyy, r0.yyzy
endif 
if_nz r3.z
  utof r1.x, r1.w
  mov r1.y, v4.w
  mov r1.z, v5.w
  sample_indexable(texture2darray)(float,float,float,float) r3.xyz, r1.yzxy, t0.xyzw, s0
  utof r1.xw, r2.yyyx
  sample_indexable(texture2darray)(float,float,float,float) r2.xy, r1.yzwy, t1.xyzw, s1
  sample_indexable(texture2darray)(float,float,float,float) r1.xy, r1.yzxy, t2.xyzw, s2
  mad r6.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.w, r6.xyxx, r6.xyxx
  min r0.w, r0.w, l(1.000000)
  add r0.w, -r0.w, l(1.000000)
  sqrt r6.z, r0.w
  mad r5.xyz, r3.xyzx, v9.zzzz, r5.xyzx
  mad r4.xyz, r6.xyzx, v9.zzzz, r4.xyzx
  mad r0.yz, r1.xxyx, v9.zzzz, r0.yyzy
endif 
if_nz r3.w
  ld_structured_indexable(structured_buffer, stride=76)(mixed,mixed,mixed,mixed) r0.w, v7.x, l(72), t4.xxxx
  utof r1.zw, r2.zzzw
  mov r1.x, v4.w
  mov r1.y, v5.w
  sample_indexable(texture2darray)(float,float,float,float) r2.xyz, r1.xyzx, t0.xyzw, s0
  sample_indexable(texture2darray)(float,float,float,float) r3.xy, r1.xywx, t1.xyzw, s1
  utof r1.z, r0.w
  sample_indexable(texture2darray)(float,float,float,float) r1.xy, r1.xyzx, t2.xyzw, s2
  mad r3.xy, r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.w, r3.xyxx, r3.xyxx
  min r0.w, r0.w, l(1.000000)
  add r0.w, -r0.w, l(1.000000)
  sqrt r3.z, r0.w
  mad r5.xyz, r2.xyzx, v9.wwww, r5.xyzx
  mad r4.xyz, r3.xyzx, v9.wwww, r4.xyzx
  mad r0.yz, r1.xxyx, v9.wwww, r0.yyzy
endif 
add r1.xyzw, v10.xyxy, cb0[0].zwzw
mul r1.xyzw, r1.xyzw, l(0.000250, 0.000250, 0.000350, 0.000350)
sample_indexable(texture2d)(float,float,float,float) r2.xyz, r1.xyxx, t13.xyzw, s13
mad r2.xyz, r2.xyzx, l(3.777778, 3.777778, 3.777778, 0.000000), l(-2.006000, -2.006000, -2.006000, 0.000000)
utof r3.z, r0.x
mov r3.xy, v8.xyxx
sample_indexable(texture2darray)(float,float,float,float) r3.xyz, r3.xyzx, t3.xyzw, s3
mad r2.xyz, r3.xyzx, r2.xyzx, -r5.xyzx
mad r2.xyz, v10.zzzz, r2.xyzx, r5.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.xw, r1.zwzz, t15.xzwy, s15
mad r1.xy, r0.xwxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.x, r1.xyxx, r1.xyxx
min r0.x, r0.x, l(1.000000)
add r0.x, -r0.x, l(1.000000)
sqrt r1.z, r0.x
mul r3.xyz, r4.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
mad r3.xyz, r4.yzxy, l(1.000000, 0.000000, 0.000000, 0.000000), -r3.xyzx
dp2 r0.x, r3.xzxx, r3.xzxx
rsq r0.x, r0.x
mul r3.xyz, r0.xxxx, r3.xyzx
mul r5.xyz, r4.yzxy, r3.xyzx
mad r3.xyz, r3.zxyz, r4.zxyz, -r5.xyzx
dp3 r0.x, r3.xyzx, r3.xyzx
rsq r0.x, r0.x
mul r3.xyz, r0.xxxx, r3.xyzx
mul r5.xyz, r3.yzxy, r4.zxyz
mad r5.xyz, r4.yzxy, r3.zxyz, -r5.xyzx
dp3 r0.x, r5.xyzx, r5.xyzx
rsq r0.x, r0.x
mul r5.xyz, r0.xxxx, r5.xyzx
dp3 r3.x, r3.xyzx, r1.xyzx
dp3 r3.y, r5.xyzx, r1.xyzx
dp3 r0.x, r4.xyzx, r4.xyzx
rsq r0.x, r0.x
mul r5.xyz, r0.xxxx, r4.xyzx
dp3 r3.z, r5.xyzx, r1.xyzx
add r1.xyz, -r4.xyzx, r3.xyzx
mad r1.xyz, v10.zzzz, r1.xyzx, r4.xyzx
dp3 r0.x, r1.xyzx, r1.xyzx
rsq r0.x, r0.x
mul r1.xyz, r0.xxxx, r1.xyzx
add r0.xw, -r0.yyyz, cb0[0].yyyx
mad r0.xy, v10.zzzz, r0.xwxx, r0.yzyy
mul r2.xyz, r2.xyzx, v6.xyzx
dp3 r0.z, v3.xyzx, v3.xyzx
rsq r0.z, r0.z
mul r3.xyz, r0.zzzz, v3.xyzx
movc r1.w, v11.x, r1.z, -r1.z
dp3 r0.z, v1.xyzx, v1.xyzx
rsq r0.z, r0.z
mul r4.xyz, r0.zzzz, v1.xyzx
dp3 r4.x, r4.xyzx, r1.xywx
dp3 r0.z, v2.xyzx, v2.xyzx
rsq r0.z, r0.z
mul r5.xyz, r0.zzzz, v2.xyzx
dp3 r4.y, r5.xyzx, r1.xywx
dp3 r0.z, r3.xyzx, r1.xywx
min r4.z, r0.z, l(0.000000)
dp3 r0.z, r4.xyzx, r4.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, r4.xyzx
mad r0.z, r1.z, l(-8.000000), l(8.000000)
sqrt r0.z, r0.z
div r0.zw, r1.xxxy, r0.zzzz
add o1.xy, r0.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
max r1.xyzw, cb2[4].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
max r3.xyzw, cb2[5].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r3.xyzw, r3.xyzw, v9.yyyy
mad r1.xyzw, r1.xyzw, v9.xxxx, r3.xyzw
max r3.xyzw, cb2[6].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r1.xyzw, r3.xyzw, v9.zzzz, r1.xyzw
max r3.xyzw, cb2[7].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r1.xyzw, r3.xyzw, v9.wwww, r1.xyzw
add r0.zw, -cb2[0].xxxy, cb2[2].xxxy
mad r0.zw, r0.zzzw, cb12[50].xxxx, cb2[0].xxxy
mul r0.zw, r0.zzzw, cb2[0].xxxy
ge r3.xy, cb2[2].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.zw, r3.xxxy, r0.zzzw, cb2[0].xxxy
eq r3.xyz, r1.zywz, l(-1.000000, -1.000000, -1.000000, 0.000000)
movc r3.xy, r3.xyxx, l(0,0,0,0), cb12[50].xxxx
add r1.yz, -r0.zzwz, r1.zzyz
mad r0.zw, r3.xxxy, r1.yyyz, r0.zzzw
mov_sat r1.x, r1.x
mul r1.y, r1.x, cb12[50].x
mad r1.x, -cb12[50].x, r1.x, l(1.000000)
mad r0.x, r0.x, r1.x, r1.y
mul o3.xy, r0.yxyy, r0.zwzz
lt r0.x, cb2[8].w, l(0.000000)
movc r0.x, r0.x, l(0), cb12[50].x
add r0.y, -cb2[8].z, cb2[8].w
ne r0.z, cb2[8].y, l(0.000000)
mad r0.y, r0.x, r0.y, cb2[8].z
mul r0.x, r0.x, cb2[8].w
movc r0.x, r0.z, r0.y, r0.x
ne r0.y, l(0.000000), cb12[50].x
ne r0.z, cb2[3].x, l(0.000000)
and r0.y, r0.z, r0.y
and o2.x, r0.y, cb2[3].x
mul o2.y, cb2[8].x, l(0.003922)
mul r0.x, r0.x, l(0.020000)
sqrt o2.z, r0.x
mov_sat o2.w, cb2[8].x
mad_sat r0.x, -cb12[50].x, r1.w, l(1.000000)
movc r0.x, r3.z, l(1.000000), r0.x
log r0.yzw, |r2.xxyz|
mul r0.yzw, r0.yyzw, cb5[1].xxxx
exp r0.yzw, r0.yyzw
mul r0.yzw, r0.yyzw, cb5[3].wwww
movc r0.yzw, cb5[0].xxxx, r0.yyzw, r2.xxyz
mul o0.xyz, r0.yzwy, r0.xxxx
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
ishl r0.x, v7.y, l(2)
iadd r1.xyzw, r0.xxxx, l(66, 63, 64, 54)
mov r2.xyz, v4.xyzx
mov r2.w, l(1.000000)
dp4 r0.y, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r1.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r1.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r0.yz, r1.xxyx, r0.yyyy
mov r2.xyz, v5.xyzx
mov r2.w, l(1.000000)
dp4 r0.w, cb12[r1.w + 0].xyzw, r2.xyzw
iadd r1.xy, r0.xxxx, l(51, 52, 0, 0)
dp4 r3.x, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r3.y, cb12[r1.y + 0].xyzw, r2.xyzw
div r0.xw, r3.xxxy, r0.wwww
add r0.xy, -r0.xwxx, r0.yzyy
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
mov o0.w, cb2[0].z
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(1.000000)
ret 
// Approximately 218 instruction slots used
