//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[9];                     // Offset:    0 Size:   144
//
// }
//
// cbuffer LandscapeLodGlobals
// {
//
//   float4 cb0;                        // Offset:    0 Size:    16
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Samp0                             sampler      NA          NA             s0      1 
// Samp1                             sampler      NA          NA             s1      1 
// Samp2                             sampler      NA          NA             s2      1 
// Samp3                             sampler      NA          NA             s3      1 
// Samp4                             sampler      NA          NA             s4      1 
// Samp5                             sampler      NA          NA             s5      1 
// Samp6                             sampler      NA          NA             s6      1 
// Samp7                             sampler      NA          NA             s7      1 
// Samp8                             sampler      NA          NA             s8      1 
// Samp9                             sampler      NA          NA             s9      1 
// Samp10                            sampler      NA          NA            s10      1 
// Samp11                            sampler      NA          NA            s11      1 
// SampLandscapeLodDiffuse           sampler      NA          NA            s13      1 
// SampLodMultiplier                 sampler      NA          NA            s14      1 
// SampLandscapeLodNormal            sampler      NA          NA            s15      1 
// TexDiffuse0                       texture  float4          2d             t0      1 
// TexDiffuse1                       texture  float4          2d             t1      1 
// TexDiffuse2                       texture  float4          2d             t2      1 
// TexDiffuse3                       texture  float4          2d             t3      1 
// TexNormal0                        texture  float4          2d             t4      1 
// TexNormal1                        texture  float4          2d             t5      1 
// TexNormal2                        texture  float4          2d             t6      1 
// TexNormal3                        texture  float4          2d             t7      1 
// TexSpecular0                      texture  float4          2d             t8      1 
// TexSpecular1                      texture  float4          2d             t9      1 
// TexSpecular2                      texture  float4          2d            t10      1 
// TexSpecular3                      texture  float4          2d            t11      1 
// TexLandscapeLodDiffuse            texture  float4          2d            t13      1 
// TexLodMultiplier                  texture  float4          2d            t14      1 
// TexLandscapeLodNormal             texture  float4          2d            t15      1 
// LandscapeLodGlobals               cbuffer      NA          NA            cb0      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    0   xyzw        6     NONE   float   xyz 
// TEXCOORD                 6   xy          7     NONE   float   xy  
// TEXCOORD                 7   xyzw        8     NONE   float   xyzw
// TEXCOORD                 8   xyz         9     NONE   float   xyz 
// EYEINDEX                 0   x          10     NONE    uint   x   
// SV_IsFrontFace           0   x          11    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[9], immediateIndexed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_sampler s13, mode_default
dcl_sampler s14, mode_default
dcl_sampler s15, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.xy
dcl_input_ps linear v8.xyzw
dcl_input_ps linear v9.xyz
dcl_input_ps constant v10.x
dcl_input_ps_sgv constant v11.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 6
lt r0.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), v8.xyzw
if_nz r0.x
  mov r1.x, v4.w
  mov r1.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r2.xyz, r1.xyxx, t0.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r1.zw, r1.xyxx, t4.zwxy, s4
  sample_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t8.xyzw, s8
  mad r3.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.x, r3.xyxx, r3.xyxx
  min r0.x, r0.x, l(1.000000)
  add r0.x, -r0.x, l(1.000000)
  sqrt r3.z, r0.x
  mul r2.xyz, r2.xyzx, v8.xxxx
  mul r3.xyz, r3.xyzx, v8.xxxx
  mul r1.xy, r1.xyxx, v8.xxxx
else 
  mov r2.xyz, l(0,0,0,0)
  mov r3.xyz, l(0,0,0,0)
  mov r1.xy, l(0,0,0,0)
endif 
if_nz r0.y
  mov r0.x, v4.w
  mov r0.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyxx, t1.xyzw, s1
  sample_indexable(texture2d)(float,float,float,float) r1.zw, r0.xyxx, t5.zwxy, s5
  sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t9.xyzw, s9
  mad r5.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r1.z, r5.xyxx, r5.xyxx
  min r1.z, r1.z, l(1.000000)
  add r1.z, -r1.z, l(1.000000)
  sqrt r5.z, r1.z
  mad r2.xyz, r4.xyzx, v8.yyyy, r2.xyzx
  mad r3.xyz, r5.xyzx, v8.yyyy, r3.xyzx
  mad r1.xy, r0.xyxx, v8.yyyy, r1.xyxx
endif 
if_nz r0.z
  mov r0.x, v4.w
  mov r0.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyxx, t2.xyzw, s2
  sample_indexable(texture2d)(float,float,float,float) r1.zw, r0.xyxx, t6.zwxy, s6
  sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t10.xyzw, s10
  mad r5.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.z, r5.xyxx, r5.xyxx
  min r0.z, r0.z, l(1.000000)
  add r0.z, -r0.z, l(1.000000)
  sqrt r5.z, r0.z
  mad r2.xyz, r4.xyzx, v8.zzzz, r2.xyzx
  mad r3.xyz, r5.xyzx, v8.zzzz, r3.xyzx
  mad r1.xy, r0.xyxx, v8.zzzz, r1.xyxx
endif 
if_nz r0.w
  mov r0.x, v4.w
  mov r0.y, v5.w
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyxx, t3.xyzw, s3
  sample_indexable(texture2d)(float,float,float,float) r0.zw, r0.xyxx, t7.zwxy, s7
  sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t11.xyzw, s11
  mad r5.xy, r0.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  dp2 r0.z, r5.xyxx, r5.xyxx
  min r0.z, r0.z, l(1.000000)
  add r0.z, -r0.z, l(1.000000)
  sqrt r5.z, r0.z
  mad r2.xyz, r4.xyzx, v8.wwww, r2.xyzx
  mad r3.xyz, r5.xyzx, v8.wwww, r3.xyzx
  mad r1.xy, r0.xyxx, v8.wwww, r1.xyxx
endif 
add r0.xyzw, v9.xyxy, cb0[0].zwzw
mul r0.xyzw, r0.xyzw, l(0.000250, 0.000250, 0.000350, 0.000350)
sample_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyxx, t13.xyzw, s13
mad r4.xyz, r4.xyzx, l(3.777778, 3.777778, 3.777778, 0.000000), l(-2.006000, -2.006000, -2.006000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r5.xyz, v7.xyxx, t14.xyzw, s14
mad r4.xyz, r5.xyzx, r4.xyzx, -r2.xyzx
mad r2.xyz, v9.zzzz, r4.xyzx, r2.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.zwzz, t15.xyzw, s15
mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.w, r0.xyxx, r0.xyxx
min r0.w, r0.w, l(1.000000)
add r0.w, -r0.w, l(1.000000)
sqrt r0.z, r0.w
mul r4.xyz, r3.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
mad r4.xyz, r3.yzxy, l(1.000000, 0.000000, 0.000000, 0.000000), -r4.xyzx
dp2 r0.w, r4.xzxx, r4.xzxx
rsq r0.w, r0.w
mul r4.xyz, r0.wwww, r4.xyzx
mul r5.xyz, r3.yzxy, r4.xyzx
mad r4.xyz, r4.zxyz, r3.zxyz, -r5.xyzx
dp3 r0.w, r4.xyzx, r4.xyzx
rsq r0.w, r0.w
mul r4.xyz, r0.wwww, r4.xyzx
mul r5.xyz, r3.zxyz, r4.yzxy
mad r5.xyz, r3.yzxy, r4.zxyz, -r5.xyzx
dp3 r0.w, r5.xyzx, r5.xyzx
rsq r0.w, r0.w
mul r5.xyz, r0.wwww, r5.xyzx
dp3 r4.x, r4.xyzx, r0.xyzx
dp3 r4.y, r5.xyzx, r0.xyzx
dp3 r0.w, r3.xyzx, r3.xyzx
rsq r0.w, r0.w
mul r5.xyz, r0.wwww, r3.xyzx
dp3 r4.z, r5.xyzx, r0.xyzx
add r0.xyz, -r3.xyzx, r4.xyzx
mad r0.xyz, v9.zzzz, r0.xyzx, r3.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx
add r1.zw, -r1.xxxy, cb0[0].yyyx
mad r1.xy, v9.zzzz, r1.zwzz, r1.xyxx
mul r2.xyz, r2.xyzx, v6.xyzx
dp3 r1.z, v3.xyzx, v3.xyzx
rsq r1.z, r1.z
mul r3.xyz, r1.zzzz, v3.xyzx
movc r0.w, v11.x, r0.z, -r0.z
dp3 r0.z, v1.xyzx, v1.xyzx
rsq r0.z, r0.z
mul r4.xyz, r0.zzzz, v1.xyzx
dp3 r4.x, r4.xyzx, r0.xywx
dp3 r0.z, v2.xyzx, v2.xyzx
rsq r0.z, r0.z
mul r5.xyz, r0.zzzz, v2.xyzx
dp3 r4.y, r5.xyzx, r0.xywx
dp3 r0.x, r3.xyzx, r0.xywx
min r4.z, r0.x, l(0.000000)
dp3 r0.x, r4.xyzx, r4.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, r4.xyzx
mad r0.z, r0.z, l(-8.000000), l(8.000000)
sqrt r0.z, r0.z
div r0.xy, r0.xyxx, r0.zzzz
add o1.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
max r0.xyzw, cb2[4].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
max r3.xyzw, cb2[5].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r3.xyzw, r3.xyzw, v8.yyyy
mad r0.xyzw, r0.xyzw, v8.xxxx, r3.xyzw
max r3.xyzw, cb2[6].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r0.xyzw, r3.xyzw, v8.zzzz, r0.xyzw
max r3.xyzw, cb2[7].zxyw, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r0.xyzw, r3.xyzw, v8.wwww, r0.xyzw
add r1.zw, -cb2[0].xxxy, cb2[2].xxxy
mad r1.zw, r1.zzzw, cb12[50].xxxx, cb2[0].xxxy
mul r1.zw, r1.zzzw, cb2[0].xxxy
ge r3.xy, cb2[2].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r1.zw, r3.xxxy, r1.zzzw, cb2[0].xxxy
eq r3.xyz, r0.zywz, l(-1.000000, -1.000000, -1.000000, 0.000000)
movc r3.xy, r3.xyxx, l(0,0,0,0), cb12[50].xxxx
add r0.yz, r0.zzyz, -r1.zzwz
mad r0.yz, r3.xxyx, r0.yyzy, r1.zzwz
mov_sat r0.x, r0.x
mul r1.z, r0.x, cb12[50].x
mad r0.x, -cb12[50].x, r0.x, l(1.000000)
mad r0.x, r1.x, r0.x, r1.z
mul o3.x, r1.y, r0.y
mul o3.y, r0.x, r0.z
lt r0.x, cb2[8].w, l(0.000000)
movc r0.x, r0.x, l(0), cb12[50].x
add r0.y, -cb2[8].z, cb2[8].w
ne r0.z, cb2[8].y, l(0.000000)
mad r0.y, r0.x, r0.y, cb2[8].z
mul r0.x, r0.x, cb2[8].w
movc r0.x, r0.z, r0.y, r0.x
ne r0.y, l(0.000000), cb12[50].x
ne r0.z, cb2[3].x, l(0.000000)
and r0.y, r0.z, r0.y
and o2.x, r0.y, cb2[3].x
mul o2.y, cb2[8].x, l(0.003922)
mul r0.x, r0.x, l(0.020000)
sqrt o2.z, r0.x
mov_sat o2.w, cb2[8].x
mad_sat r0.x, -cb12[50].x, r0.w, l(1.000000)
movc r0.x, r3.z, l(1.000000), r0.x
log r0.yzw, |r2.xxyz|
mul r0.yzw, r0.yyzw, cb5[1].xxxx
exp r0.yzw, r0.yyzw
mul r0.yzw, r0.yyzw, cb5[3].wwww
movc r0.yzw, cb5[0].xxxx, r0.yyzw, r2.xxyz
mul o0.xyz, r0.yzwy, r0.xxxx
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
ishl r0.x, v10.x, l(2)
iadd r1.xyzw, r0.xxxx, l(66, 63, 64, 54)
mov r2.xyz, v4.xyzx
mov r2.w, l(1.000000)
dp4 r0.y, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r1.x, cb12[r1.y + 0].xyzw, r2.xyzw
dp4 r1.y, cb12[r1.z + 0].xyzw, r2.xyzw
div r0.yz, r1.xxyx, r0.yyyy
mov r2.xyz, v5.xyzx
mov r2.w, l(1.000000)
dp4 r0.w, cb12[r1.w + 0].xyzw, r2.xyzw
iadd r1.xy, r0.xxxx, l(51, 52, 0, 0)
dp4 r3.x, cb12[r1.x + 0].xyzw, r2.xyzw
dp4 r3.y, cb12[r1.y + 0].xyzw, r2.xyzw
div r0.xw, r3.xxxy, r0.wwww
add r0.xy, -r0.xwxx, r0.yzyy
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
mov o0.w, cb2[0].z
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(1.000000)
ret 
// Approximately 203 instruction slots used
