//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[6];                     // Offset:    0 Size:    96
//
// }
//
// cbuffer LandscapeLodGlobals
// {
//
//   float4 cb0;                        // Offset:    0 Size:    16
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampLandscapeLodDiffuse           sampler      NA          NA            s13      1 
// SampLandscapeLodNormal            sampler      NA          NA            s15      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexSpecular                       texture  float4          2d             t2      1 
// TexLandscapeLodDiffuse            texture  float4          2d            t13      1 
// TexLandscapeLodNormal             texture  float4          2d            t15      1 
// LandscapeLodGlobals               cbuffer      NA          NA            cb0      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// COLOR                    0   xyzw        6     NONE   float   xyzw
// TEXCOORD                 9   xy          7     NONE   float   xy  
// EYEINDEX                 0   x           8     NONE    uint   x   
// SV_IsFrontFace           0   x           9    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[6], immediateIndexed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s13, mode_default
dcl_sampler s15, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyzw
dcl_input_ps linear v7.xy
dcl_input_ps constant v8.x
dcl_input_ps_sgv constant v9.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 6
mov r0.x, v4.w
mov r0.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyxx, t0.xyzw, s0
mad r0.z, r1.w, v6.w, -cb2[1].w
lt r0.z, r0.z, l(0.000000)
discard_nz r0.z
add r2.xyzw, v7.xyxy, cb0[0].zwzw
mul r2.xyzw, r2.xyzw, l(0.000250, 0.000250, 0.000350, 0.000350)
sample_indexable(texture2d)(float,float,float,float) r3.xyz, r2.xyxx, t13.xyzw, s13
sample_indexable(texture2d)(float,float,float,float) r0.zw, r2.zwzz, t15.zwxy, s15
mad r2.xy, r0.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mad r3.xyz, r3.xyzx, l(3.777778, 3.777778, 3.777778, 0.000000), l(-2.006000, -2.006000, -2.006000, 0.000000)
mul r1.xyz, r1.xyzx, r3.xyzx
mul r1.xyz, r1.xyzx, v6.xyzx
log r3.xyz, |r1.xyzx|
mul r3.xyz, r3.xyzx, cb5[1].xxxx
exp r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, cb5[3].wwww
movc r1.xyz, cb5[0].xxxx, r3.xyzx, r1.xyzx
eq r0.z, cb2[4].w, l(-1.000000)
mad r3.xy, -cb2[4].wzww, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
movc r0.z, r0.z, l(1.000000), r3.x
mul o0.xyz, r1.xyzx, r0.zzzz
mov o0.w, cb2[0].z
dp3 r0.z, v3.xyzx, v3.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, v3.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.zw, r0.xyxx, t1.zwxy, s1
sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t2.xyzw, s2
mad r4.xy, r0.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.z, r4.xyxx, r4.xyxx
min r0.z, r0.z, l(1.000000)
add r0.z, -r0.z, l(1.000000)
sqrt r4.z, r0.z
mul r3.xzw, r4.xxyz, l(0.000000, 0.000000, 0.000000, 1.000000)
mad r3.xzw, r4.yyzx, l(1.000000, 0.000000, 0.000000, 0.000000), -r3.xxzw
dp2 r0.z, r3.xwxx, r3.xwxx
rsq r0.z, r0.z
mul r3.xzw, r0.zzzz, r3.xxzw
mul r5.xyz, r4.yzxy, r3.xzwx
mad r5.xyz, r3.wxzw, r4.zxyz, -r5.xyzx
dp3 r0.z, r5.xyzx, r5.xyzx
rsq r0.z, r0.z
mul r5.xyz, r0.zzzz, r5.xyzx
dp2 r0.z, r2.xyxx, r2.xyxx
min r0.z, r0.z, l(1.000000)
add r0.z, -r0.z, l(1.000000)
sqrt r2.z, r0.z
dp3 r5.x, r5.xyzx, r2.xyzx
dp3 r0.z, r4.xyzx, r4.xyzx
rsq r0.z, r0.z
mul r4.xyz, r0.zzzz, r4.xyzx
dp3 r0.z, r4.xyzx, r2.xyzx
dp2 r5.y, r3.wxww, r2.yzyy
movc r5.z, v9.x, r0.z, -r0.z
dp3 r0.z, r1.xyzx, r5.xyzx
min r1.z, r0.z, l(0.000000)
dp3 r0.z, v1.xyzx, v1.xyzx
rsq r0.z, r0.z
mul r2.xyz, r0.zzzz, v1.xyzx
dp3 r1.x, r2.xyzx, r5.xyzx
dp3 r0.z, v2.xyzx, v2.xyzx
rsq r0.z, r0.z
mul r2.xyz, r0.zzzz, v2.xyzx
dp3 r1.y, r2.xyzx, r5.xyzx
dp3 r0.z, r1.xyzx, r1.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, r1.xyzx
mad r0.z, r1.z, l(-8.000000), l(8.000000)
sqrt r0.z, r0.z
div r0.zw, r1.xxxy, r0.zzzz
add o1.xy, r0.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
add r0.z, -cb2[5].z, cb2[5].w
lt r0.w, cb2[5].w, l(0.000000)
movc r0.w, r0.w, l(0), cb12[50].x
mad r0.z, r0.w, r0.z, cb2[5].z
mul r0.w, r0.w, cb2[5].w
ne r1.x, cb2[5].y, l(0.000000)
movc r0.z, r1.x, r0.z, r0.w
mul r0.z, r0.z, l(0.020000)
sqrt o2.z, r0.z
ne r0.z, l(0.000000), cb12[50].x
ne r1.xy, cb2[4].yxyy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.z, r0.z, r1.x
or r0.z, r1.y, r0.z
and o2.x, r0.z, l(0x3f800000)
mul o2.y, cb2[5].x, l(0.003922)
mov_sat o2.w, cb2[5].x
mul r0.z, cb2[4].z, cb12[50].x
mad r0.x, r0.x, r3.y, r0.z
add r0.zw, -cb2[0].xxxy, cb2[2].xxxy
mad r0.zw, r0.zzzw, cb12[50].xxxx, cb2[0].xxxy
mul r0.zw, r0.zzzw, cb2[0].xxxy
ge r1.xy, cb2[2].xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.zw, r1.xxxy, r0.zzzw, cb2[0].xxxy
mul o3.xy, r0.yxyy, r0.zwzz
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(1.000000)
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
mov r0.xyz, v4.xyzx
mov r0.w, l(1.000000)
ishl r1.x, v8.x, l(2)
iadd r2.xyzw, r1.xxxx, l(66, 63, 64, 54)
iadd r1.xy, r1.xxxx, l(51, 52, 0, 0)
dp4 r1.z, cb12[r2.x + 0].xyzw, r0.xyzw
dp4 r2.x, cb12[r2.y + 0].xyzw, r0.xyzw
dp4 r2.y, cb12[r2.z + 0].xyzw, r0.xyzw
div r0.xy, r2.xyxx, r1.zzzz
mov r3.xyz, v5.xyzx
mov r3.w, l(1.000000)
dp4 r0.z, cb12[r2.w + 0].xyzw, r3.xyzw
dp4 r2.x, cb12[r1.x + 0].xyzw, r3.xyzw
dp4 r2.y, cb12[r1.y + 0].xyzw, r3.xyzw
div r0.zw, r2.xxxy, r0.zzzz
add r0.xy, -r0.zwzz, r0.xyxx
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
ret 
// Approximately 124 instruction slots used
