//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Note: shader requires additional functionality:
//       Early depth-stencil
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[7];                     // Offset:    0 Size:   112
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[51];                   // Offset:    0 Size:   816
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// SampScreen                        sampler      NA          NA             s4      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexSpecular                       texture  float4          2d             t2      1 
// TexScreen                         texture  float4          2d             t4      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float      w
// TEXCOORD                 4   xyzw        5     NONE   float      w
// COLOR                    0   xyzw        6     NONE   float   xyzw
// EYEINDEX                 0   x           7     NONE    uint       
// SV_IsFrontFace           0   x           8    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyzw        4   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | forceEarlyDepthStencil
dcl_constantbuffer CB2[7], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[51], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.w
dcl_input_ps linear v5.w
dcl_input_ps linear v6.xyzw
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_temps 5
eq r0.x, cb2[2].y, l(1.000000)
mov r1.x, v4.w
mov r1.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyxx, t0.xyzw, s0
mul r2.xyzw, r2.xyzw, v6.xyzw
movc r0.x, r0.x, r2.w, l(1.000000)
mad r0.y, r0.x, cb2[2].x, l(-0.015686)
mul r0.x, r0.x, cb2[2].x
lt r0.y, r0.y, l(0.000000)
discard_nz r0.y
sample_indexable(texture2d)(float,float,float,float) r0.yzw, r1.xyxx, t4.wxyz, s4
log r3.xyz, |r0.yzwy|
mul r3.xyz, r3.xyzx, cb5[1].xxxx
exp r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, cb5[3].wwww
movc r0.yzw, cb5[0].xxxx, r3.xxyz, r0.yyzw
log r3.xyz, |r2.xyzx|
mul r3.xyz, r3.xyzx, cb5[1].xxxx
exp r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, cb5[3].wwww
movc r2.xyz, cb5[0].xxxx, r3.xyzx, r2.xyzx
add r0.yzw, r0.yyzw, r2.xxyz
eq r1.z, cb2[5].w, l(-1.000000)
mad r2.xy, -cb2[5].wzww, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
movc r1.z, r1.z, l(1.000000), r2.x
mul o0.xyz, r0.yzwy, r1.zzzz
mov o0.w, r0.x
dp3 r0.y, v3.xyzx, v3.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, v3.xxyz
sample_indexable(texture2d)(float,float,float,float) r1.zw, r1.xyxx, t1.zwxy, s1
sample_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t2.xyzw, s2
mad r3.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.z, r3.xyxx, r3.xyxx
min r1.z, r1.z, l(1.000000)
add r1.z, -r1.z, l(1.000000)
sqrt r1.z, r1.z
movc r3.z, v8.x, r1.z, -r1.z
dp3 r0.y, r0.yzwy, r3.xyzx
min r4.z, r0.y, l(0.000000)
dp3 r0.y, v1.xyzx, v1.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, v1.xxyz
dp3 r4.x, r0.yzwy, r3.xyzx
dp3 r0.y, v2.xyzx, v2.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, v2.xxyz
dp3 r4.y, r0.yzwy, r3.xyzx
dp3 r0.y, r4.xyzx, r4.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, r4.xxyz
mad r1.z, r0.w, l(-8.000000), l(8.000000)
sqrt r1.z, r1.z
div r0.yz, r0.yyzy, r1.zzzz
mov o1.z, -r0.w
add o1.xy, r0.yzyy, l(0.500000, 0.500000, 0.000000, 0.000000)
mov o1.w, r0.x
add r0.y, -cb2[6].z, cb2[6].w
lt r0.z, cb2[6].w, l(0.000000)
movc r0.z, r0.z, l(0), cb12[50].x
mad r0.y, r0.z, r0.y, cb2[6].z
mul r0.z, r0.z, cb2[6].w
ne r0.w, cb2[6].y, l(0.000000)
movc r0.y, r0.w, r0.y, r0.z
mul r0.y, r0.y, l(0.020000)
sqrt o2.z, r0.y
ne r0.y, cb12[50].x, l(0.000000)
ne r0.zw, cb2[5].yyyx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.y, r0.z, r0.y
or r0.y, r0.w, r0.y
and o2.x, r0.y, l(0x3f800000)
mul o2.y, cb2[6].x, l(0.003922)
mov_sat o2.w, cb2[6].x
mul r0.y, cb2[5].z, cb12[50].x
mad r0.y, r1.x, r2.y, r0.y
add r0.zw, -cb2[0].xxxy, cb2[3].xxxy
mad r0.zw, r0.zzzw, cb12[50].xxxx, cb2[0].xxxy
mul r0.zw, r0.zzzw, cb2[0].xxxy
ge r1.xz, cb2[3].xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.zw, r1.xxxz, r0.zzzw, cb2[0].xxxy
mul o3.y, r0.y, r0.w
mul o3.x, r1.y, r0.z
mov o3.w, r0.x
mov o4.w, r0.x
mul o3.z, cb2[0].w, l(0.010000)
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
ret 
// Approximately 94 instruction slots used
