//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Note: shader requires additional functionality:
//       Early depth-stencil
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[8];                     // Offset:    0 Size:   128
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[51];                   // Offset:    0 Size:   816
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SampDiffuse                       sampler      NA          NA             s0      1 
// SampNormal                        sampler      NA          NA             s1      1 
// SampSpecular                      sampler      NA          NA             s2      1 
// TexDiffuse                        texture  float4          2d             t0      1 
// TexNormal                         texture  float4          2d             t1      1 
// TexSpecular                       texture  float4          2d             t2      1 
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float      w
// TEXCOORD                 4   xyzw        5     NONE   float      w
// COLOR                    0   xyzw        6     NONE   float   xyzw
// EYEINDEX                 0   x           7     NONE    uint       
// SV_IsFrontFace           0   x           8    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyzw        4   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | forceEarlyDepthStencil
dcl_constantbuffer CB2[8], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[51], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.w
dcl_input_ps linear v5.w
dcl_input_ps linear v6.xyzw
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_temps 9
eq r0.x, cb2[2].y, l(1.000000)
mov r1.x, v4.w
mov r1.y, v5.w
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyxx, t0.xyzw, s0
mul r3.xyzw, r2.xyzw, v6.xyzw
movc r0.x, r0.x, r3.w, l(1.000000)
mad r0.y, r0.x, cb2[2].x, l(-0.015686)
mul r0.x, r0.x, cb2[2].x
lt r0.y, r0.y, l(0.000000)
discard_nz r0.y
log r0.yzw, |r3.xxyz|
mul r0.yzw, r0.yyzw, l(0.000000, 0.454545, 0.454545, 0.454545)
exp r0.yzw, r0.yyzw
sqrt r4.xyz, r0.yzwy
add r5.xyz, r0.yzwy, r0.yzwy
mul r0.yzw, r0.yyzw, r0.yyzw
log r6.xyz, |cb2[3].xyzx|
mul r6.xyz, r6.xyzx, l(0.454545, 0.454545, 0.454545, 0.000000)
exp r6.xyz, r6.xyzx
add r7.xyz, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r7.xyz, r5.xyzx, r7.xyzx
mad r8.xyz, r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
mad r4.xyz, r4.xyzx, r8.xyzx, r7.xyzx
mad r7.xyz, -r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
mul r0.yzw, r0.yyzw, r7.xxyz
mad r0.yzw, r5.xxyz, r6.xxyz, r0.yyzw
lt r5.xyz, r6.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
movc r0.yzw, r5.xxyz, r0.yyzw, r4.xxyz
log r0.yzw, |r0.yyzw|
mul r0.yzw, r0.yyzw, l(0.000000, 2.200000, 2.200000, 2.200000)
exp r0.yzw, r0.yyzw
mad r0.yzw, -r2.xxyz, v6.xxyz, r0.yyzw
mad r0.yzw, cb2[3].wwww, r0.yyzw, r3.xxyz
log r2.xyz, |r0.yzwy|
mul r2.xyz, r2.xyzx, cb5[1].xxxx
exp r2.xyz, r2.xyzx
mul r2.xyz, r2.xyzx, cb5[3].wwww
movc r0.yzw, cb5[0].xxxx, r2.xxyz, r0.yyzw
eq r1.z, cb2[6].w, l(-1.000000)
mad r2.xy, -cb2[6].wzww, cb12[50].xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
movc r1.z, r1.z, l(1.000000), r2.x
mul o0.xyz, r0.yzwy, r1.zzzz
mov o0.w, r0.x
dp3 r0.y, v3.xyzx, v3.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, v3.xxyz
sample_indexable(texture2d)(float,float,float,float) r1.zw, r1.xyxx, t1.zwxy, s1
sample_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t2.xyzw, s2
mad r3.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.z, r3.xyxx, r3.xyxx
min r1.z, r1.z, l(1.000000)
add r1.z, -r1.z, l(1.000000)
sqrt r1.z, r1.z
movc r3.z, v8.x, r1.z, -r1.z
dp3 r0.y, r0.yzwy, r3.xyzx
min r4.z, r0.y, l(0.000000)
dp3 r0.y, v1.xyzx, v1.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, v1.xxyz
dp3 r4.x, r0.yzwy, r3.xyzx
dp3 r0.y, v2.xyzx, v2.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, v2.xxyz
dp3 r4.y, r0.yzwy, r3.xyzx
dp3 r0.y, r4.xyzx, r4.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, r4.xxyz
mad r1.z, r0.w, l(-8.000000), l(8.000000)
sqrt r1.z, r1.z
div r0.yz, r0.yyzy, r1.zzzz
mov o1.z, -r0.w
add o1.xy, r0.yzyy, l(0.500000, 0.500000, 0.000000, 0.000000)
mov o1.w, r0.x
mov o4.w, r0.x
add r0.x, -cb2[7].z, cb2[7].w
lt r0.y, cb2[7].w, l(0.000000)
movc r0.y, r0.y, l(0), cb12[50].x
mad r0.x, r0.y, r0.x, cb2[7].z
mul r0.y, r0.y, cb2[7].w
ne r0.z, cb2[7].y, l(0.000000)
movc r0.x, r0.z, r0.x, r0.y
mul r0.x, r0.x, l(0.020000)
sqrt o2.z, r0.x
ne r0.x, cb12[50].x, l(0.000000)
ne r0.yz, cb2[6].yyxy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x
and o2.x, r0.x, l(0x3f800000)
mul o2.y, cb2[7].x, l(0.003922)
mov_sat o2.w, cb2[7].x
mul r0.x, cb2[6].z, cb12[50].x
mad r0.x, r1.x, r2.y, r0.x
add r0.yz, -cb2[0].xxyx, cb2[4].xxyx
mad r0.yz, r0.yyzy, cb12[50].xxxx, cb2[0].xxyx
mul r0.yz, r0.yyzy, cb2[0].xxyx
ge r1.xz, cb2[4].xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.yz, r1.xxzx, r0.yyzy, cb2[0].xxyx
mul o3.y, r0.x, r0.z
mul o3.x, r1.y, r0.y
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(0.019608)
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
ret 
// Approximately 110 instruction slots used
