//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Note: shader requires additional functionality:
//       Early depth-stencil
//
//
// Buffer Definitions: 
//
// cbuffer PerMaterial
// {
//
//   float4 cb2[6];                     // Offset:    0 Size:    96
//
// }
//
// cbuffer LinearLightingFrame
// {
//
//   uint enableLinearLighting;         // Offset:    0 Size:     4
//   uint isDirLightLinear;             // Offset:    4 Size:     4 [unused]
//   float dirLightMult;                // Offset:    8 Size:     4 [unused]
//   float lightGamma;                  // Offset:   12 Size:     4 [unused]
//   float colorGamma;                  // Offset:   16 Size:     4 [unused]
//   float emitColorGamma;              // Offset:   20 Size:     4
//   float glowmapGamma;                // Offset:   24 Size:     4 [unused]
//   float ambientGamma;                // Offset:   28 Size:     4 [unused]
//   float fogGamma;                    // Offset:   32 Size:     4 [unused]
//   float fogAlphaGamma;               // Offset:   36 Size:     4 [unused]
//   float effectGamma;                 // Offset:   40 Size:     4 [unused]
//   float effectAlphaGamma;            // Offset:   44 Size:     4 [unused]
//   float skyGamma;                    // Offset:   48 Size:     4 [unused]
//   float waterGamma;                  // Offset:   52 Size:     4 [unused]
//   float vlGamma;                     // Offset:   56 Size:     4 [unused]
//   float vanillaDiffuseColorMult;     // Offset:   60 Size:     4
//   float directionalLightMult;        // Offset:   64 Size:     4 [unused]
//   float pointLightMult;              // Offset:   68 Size:     4 [unused]
//   float ambientMult;                 // Offset:   72 Size:     4 [unused]
//   float emitColorMult;               // Offset:   76 Size:     4
//   float glowmapMult;                 // Offset:   80 Size:     4 [unused]
//   float effectLightingMult;          // Offset:   84 Size:     4 [unused]
//   float membraneEffectMult;          // Offset:   88 Size:     4 [unused]
//   float bloodEffectMult;             // Offset:   92 Size:     4 [unused]
//   float projectedEffectMult;         // Offset:   96 Size:     4 [unused]
//   float deferredEffectMult;          // Offset:  100 Size:     4 [unused]
//   float otherEffectMult;             // Offset:  104 Size:     4 [unused]
//   uint linearLightingPad0;           // Offset:  108 Size:     4 [unused]
//
// }
//
// cbuffer LinearLightingGeometry
// {
//
//   float emissiveMult;                // Offset:    0 Size:     4
//   float3 linearLightingGeometryPad0; // Offset:    4 Size:    12 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 cb12[71];                   // Offset:    0 Size:  1136
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerMaterial                       cbuffer      NA          NA            cb2      1 
// LinearLightingFrame               cbuffer      NA          NA            cb5      1 
// LinearLightingGeometry            cbuffer      NA          NA            cb8      1 
// PerGeometry                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float       
// TEXCOORD                 1   xyz         2     NONE   float       
// TEXCOORD                 2   xyz         3     NONE   float       
// TEXCOORD                 3   xyzw        4     NONE   float   xyz 
// TEXCOORD                 4   xyzw        5     NONE   float   xyz 
// EYEINDEX                 0   x           6     NONE    uint   x   
// SV_IsFrontFace           0   x           7    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xy          1   TARGET   float   xy  
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyz         4   TARGET   float   xyz 
// SV_Target                5   xy          5   TARGET   float   xy  
//
ps_5_0
dcl_globalFlags refactoringAllowed | forceEarlyDepthStencil
dcl_constantbuffer CB2[6], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_constantbuffer CB12[71], dynamicIndexed
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps constant v6.x
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyz
dcl_output o5.xy
dcl_temps 4
eq r0.x, cb2[4].w, l(-1.000000)
mad r0.y, -cb2[4].w, cb12[50].x, l(1.000000)
movc r0.x, r0.x, l(1.000000), r0.y
movc r0.y, cb5[0].x, cb5[3].w, l(1.000000)
mul o0.xyz, r0.yyyy, r0.xxxx
mov o0.w, cb2[0].z
mov o1.xy, l(0x7fc00000,0x7fc00000,0,0)
add r0.x, -cb2[5].z, cb2[5].w
lt r0.y, cb2[5].w, l(0.000000)
movc r0.y, r0.y, l(0), cb12[50].x
mad r0.x, r0.y, r0.x, cb2[5].z
mul r0.y, r0.y, cb2[5].w
ne r0.z, cb2[5].y, l(0.000000)
movc r0.x, r0.z, r0.x, r0.y
mul r0.x, r0.x, l(0.020000)
sqrt o2.z, r0.x
ne r0.x, l(0.000000), cb12[50].x
ne r0.yz, cb2[4].yyxy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x
and o2.x, r0.x, l(0x3f800000)
mul o2.y, cb2[5].x, l(0.003922)
mov_sat o2.w, cb2[5].x
add r0.xy, -cb2[0].xyxx, cb2[2].xyxx
mad r0.xy, r0.xyxx, cb12[50].xxxx, cb2[0].xyxx
mul r0.xy, r0.xyxx, cb2[0].xyxx
ge r0.zw, cb2[2].xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.xy, r0.zwzz, r0.xyxx, cb2[0].xyxx
mul r0.y, r0.y, cb12[50].x
mov o3.x, r0.x
mul o3.y, r0.y, cb2[4].z
mul o3.z, cb2[0].w, l(0.010000)
mov o3.w, l(1.000000)
max r0.x, cb8[0].x, l(0.000010)
div r0.xyz, cb2[1].xyzx, r0.xxxx
log r0.xyz, |r0.xyzx|
mul r0.xyz, r0.xyzx, cb5[1].yyyy
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, cb8[0].xxxx
mul r0.xyz, r0.xyzx, cb5[4].wwww
movc o4.xyz, cb5[0].xxxx, r0.xyzx, cb2[1].xyzx
mov r0.xyz, v4.xyzx
mov r0.w, l(1.000000)
ishl r1.x, v6.x, l(2)
iadd r2.xyzw, r1.xxxx, l(66, 63, 64, 54)
iadd r1.xy, r1.xxxx, l(51, 52, 0, 0)
dp4 r1.z, cb12[r2.x + 0].xyzw, r0.xyzw
dp4 r2.x, cb12[r2.y + 0].xyzw, r0.xyzw
dp4 r2.y, cb12[r2.z + 0].xyzw, r0.xyzw
div r0.xy, r2.xyxx, r1.zzzz
mov r3.xyz, v5.xyzx
mov r3.w, l(1.000000)
dp4 r0.z, cb12[r2.w + 0].xyzw, r3.xyzw
dp4 r2.x, cb12[r1.x + 0].xyzw, r3.xyzw
dp4 r2.y, cb12[r1.y + 0].xyzw, r3.xyzw
div r0.zw, r2.xxxy, r0.zzzz
add r0.xy, -r0.zwzz, r0.xyxx
mul o5.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
ret 
// Approximately 59 instruction slots used
