#pragma once

#include <string_view>

namespace csah::settings_path
{
    // Initial settings captured from the deployed mod. Existing user INIs
    // remain authoritative; this is only used when no current or legacy INI exists.
    inline constexpr std::string_view kFirstRunIni =
        "; Community Shaders at Home (CSAH) VR runtime configuration.\r\n"
        "; 0=Off and 1=On. DevMenu and this file control the same settings.\r\n"
        "; Most settings hot-reload. Restart only where a section says it is required.\r\n"
        "\r\n"
        "; =============================================================================\r\n"
        "; INDEPENDENT RUNTIME MASTER SWITCHES\r\n"
        "; =============================================================================\r\n"
        "[CommunityShaders]\r\n"
        "; Controls only the Community Shaders visual-effect suite. Individual visual\r\n"
        "; feature selections are preserved while this is off. DLAA/DLSS, Vanilla\r\n"
        "; Fixes, and Native Shadows use their own independent master switches below.\r\n"
        "bEnabled=1\r\n"
        "\r\n"
        "; =============================================================================\r\n"
        "; CORE LIGHTING AND ENVIRONMENT\r\n"
        "; =============================================================================\r\n"
        "[LinearLighting]\r\n"
        "; Converts supported lighting and material colour operations to linear space.\r\n"
        "bEnabled=1\r\n"
        "bPreserveNativeDarkness=1\r\n"
        "\r\n"
        "; Input response curves.\r\n"
        "fLightGamma=1.79999995\r\n"
        "fColorGamma=1.79999995\r\n"
        "fEmitColorGamma=1.79999995\r\n"
        "fGlowmapGamma=1.79999995\r\n"
        "fAmbientGamma=1.79999995\r\n"
        "fFogGamma=1.97000003\r\n"
        "fFogAlphaGamma=1.79999995\r\n"
        "fEffectGamma=1.39999998\r\n"
        "fEffectAlphaGamma=1.54999995\r\n"
        "fSkyGamma=1.79999995\r\n"
        "fWaterGamma=1.79999995\r\n"
        "fVolumetricLightingGamma=1.79999995\r\n"
        "\r\n"
        "; Light-energy multipliers.\r\n"
        "fVanillaDiffuseColorMultiplier=1\r\n"
        "fDirectionalLightMultiplier=1\r\n"
        "fPointLightMultiplier=1\r\n"
        "fAmbientMultiplier=1\r\n"
        "fEmitColorMultiplier=1\r\n"
        "fGlowmapMultiplier=0.660000026\r\n"
        "fEffectLightingMultiplier=0.319999993\r\n"
        "\r\n"
        "; Effect-family multipliers.\r\n"
        "fMembraneEffectMultiplier=1\r\n"
        "fBloodEffectMultiplier=1\r\n"
        "fProjectedEffectMultiplier=1\r\n"
        "fDeferredEffectMultiplier=1\r\n"
        "fOtherEffectMultiplier=1\r\n"
        "\r\n"
        "[Skylighting]\r\n"
        "; Probe quality: 0=Low, 1=Medium, 2=High. Quality changes require a restart.\r\n"
        "bEnabled=1\r\n"
        "iQuality=0\r\n"
        "; Minimum retained light in fully occluded areas and the sampled sky cone.\r\n"
        "fMinDiffuseVisibility=0.10\r\n"
        "fMinSpecularVisibility=0.10\r\n"
        "fMaxZenithDegrees=90.0\r\n"
        "\r\n"
        "[SkySync]\r\n"
        "; Aligns native directional lighting with the visible Sun by day and Moon by night.\r\n"
        "bEnabled=1\r\n"
        "\r\n"
        "[ImageBasedLighting]\r\n"
        "; Shared environment gate, diffuse bounce gate, and diffuse intensity.\r\n"
        "bEnabled=1\r\n"
        "bDiffuseEnabled=1\r\n"
        "fDiffuseLevel=1\r\n"
        "\r\n"
        "[DynamicCubemaps]\r\n"
        "; Position-aware specular environment reflections. Requires IBL above.\r\n"
        "bEnabled=1\r\n"
        "\r\n"
        "; =============================================================================\r\n"
        "; SCENE, SHADOW, AND MATERIAL EFFECTS\r\n"
        "; =============================================================================\r\n"
        "[PBR]\r\n"
        "; Requires Linear Lighting. Shared physical material response for direct light,\r\n"
        "; IBL, dynamic cubemaps, wetness, and native reflection fallback. All controls\r\n"
        "; hot-reload.\r\n"
        "bEnabled=1\r\n"
        "bLegacyMaterials=1\r\n"
        "bDirectGGX=1\r\n"
        "bGrassGGX=0\r\n"
        "bEnvironmentFresnel=1\r\n"
        "bEnergyConservation=1\r\n"
        "bMultiscatterCompensation=1\r\n"
        "bSpecularOcclusion=1\r\n"
        "fRoughnessMultiplier=1.0\r\n"
        "fSpecularRoughnessBlend=1.0\r\n"
        "fBaseF0Multiplier=0.32\r\n"
        "fMinimumF0=0.02\r\n"
        "fCubemapToF0Multiplier=1.0\r\n"
        "fComplexMaterialF0Multiplier=1.0\r\n"
        "fDirectLightingScale=1.0\r\n"
        "\r\n"
        "[ComplexMaterials]\r\n"
        "; These effects require assets authored for the complex-material contract.\r\n"
        "bEnableEnvironmentResponse=1\r\n"
        "bEnableParallax=1\r\n"
        "; Parallax quality: 0=Low, 1=Medium, 2=High.\r\n"
        "iParallaxQuality=0\r\n"
        "fParallaxDepth=0.0350000001\r\n"
        "fParallaxGrazingClamp=0.180000007\r\n"
        "fParallaxFadeStart=2048\r\n"
        "fParallaxFadeEnd=8192\r\n"
        "\r\n"
        "[ContactShadows]\n"
        "; Short-range screen-space directional occlusion.\n"
        "bEnabled=0\n"
        "; Reduces work outside the centre view without changing centre fidelity.\r\n"
        "bFoveated=1\r\n"
        "fStrength=0.850000024\r\n"
        "fMaxDistance=96\r\n"
        "fFadeDistance=2048\r\n"
        "fThickness=0.0120000001\r\n"
        "iSampleCount=8\r\n"
        "\r\n"
        "[WrappedGrassLighting]\r\n"
        "bEnabled=0\r\n"
        "fWrapAmount=0.5\r\n"
        "\r\n"
        "[HairSpecular]\r\n"
        "bEnabled=0\r\n"
        "fSpecularMultiplier=1.60000002\r\n"
        "\r\n"
        "[SubsurfaceScattering]\r\n"
        "bEnabled=0\r\n"
        "fStrength=0.550000012\r\n"
        "fRadiusPixels=2\r\n"
        "fDepthRejection=0.00300000003\r\n"
        "\r\n"
        "[CloudShadows]\r\n"
        "bEnabled=0\r\n"
        "fOpacity=0.550000012\r\n"
        "\r\n"
        "[VolumetricLighting]\n"
        "; Full stereo world-space volumetric lighting and Godrays. This is the only\n"
        "; user-facing Godrays switch, and every value below hot-reloads.\n"
        "bEnabled=1\n"
        "; 0=Low, 1=Medium, 2=High.\r\n"
        "iQuality=2\r\n"
        "fIntensity=1.0\r\n"
        "; Zero preserves Fallout's native fog; shafts use local shadow contrast.\n"
        "fBaseScattering=0.0\n"
        "fShaftIntensity=1.35\r\n"
        "fDensityContribution=0.5\n"
        "fDensityScale=1.0\r\n"
        "fWindSpeed=0.0\n"
        "fMaxDistance=3000.0\n"
        "fTemporalWeight=0.90\r\n"
        "\r\n"
        "[BasicWetness]\r\n"
        "bEnabled=1\r\n"
        "fWetness=0.649999976\r\n"
        "fDiffuseDarkening=0.180000007\r\n"
        "fSpecularMultiplier=1.60000002\r\n"
        "fRoughnessScale=0.349999994\r\n"
        "\r\n"
        "; =============================================================================\r\n"
        "; NATIVE ENGINE SHADOWS - RESTART REQUIRED\r\n"
        "; =============================================================================\r\n"
        "[NativeShadows]\r\n"
        "; Fixed startup-only native shadow controls. Restart the game after changes.\r\n"
        "; Independent from the Community Shaders visual suite and DLAA/DLSS.\r\n"
        "; No FPS monitoring, target-FPS logic, or automatic quality adjustment is used.\r\n"
        "bEnabled=0\r\n"
        "bExtendedDirectionalCascades=1\r\n"
        "bTiledDeferredLighting=1\r\n"
        "fDirectionalShadowDistance=12000\r\n"
        "; Both shipped executables default to 100. Large values create broad cascade overlap.\r\n"
        "fCascadeBlendDistance=3000\r\n"
        "; Directional/orthographic shadow PCF level. Engine-supported range: 0-5.\r\n"
        "iOrthographicShadowFilter=3\r\n"
        "\r\n"
        "; =============================================================================\r\n"
        "; VANILLA VR FIXES\r\n"
        "; =============================================================================\r\n"
        "[VanillaFixes]\r\n"
        "; Independent master for native-rendering fixes. Restart after changing it.\r\n"
        "; Does not require the Community Shaders visual suite or DLAA/DLSS.\r\n"
        "bEnabled=1\r\n"
        "bPrecipitationOcclusion=1\r\n"
        "bAllowImageSpaceModifiers=1\r\n"
        "bVrAllowSAO=1\r\n"
        "bVrAllowScreenSpaceReflections=0\r\n"
        "bNativeScreenSpaceMaterialPipeline=1\r\n"
        "bLensFlareVr=0\r\n"
        "bVrAllowFocusShadows=0\r\n"
        "bVrDirectionalLightStability=0\r\n"
        "bVrSunOcclusion=1\r\n"
        "\r\n"
        "; =============================================================================\r\n"
        "; IMAGE PROCESSING AND OUTPUT\r\n"
        "; =============================================================================\r\n"
        "[DLAA]\r\n"
        "; Independent Streamline image-quality master. It can run without the\r\n"
        "; Community Shaders visual suite or Vanilla Fixes.\r\n"
        "bEnabled=0\r\n"
        "; Mode: 0=DLAA, 1=DLSS Quality, 2=DLSS Balanced, 3=DLSS Performance,\r\n"
        "; 4=DLSS Ultra Performance, 5=Centre DLAA plus peripheral TAA.\r\n"
        "iMode=5\r\n"
        "; Model: 0=Automatic, 1=J, 2=K, 3=L, 4=M.\r\n"
        "iModelPreset=2\r\n"
        "bPostSharpening=1\r\n"
        "fSharpness=0.25\r\n"
        "fCenterWidth=0.400000012\r\n"
        "fCenterHeight=0.400000012\r\n"
        "fCenterFeatherPixels=48\r\n"
        "bVisualizeCenter=0\r\n"
        "bHardResetOnLoad=1\r\n"
        "bVerboseDiagnostics=0\r\n"
        "bMotionVectorRepair=1\r\n"
        "\r\n"
        "[FilmicTonemapping]\r\n"
        "; Hue-preserving highlight compression after the native exposure baseline.\r\n"
        "bEnabled=1\r\n"
        "bUseNativeAutoExposure=1\r\n"
        "fExposureCompensationEV=0.0\r\n"
        "fFilmicStrength=1.0\r\n"
        "fWhitePointScale=1.0\r\n"
        "\r\n"
        "[Bloom]\r\n"
        "; Adds an HDR mip-chain bloom while Fallout's native bloom remains active.\r\n"
        "bEnabled=1\r\n"
        "fThresholdEV=3.0\r\n"
        "fIntensity=0.035\r\n"
        "fRadius=2.0\r\n"
        "\r\n"
        "[PhysicalGlare]\r\n"
        "; Per-eye optical glare. FFT resolution: 128=Low, 256=Medium, 512=High.\r\n"
        "bEnabled=1\r\n"
        "fThresholdEV=6.0\r\n"
        "fIntensity=0.20\r\n"
        "iFftResolution=256\r\n"
        "fPaddingRatio=0.10\r\n"
        "iApertureMode=0\r\n"
        "iApertureBlades=6\r\n"
        "fApertureRotationDegrees=0.0\r\n"
        "fFStop=2.8\r\n"
        "fFresnelExponent=30.0\r\n"
        "fSphericalAberration=0.0\r\n"
        "fChromaticSpread=1.0\r\n"
        "fKernelScale=1.0\r\n"
        "fPsfSharpness=0.45\r\n"
        "fPsfNoiseFloor=0.001\r\n"
        "\r\n"
        "; =============================================================================\r\n"
        "; DIAGNOSTICS - LEAVE OFF FOR NORMAL PLAY\r\n"
        "; =============================================================================\r\n"
        "[Diagnostics]\r\n"
        "; Exclusive lighting test selected before launch or hot-reloaded.\r\n"
        "; 0=Off, 1=Native N dot L (red), 2=N dot V (green),\r\n"
        "; 3=Shadow Visibility (blue), 4=Supplied Light Vector (RGB),\r\n"
        "; 5=View Light Vector (RGB), 6=Corrected N dot L (red),\r\n"
        "; 7=Coverage Without Depth (RGB), 8=Coverage Full Raster (RGB),\r\n"
        "; 9=Synthetic DFLight Coverage (RGB), 10=Synthetic Composite Coverage (RGB),\r\n"
        "; 11=Final HDR Output (RGB), 12=Direct Diffuse Only,\r\n"
        "; 13=Direct Specular Only, 14=Native SSR Only,\r\n"
        "; 15=Vanilla Cubemap Only.\r\n"
        "iDirectionalLightingMode=0\r\n"
        "; Continuous image-neutral performance telemetry. Hot-reloaded.\r\n"
        "; 0=Off, 1=Contact Shadows, 2=Skylighting, 3=Both.\r\n"
        "iGpuProfilingMode=0\r\n";
}
