// Generated by tools/generate_distant_tree_linear_lighting_contracts.py.
// Do not edit this file by hand.
constexpr DistantTreeShaderContractDefinition kDistantTreeShaderContract{
    "DistantTreeBlock_00000000",
    0u,
    IDR_LINEAR_LIGHTING_DISTANT_TREE_BLOCK_PS,
    {
        644,
        {
            std::byte{ 0xA1 }, std::byte{ 0x57 }, std::byte{ 0x84 }, std::byte{ 0x71 },
            std::byte{ 0xE3 }, std::byte{ 0x0E }, std::byte{ 0x8C }, std::byte{ 0x34 },
            std::byte{ 0x29 }, std::byte{ 0x10 }, std::byte{ 0x12 }, std::byte{ 0xBE },
            std::byte{ 0xEB }, std::byte{ 0xF8 }, std::byte{ 0x73 }, std::byte{ 0x89 },
        },
    },
    {
        3924,
        {
            std::byte{ 0x15 }, std::byte{ 0x5B }, std::byte{ 0x95 }, std::byte{ 0x4F },
            std::byte{ 0xD2 }, std::byte{ 0x3A }, std::byte{ 0x19 }, std::byte{ 0xE2 },
            std::byte{ 0x7B }, std::byte{ 0xB9 }, std::byte{ 0xF3 }, std::byte{ 0xD5 },
            std::byte{ 0xC7 }, std::byte{ 0x01 }, std::byte{ 0xB0 }, std::byte{ 0x10 },
        },
    },
};
