// Generated by tools/generate_particle_linear_lighting_contracts.py.
// Do not edit this file by hand.
constexpr std::array<ParticleShaderContractDefinition, 4> kParticleShaderContracts{ {
    {
        "ParticleDefault_00000000",
        0u,
        IDR_LINEAR_LIGHTING_PARTICLE_DEFAULT_PS,
        {
            448,
            {
                std::byte{ 0x55 }, std::byte{ 0x2E }, std::byte{ 0x39 }, std::byte{ 0x98 },
                std::byte{ 0x80 }, std::byte{ 0xBC }, std::byte{ 0x2A }, std::byte{ 0x0A },
                std::byte{ 0xB5 }, std::byte{ 0x5C }, std::byte{ 0x2B }, std::byte{ 0x9C },
                std::byte{ 0x34 }, std::byte{ 0xF4 }, std::byte{ 0x39 }, std::byte{ 0xEC },
            },
        },
        {
            2808,
            {
                std::byte{ 0x2A }, std::byte{ 0xB8 }, std::byte{ 0xBF }, std::byte{ 0x78 },
                std::byte{ 0xE9 }, std::byte{ 0xC3 }, std::byte{ 0x81 }, std::byte{ 0x2A },
                std::byte{ 0x9F }, std::byte{ 0xA2 }, std::byte{ 0x00 }, std::byte{ 0x0D },
                std::byte{ 0xF4 }, std::byte{ 0xA7 }, std::byte{ 0x9E }, std::byte{ 0xB7 },
            },
        },
    },
    {
        "ParticleGrayscaleToColor_00000001",
        1u,
        IDR_LINEAR_LIGHTING_PARTICLE_GRAYSCALE_COLOR_PS,
        {
            520,
            {
                std::byte{ 0xC3 }, std::byte{ 0xA4 }, std::byte{ 0xB0 }, std::byte{ 0xEC },
                std::byte{ 0x6D }, std::byte{ 0xB6 }, std::byte{ 0x5B }, std::byte{ 0xEB },
                std::byte{ 0x6F }, std::byte{ 0x8F }, std::byte{ 0x2C }, std::byte{ 0x0A },
                std::byte{ 0xCA }, std::byte{ 0x25 }, std::byte{ 0x8A }, std::byte{ 0xEA },
            },
        },
        {
            2980,
            {
                std::byte{ 0x29 }, std::byte{ 0xEE }, std::byte{ 0x89 }, std::byte{ 0x66 },
                std::byte{ 0x8F }, std::byte{ 0x88 }, std::byte{ 0x8D }, std::byte{ 0x99 },
                std::byte{ 0x3E }, std::byte{ 0x0F }, std::byte{ 0x8A }, std::byte{ 0x6A },
                std::byte{ 0xC6 }, std::byte{ 0xBD }, std::byte{ 0x1C }, std::byte{ 0x41 },
            },
        },
    },
    {
        "ParticleGrayscaleToAlpha_00000002",
        2u,
        IDR_LINEAR_LIGHTING_PARTICLE_GRAYSCALE_ALPHA_PS,
        {
            560,
            {
                std::byte{ 0x41 }, std::byte{ 0xDA }, std::byte{ 0x21 }, std::byte{ 0xC6 },
                std::byte{ 0xA2 }, std::byte{ 0x4D }, std::byte{ 0x91 }, std::byte{ 0xC5 },
                std::byte{ 0x35 }, std::byte{ 0x9F }, std::byte{ 0xCF }, std::byte{ 0xC5 },
                std::byte{ 0x8E }, std::byte{ 0x43 }, std::byte{ 0x03 }, std::byte{ 0x8C },
            },
        },
        {
            3000,
            {
                std::byte{ 0x61 }, std::byte{ 0x24 }, std::byte{ 0x3A }, std::byte{ 0xC4 },
                std::byte{ 0x17 }, std::byte{ 0x75 }, std::byte{ 0x09 }, std::byte{ 0x62 },
                std::byte{ 0xAC }, std::byte{ 0xE0 }, std::byte{ 0x35 }, std::byte{ 0x44 },
                std::byte{ 0x9B }, std::byte{ 0x4C }, std::byte{ 0x8D }, std::byte{ 0x27 },
            },
        },
    },
    {
        "ParticleGrayscaleToColorAlpha_00000003",
        3u,
        IDR_LINEAR_LIGHTING_PARTICLE_GRAYSCALE_COLOR_ALPHA_PS,
        {
            556,
            {
                std::byte{ 0xFD }, std::byte{ 0xAF }, std::byte{ 0xBB }, std::byte{ 0xC5 },
                std::byte{ 0xB4 }, std::byte{ 0xA5 }, std::byte{ 0xDC }, std::byte{ 0xD3 },
                std::byte{ 0x9A }, std::byte{ 0x25 }, std::byte{ 0x3F }, std::byte{ 0x9B },
                std::byte{ 0x54 }, std::byte{ 0xB4 }, std::byte{ 0x12 }, std::byte{ 0xAF },
            },
        },
        {
            3016,
            {
                std::byte{ 0xC1 }, std::byte{ 0x93 }, std::byte{ 0x97 }, std::byte{ 0x09 },
                std::byte{ 0xE0 }, std::byte{ 0xA5 }, std::byte{ 0xCD }, std::byte{ 0xB0 },
                std::byte{ 0x6B }, std::byte{ 0x7D }, std::byte{ 0xD0 }, std::byte{ 0x66 },
                std::byte{ 0xF4 }, std::byte{ 0x9B }, std::byte{ 0x7A }, std::byte{ 0xAD },
            },
        },
    },
} };
