// Generated by tools/generate_distant_tree_linear_lighting_contracts.py.
// Do not edit this file by hand.
constexpr DistantTreeShaderContractDefinition kDistantTreeShaderContract{
    "DistantTreeBlock_00000000",
    0u,
    IDR_LINEAR_LIGHTING_DISTANT_TREE_BLOCK_PS,
    {
        644,
        {
            std::byte{ 0xA1 }, std::byte{ 0x57 }, std::byte{ 0x84 }, std::byte{ 0x71 },
            std::byte{ 0xE3 }, std::byte{ 0x0E }, std::byte{ 0x8C }, std::byte{ 0x34 },
            std::byte{ 0x29 }, std::byte{ 0x10 }, std::byte{ 0x12 }, std::byte{ 0xBE },
            std::byte{ 0xEB }, std::byte{ 0xF8 }, std::byte{ 0x73 }, std::byte{ 0x89 },
        },
    },
    {
        4044,
        {
            std::byte{ 0x72 }, std::byte{ 0x12 }, std::byte{ 0xA1 }, std::byte{ 0xBA },
            std::byte{ 0x0B }, std::byte{ 0x75 }, std::byte{ 0x43 }, std::byte{ 0xE1 },
            std::byte{ 0x4A }, std::byte{ 0x25 }, std::byte{ 0x9D }, std::byte{ 0x95 },
            std::byte{ 0x4A }, std::byte{ 0x48 }, std::byte{ 0xC5 }, std::byte{ 0x2F },
        },
    },
};
