// Generated by tools/generate_sky_linear_lighting_contracts.py.
// Do not edit this file by hand.
constexpr std::array<SkyShaderContractDefinition, 8> kSkyShaderContracts{ {
    {
        "SkyTechnique1_00000001",
        1u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_1_PS,
        {
            1240,
            {
                std::byte{ 0x7C }, std::byte{ 0xEC }, std::byte{ 0x59 }, std::byte{ 0x49 },
                std::byte{ 0xCB }, std::byte{ 0x36 }, std::byte{ 0x1A }, std::byte{ 0xAA },
                std::byte{ 0xF0 }, std::byte{ 0xAF }, std::byte{ 0x71 }, std::byte{ 0xC2 },
                std::byte{ 0xB8 }, std::byte{ 0xE4 }, std::byte{ 0xEB }, std::byte{ 0xF6 },
            },
        },
        {
            3936,
            {
                std::byte{ 0xD0 }, std::byte{ 0xDA }, std::byte{ 0xF1 }, std::byte{ 0x8E },
                std::byte{ 0x4A }, std::byte{ 0x12 }, std::byte{ 0xDA }, std::byte{ 0x3A },
                std::byte{ 0x26 }, std::byte{ 0x69 }, std::byte{ 0xC2 }, std::byte{ 0x1F },
                std::byte{ 0x2B }, std::byte{ 0xA4 }, std::byte{ 0x84 }, std::byte{ 0x57 },
            },
        },
    },
    {
        "SkyTechnique2_00000002",
        2u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_2_PS,
        {
            1192,
            {
                std::byte{ 0x5F }, std::byte{ 0x38 }, std::byte{ 0x3A }, std::byte{ 0x68 },
                std::byte{ 0x19 }, std::byte{ 0x35 }, std::byte{ 0x55 }, std::byte{ 0xF7 },
                std::byte{ 0xAA }, std::byte{ 0x6B }, std::byte{ 0x59 }, std::byte{ 0x11 },
                std::byte{ 0x20 }, std::byte{ 0x99 }, std::byte{ 0x59 }, std::byte{ 0x45 },
            },
        },
        {
            3580,
            {
                std::byte{ 0x82 }, std::byte{ 0x65 }, std::byte{ 0xB9 }, std::byte{ 0x9B },
                std::byte{ 0x82 }, std::byte{ 0x68 }, std::byte{ 0x96 }, std::byte{ 0x72 },
                std::byte{ 0x40 }, std::byte{ 0x30 }, std::byte{ 0x36 }, std::byte{ 0x1D },
                std::byte{ 0xA9 }, std::byte{ 0x21 }, std::byte{ 0x33 }, std::byte{ 0xBE },
            },
        },
    },
    {
        "SkyTechnique3_00000003",
        3u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_3_PS,
        {
            1276,
            {
                std::byte{ 0xFA }, std::byte{ 0x67 }, std::byte{ 0x75 }, std::byte{ 0xBA },
                std::byte{ 0x64 }, std::byte{ 0x44 }, std::byte{ 0x05 }, std::byte{ 0x41 },
                std::byte{ 0x61 }, std::byte{ 0x89 }, std::byte{ 0x72 }, std::byte{ 0x4E },
                std::byte{ 0x24 }, std::byte{ 0x85 }, std::byte{ 0xB7 }, std::byte{ 0xFB },
            },
        },
        {
            4112,
            {
                std::byte{ 0xE9 }, std::byte{ 0xDB }, std::byte{ 0x98 }, std::byte{ 0x6B },
                std::byte{ 0x5B }, std::byte{ 0x73 }, std::byte{ 0x56 }, std::byte{ 0x85 },
                std::byte{ 0xE4 }, std::byte{ 0xEC }, std::byte{ 0xAD }, std::byte{ 0xBD },
                std::byte{ 0x14 }, std::byte{ 0xF2 }, std::byte{ 0x02 }, std::byte{ 0xE5 },
            },
        },
    },
    {
        "SkyTechnique4_00000004",
        4u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_4_PS,
        {
            1268,
            {
                std::byte{ 0xD8 }, std::byte{ 0xD2 }, std::byte{ 0x31 }, std::byte{ 0x30 },
                std::byte{ 0xCB }, std::byte{ 0x63 }, std::byte{ 0x95 }, std::byte{ 0x48 },
                std::byte{ 0xB5 }, std::byte{ 0x17 }, std::byte{ 0x94 }, std::byte{ 0xA8 },
                std::byte{ 0xAA }, std::byte{ 0x2F }, std::byte{ 0x65 }, std::byte{ 0x83 },
            },
        },
        {
            4132,
            {
                std::byte{ 0xA3 }, std::byte{ 0x3E }, std::byte{ 0x81 }, std::byte{ 0x03 },
                std::byte{ 0x82 }, std::byte{ 0xF2 }, std::byte{ 0x44 }, std::byte{ 0xE4 },
                std::byte{ 0x5F }, std::byte{ 0x92 }, std::byte{ 0x48 }, std::byte{ 0xD9 },
                std::byte{ 0x37 }, std::byte{ 0x52 }, std::byte{ 0x92 }, std::byte{ 0x3E },
            },
        },
    },
    {
        "SkyTechnique5_00000005",
        5u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_5_PS,
        {
            1200,
            {
                std::byte{ 0x44 }, std::byte{ 0xC7 }, std::byte{ 0x1E }, std::byte{ 0xBA },
                std::byte{ 0x61 }, std::byte{ 0x9B }, std::byte{ 0x41 }, std::byte{ 0xC2 },
                std::byte{ 0x64 }, std::byte{ 0x24 }, std::byte{ 0x0D }, std::byte{ 0xAA },
                std::byte{ 0xBA }, std::byte{ 0x7B }, std::byte{ 0x16 }, std::byte{ 0x5E },
            },
        },
        {
            4084,
            {
                std::byte{ 0xED }, std::byte{ 0x80 }, std::byte{ 0x67 }, std::byte{ 0x52 },
                std::byte{ 0xC0 }, std::byte{ 0xC7 }, std::byte{ 0xB2 }, std::byte{ 0x5B },
                std::byte{ 0x36 }, std::byte{ 0xBA }, std::byte{ 0x03 }, std::byte{ 0x43 },
                std::byte{ 0x93 }, std::byte{ 0x8D }, std::byte{ 0x0D }, std::byte{ 0x74 },
            },
        },
    },
    {
        "SkyTechnique6_00000006",
        6u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_6_PS,
        {
            1380,
            {
                std::byte{ 0xA4 }, std::byte{ 0x02 }, std::byte{ 0x09 }, std::byte{ 0xE2 },
                std::byte{ 0x3F }, std::byte{ 0x89 }, std::byte{ 0x5B }, std::byte{ 0x31 },
                std::byte{ 0xDC }, std::byte{ 0x05 }, std::byte{ 0x1B }, std::byte{ 0xA9 },
                std::byte{ 0xF2 }, std::byte{ 0xF9 }, std::byte{ 0x4C }, std::byte{ 0x5E },
            },
        },
        {
            4548,
            {
                std::byte{ 0x0A }, std::byte{ 0x67 }, std::byte{ 0xC3 }, std::byte{ 0xAB },
                std::byte{ 0x16 }, std::byte{ 0xF5 }, std::byte{ 0x72 }, std::byte{ 0xEE },
                std::byte{ 0xA3 }, std::byte{ 0x44 }, std::byte{ 0xC2 }, std::byte{ 0xB0 },
                std::byte{ 0x39 }, std::byte{ 0x6F }, std::byte{ 0xC9 }, std::byte{ 0x1D },
            },
        },
    },
    {
        "SkyTechnique7_00000007",
        7u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_7_PS,
        {
            1288,
            {
                std::byte{ 0xE1 }, std::byte{ 0xD3 }, std::byte{ 0x2A }, std::byte{ 0xE8 },
                std::byte{ 0xBF }, std::byte{ 0x36 }, std::byte{ 0xFD }, std::byte{ 0x42 },
                std::byte{ 0x22 }, std::byte{ 0x61 }, std::byte{ 0xCE }, std::byte{ 0xC9 },
                std::byte{ 0xF3 }, std::byte{ 0xC3 }, std::byte{ 0x41 }, std::byte{ 0x23 },
            },
        },
        {
            4096,
            {
                std::byte{ 0x40 }, std::byte{ 0xB0 }, std::byte{ 0x8F }, std::byte{ 0x62 },
                std::byte{ 0x0A }, std::byte{ 0x9A }, std::byte{ 0x3A }, std::byte{ 0x58 },
                std::byte{ 0xA1 }, std::byte{ 0xA0 }, std::byte{ 0xAF }, std::byte{ 0x01 },
                std::byte{ 0x59 }, std::byte{ 0x75 }, std::byte{ 0x59 }, std::byte{ 0x67 },
            },
        },
    },
    {
        "SkyTechnique8_00000008",
        8u,
        IDR_LINEAR_LIGHTING_SKY_TECHNIQUE_8_PS,
        {
            1384,
            {
                std::byte{ 0xB8 }, std::byte{ 0x7A }, std::byte{ 0x16 }, std::byte{ 0xD1 },
                std::byte{ 0xD6 }, std::byte{ 0x40 }, std::byte{ 0x80 }, std::byte{ 0x42 },
                std::byte{ 0xF3 }, std::byte{ 0xEE }, std::byte{ 0x2A }, std::byte{ 0xB8 },
                std::byte{ 0xDC }, std::byte{ 0x3E }, std::byte{ 0x87 }, std::byte{ 0x24 },
            },
        },
        {
            4288,
            {
                std::byte{ 0xA2 }, std::byte{ 0x3E }, std::byte{ 0x8E }, std::byte{ 0x21 },
                std::byte{ 0x3E }, std::byte{ 0x84 }, std::byte{ 0x99 }, std::byte{ 0x32 },
                std::byte{ 0xE5 }, std::byte{ 0xD3 }, std::byte{ 0xF2 }, std::byte{ 0xA9 },
                std::byte{ 0x6A }, std::byte{ 0xA2 }, std::byte{ 0x68 }, std::byte{ 0x72 },
            },
        },
    },
} };
