// Generated by tools/generate_dflight_ambient_contracts.py.
// Do not edit by hand.
constexpr std::array<DFLightAmbientContractDefinition,
    39> kDFLightAmbientContracts{{
    DFLightAmbientContractDefinition{
        "DFLightAmbient_0053d7e2_13136",
        DxbcIdentity{
            13136,
            { std::byte{ 0x00 }, std::byte{ 0x53 }, std::byte{ 0xD7 }, std::byte{ 0xE2 }, std::byte{ 0x49 }, std::byte{ 0xB1 }, std::byte{ 0x4B }, std::byte{ 0xF4 }, std::byte{ 0x0C }, std::byte{ 0xE5 }, std::byte{ 0x74 }, std::byte{ 0x90 }, std::byte{ 0xAC }, std::byte{ 0xC7 }, std::byte{ 0x35 }, std::byte{ 0xDC } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x000028D4u, 0x000028D8u, 0x000028DCu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_04e0ed28_9204",
        DxbcIdentity{
            9204,
            { std::byte{ 0x04 }, std::byte{ 0xE0 }, std::byte{ 0xED }, std::byte{ 0x28 }, std::byte{ 0x25 }, std::byte{ 0xFF }, std::byte{ 0xDE }, std::byte{ 0x29 }, std::byte{ 0xE6 }, std::byte{ 0x1A }, std::byte{ 0x61 }, std::byte{ 0x21 }, std::byte{ 0xC5 }, std::byte{ 0x67 }, std::byte{ 0xF2 }, std::byte{ 0x92 } },
        },
        { 0x000008ACu, 0x000008B0u, 0x000008B4u, 0x00001CA4u, 0x00001CA8u, 0x00001CACu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_0b71be4b_64488",
        DxbcIdentity{
            64488,
            { std::byte{ 0x0B }, std::byte{ 0x71 }, std::byte{ 0xBE }, std::byte{ 0x4B }, std::byte{ 0x2E }, std::byte{ 0x9D }, std::byte{ 0xE8 }, std::byte{ 0xCD }, std::byte{ 0xFB }, std::byte{ 0x06 }, std::byte{ 0x33 }, std::byte{ 0xDB }, std::byte{ 0x5A }, std::byte{ 0xC4 }, std::byte{ 0xAE }, std::byte{ 0xE7 } },
        },
        { 0x00004748u, 0x0000474Cu, 0x00004750u, 0x0000F16Cu, 0x0000F170u, 0x0000F174u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_0bbd4d8b_10156",
        DxbcIdentity{
            10156,
            { std::byte{ 0x0B }, std::byte{ 0xBD }, std::byte{ 0x4D }, std::byte{ 0x8B }, std::byte{ 0xE9 }, std::byte{ 0x92 }, std::byte{ 0x05 }, std::byte{ 0x1E }, std::byte{ 0x42 }, std::byte{ 0xBF }, std::byte{ 0x42 }, std::byte{ 0x56 }, std::byte{ 0xFE }, std::byte{ 0x21 }, std::byte{ 0x76 }, std::byte{ 0x58 } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001D30u, 0x00001D34u, 0x00001D38u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_18e21c61_10084",
        DxbcIdentity{
            10084,
            { std::byte{ 0x18 }, std::byte{ 0xE2 }, std::byte{ 0x1C }, std::byte{ 0x61 }, std::byte{ 0xEC }, std::byte{ 0x32 }, std::byte{ 0x3E }, std::byte{ 0x5E }, std::byte{ 0x24 }, std::byte{ 0xC3 }, std::byte{ 0x0E }, std::byte{ 0xFF }, std::byte{ 0x0C }, std::byte{ 0x09 }, std::byte{ 0xC9 }, std::byte{ 0x2A } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001CE8u, 0x00001CECu, 0x00001CF0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_1b7a77fd_9900",
        DxbcIdentity{
            9900,
            { std::byte{ 0x1B }, std::byte{ 0x7A }, std::byte{ 0x77 }, std::byte{ 0xFD }, std::byte{ 0x79 }, std::byte{ 0xF9 }, std::byte{ 0xB5 }, std::byte{ 0x41 }, std::byte{ 0x1D }, std::byte{ 0xAE }, std::byte{ 0x26 }, std::byte{ 0x58 }, std::byte{ 0x02 }, std::byte{ 0x06 }, std::byte{ 0xAE }, std::byte{ 0x1A } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001C30u, 0x00001C34u, 0x00001C38u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_1d065bd1_2912",
        DxbcIdentity{
            2912,
            { std::byte{ 0x1D }, std::byte{ 0x06 }, std::byte{ 0x5B }, std::byte{ 0xD1 }, std::byte{ 0x66 }, std::byte{ 0x1B }, std::byte{ 0x18 }, std::byte{ 0x45 }, std::byte{ 0xFF }, std::byte{ 0xA8 }, std::byte{ 0x9C }, std::byte{ 0x9B }, std::byte{ 0xD1 }, std::byte{ 0xD0 }, std::byte{ 0x9C }, std::byte{ 0xAB } },
        },
        { 0x00000848u, 0x0000084Cu, 0x00000850u, 0x00000A4Cu, 0x00000A50u, 0x00000A54u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_235b930a_26072",
        DxbcIdentity{
            26072,
            { std::byte{ 0x23 }, std::byte{ 0x5B }, std::byte{ 0x93 }, std::byte{ 0x0A }, std::byte{ 0x82 }, std::byte{ 0xCE }, std::byte{ 0xBF }, std::byte{ 0x73 }, std::byte{ 0xBB }, std::byte{ 0x32 }, std::byte{ 0x5E }, std::byte{ 0x6F }, std::byte{ 0x4C }, std::byte{ 0xD7 }, std::byte{ 0xF2 }, std::byte{ 0x96 } },
        },
        { 0x000008E8u, 0x000008ECu, 0x000008F0u, 0x00005B5Cu, 0x00005B60u, 0x00005B64u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_246964c9_13208",
        DxbcIdentity{
            13208,
            { std::byte{ 0x24 }, std::byte{ 0x69 }, std::byte{ 0x64 }, std::byte{ 0xC9 }, std::byte{ 0x02 }, std::byte{ 0x2C }, std::byte{ 0x40 }, std::byte{ 0xEC }, std::byte{ 0xF9 }, std::byte{ 0xB4 }, std::byte{ 0x67 }, std::byte{ 0xA9 }, std::byte{ 0x03 }, std::byte{ 0xD6 }, std::byte{ 0x36 }, std::byte{ 0xDB } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x0000291Cu, 0x00002920u, 0x00002924u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_267befcc_26144",
        DxbcIdentity{
            26144,
            { std::byte{ 0x26 }, std::byte{ 0x7B }, std::byte{ 0xEF }, std::byte{ 0xCC }, std::byte{ 0xC6 }, std::byte{ 0x90 }, std::byte{ 0x54 }, std::byte{ 0x8B }, std::byte{ 0x65 }, std::byte{ 0x43 }, std::byte{ 0x02 }, std::byte{ 0xAD }, std::byte{ 0xF3 }, std::byte{ 0xD5 }, std::byte{ 0x3D }, std::byte{ 0x35 } },
        },
        { 0x000008E8u, 0x000008ECu, 0x000008F0u, 0x00005BA4u, 0x00005BA8u, 0x00005BACu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_2a28f204_30032",
        DxbcIdentity{
            30032,
            { std::byte{ 0x2A }, std::byte{ 0x28 }, std::byte{ 0xF2 }, std::byte{ 0x04 }, std::byte{ 0xAF }, std::byte{ 0xAB }, std::byte{ 0x29 }, std::byte{ 0x96 }, std::byte{ 0x0A }, std::byte{ 0x71 }, std::byte{ 0x61 }, std::byte{ 0xD6 }, std::byte{ 0x15 }, std::byte{ 0x58 }, std::byte{ 0x91 }, std::byte{ 0x69 } },
        },
        { 0x0000470Cu, 0x00004710u, 0x00004714u, 0x00006E00u, 0x00006E04u, 0x00006E08u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_2d5fee10_7976",
        DxbcIdentity{
            7976,
            { std::byte{ 0x2D }, std::byte{ 0x5F }, std::byte{ 0xEE }, std::byte{ 0x10 }, std::byte{ 0xD8 }, std::byte{ 0xA4 }, std::byte{ 0x78 }, std::byte{ 0x36 }, std::byte{ 0x50 }, std::byte{ 0xD2 }, std::byte{ 0x3C }, std::byte{ 0x49 }, std::byte{ 0x9F }, std::byte{ 0x35 }, std::byte{ 0xBC }, std::byte{ 0x87 } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x000014ACu, 0x000014B0u, 0x000014B4u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_2fc73abc_24264",
        DxbcIdentity{
            24264,
            { std::byte{ 0x2F }, std::byte{ 0xC7 }, std::byte{ 0x3A }, std::byte{ 0xBC }, std::byte{ 0x57 }, std::byte{ 0x65 }, std::byte{ 0x4C }, std::byte{ 0x88 }, std::byte{ 0x30 }, std::byte{ 0x98 }, std::byte{ 0xF3 }, std::byte{ 0x3F }, std::byte{ 0xF8 }, std::byte{ 0x42 }, std::byte{ 0xBA }, std::byte{ 0xEC } },
        },
        { 0x0000472Cu, 0x00004730u, 0x00004734u, 0x0000544Cu, 0x00005450u, 0x00005454u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_4cdeb9b6_7944",
        DxbcIdentity{
            7944,
            { std::byte{ 0x4C }, std::byte{ 0xDE }, std::byte{ 0xB9 }, std::byte{ 0xB6 }, std::byte{ 0x41 }, std::byte{ 0xF5 }, std::byte{ 0x04 }, std::byte{ 0x5B }, std::byte{ 0xC2 }, std::byte{ 0x3D }, std::byte{ 0xC7 }, std::byte{ 0x4B }, std::byte{ 0x32 }, std::byte{ 0x13 }, std::byte{ 0x92 }, std::byte{ 0x52 } },
        },
        { 0x000008ACu, 0x000008B0u, 0x000008B4u, 0x000017B8u, 0x000017BCu, 0x000017C0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_579bfa84_30932",
        DxbcIdentity{
            30932,
            { std::byte{ 0x57 }, std::byte{ 0x9B }, std::byte{ 0xFA }, std::byte{ 0x84 }, std::byte{ 0xF6 }, std::byte{ 0xBA }, std::byte{ 0x42 }, std::byte{ 0x39 }, std::byte{ 0xC1 }, std::byte{ 0xF9 }, std::byte{ 0x76 }, std::byte{ 0x52 }, std::byte{ 0x59 }, std::byte{ 0x78 }, std::byte{ 0x04 }, std::byte{ 0xA4 } },
        },
        { 0x0000472Cu, 0x00004730u, 0x00004734u, 0x00006E58u, 0x00006E5Cu, 0x00006E60u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_5905a51c_3604",
        DxbcIdentity{
            3604,
            { std::byte{ 0x59 }, std::byte{ 0x05 }, std::byte{ 0xA5 }, std::byte{ 0x1C }, std::byte{ 0x9C }, std::byte{ 0x19 }, std::byte{ 0x64 }, std::byte{ 0x33 }, std::byte{ 0x23 }, std::byte{ 0xE0 }, std::byte{ 0x9C }, std::byte{ 0x1D }, std::byte{ 0x16 }, std::byte{ 0x0D }, std::byte{ 0x15 }, std::byte{ 0x31 } },
        },
        { 0x0000080Cu, 0x00000810u, 0x00000814u, 0x00000D20u, 0x00000D24u, 0x00000D28u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_68c5ffe0_26040",
        DxbcIdentity{
            26040,
            { std::byte{ 0x68 }, std::byte{ 0xC5 }, std::byte{ 0xFF }, std::byte{ 0xE0 }, std::byte{ 0x52 }, std::byte{ 0xF7 }, std::byte{ 0xF2 }, std::byte{ 0x7A }, std::byte{ 0xB0 }, std::byte{ 0xDE }, std::byte{ 0xD4 }, std::byte{ 0x61 }, std::byte{ 0xA2 }, std::byte{ 0xAE }, std::byte{ 0xC5 }, std::byte{ 0x83 } },
        },
        { 0x0000470Cu, 0x00004710u, 0x00004714u, 0x00005E68u, 0x00005E6Cu, 0x00005E70u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_6a73562e_26932",
        DxbcIdentity{
            26932,
            { std::byte{ 0x6A }, std::byte{ 0x73 }, std::byte{ 0x56 }, std::byte{ 0x2E }, std::byte{ 0x94 }, std::byte{ 0x57 }, std::byte{ 0xF8 }, std::byte{ 0x89 }, std::byte{ 0x8D }, std::byte{ 0x98 }, std::byte{ 0xFA }, std::byte{ 0x4C }, std::byte{ 0x31 }, std::byte{ 0xE2 }, std::byte{ 0x2B }, std::byte{ 0x75 } },
        },
        { 0x0000472Cu, 0x00004730u, 0x00004734u, 0x00005EB8u, 0x00005EBCu, 0x00005EC0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_7006b78d_25236",
        DxbcIdentity{
            25236,
            { std::byte{ 0x70 }, std::byte{ 0x06 }, std::byte{ 0xB7 }, std::byte{ 0x8D }, std::byte{ 0xBC }, std::byte{ 0x69 }, std::byte{ 0xD8 }, std::byte{ 0x3F }, std::byte{ 0xBB }, std::byte{ 0x42 }, std::byte{ 0xF5 }, std::byte{ 0x36 }, std::byte{ 0xC7 }, std::byte{ 0x73 }, std::byte{ 0x01 }, std::byte{ 0xD6 } },
        },
        { 0x000008C8u, 0x000008CCu, 0x000008D0u, 0x00005B44u, 0x00005B48u, 0x00005B4Cu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_89c3d428_20316",
        DxbcIdentity{
            20316,
            { std::byte{ 0x89 }, std::byte{ 0xC3 }, std::byte{ 0xD4 }, std::byte{ 0x28 }, std::byte{ 0x14 }, std::byte{ 0x8B }, std::byte{ 0x09 }, std::byte{ 0x87 }, std::byte{ 0xE8 }, std::byte{ 0x85 }, std::byte{ 0xE3 }, std::byte{ 0xC5 }, std::byte{ 0x99 }, std::byte{ 0xA0 }, std::byte{ 0xE1 }, std::byte{ 0x9A } },
        },
        { 0x0000466Cu, 0x00004670u, 0x00004674u, 0x00004E68u, 0x00004E6Cu, 0x00004E70u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_a4452ef0_26860",
        DxbcIdentity{
            26860,
            { std::byte{ 0xA4 }, std::byte{ 0x45 }, std::byte{ 0x2E }, std::byte{ 0xF0 }, std::byte{ 0x99 }, std::byte{ 0x93 }, std::byte{ 0x16 }, std::byte{ 0x57 }, std::byte{ 0x2B }, std::byte{ 0x11 }, std::byte{ 0xAA }, std::byte{ 0xA7 }, std::byte{ 0x38 }, std::byte{ 0xF9 }, std::byte{ 0x4B }, std::byte{ 0xCA } },
        },
        { 0x0000472Cu, 0x00004730u, 0x00004734u, 0x00005E70u, 0x00005E74u, 0x00005E78u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_a59e261f_25968",
        DxbcIdentity{
            25968,
            { std::byte{ 0xA5 }, std::byte{ 0x9E }, std::byte{ 0x26 }, std::byte{ 0x1F }, std::byte{ 0xE6 }, std::byte{ 0x65 }, std::byte{ 0x7F }, std::byte{ 0x18 }, std::byte{ 0x9F }, std::byte{ 0x67 }, std::byte{ 0xD0 }, std::byte{ 0xB7 }, std::byte{ 0xEF }, std::byte{ 0xCE }, std::byte{ 0xAD }, std::byte{ 0x7F } },
        },
        { 0x0000470Cu, 0x00004710u, 0x00004714u, 0x00005E20u, 0x00005E24u, 0x00005E28u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_a6f66042_47648",
        DxbcIdentity{
            47648,
            { std::byte{ 0xA6 }, std::byte{ 0xF6 }, std::byte{ 0x60 }, std::byte{ 0x42 }, std::byte{ 0x19 }, std::byte{ 0xB7 }, std::byte{ 0x5A }, std::byte{ 0xD1 }, std::byte{ 0x41 }, std::byte{ 0x46 }, std::byte{ 0x6E }, std::byte{ 0x7A }, std::byte{ 0x57 }, std::byte{ 0xA3 }, std::byte{ 0x4B }, std::byte{ 0x70 } },
        },
        { 0x000008C8u, 0x000008CCu, 0x000008D0u, 0x0000B2D0u, 0x0000B2D4u, 0x0000B2D8u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_affb527d_6960",
        DxbcIdentity{
            6960,
            { std::byte{ 0xAF }, std::byte{ 0xFB }, std::byte{ 0x52 }, std::byte{ 0x7D }, std::byte{ 0x99 }, std::byte{ 0x5E }, std::byte{ 0x74 }, std::byte{ 0x30 }, std::byte{ 0xE7 }, std::byte{ 0x51 }, std::byte{ 0x4D }, std::byte{ 0x60 }, std::byte{ 0xBE }, std::byte{ 0x1C }, std::byte{ 0x4C }, std::byte{ 0x9E } },
        },
        { 0x000008B0u, 0x000008B4u, 0x000008B8u, 0x000010D8u, 0x000010DCu, 0x000010E0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_b4fb1f66_9316",
        DxbcIdentity{
            9316,
            { std::byte{ 0xB4 }, std::byte{ 0xFB }, std::byte{ 0x1F }, std::byte{ 0x66 }, std::byte{ 0x4E }, std::byte{ 0x29 }, std::byte{ 0x90 }, std::byte{ 0xD1 }, std::byte{ 0x69 }, std::byte{ 0xAA }, std::byte{ 0xF9 }, std::byte{ 0x28 }, std::byte{ 0x7D }, std::byte{ 0x21 }, std::byte{ 0x1F }, std::byte{ 0x56 } },
        },
        { 0x000008E8u, 0x000008ECu, 0x000008F0u, 0x000019E8u, 0x000019ECu, 0x000019F0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_bfd64867_6064",
        DxbcIdentity{
            6064,
            { std::byte{ 0xBF }, std::byte{ 0xD6 }, std::byte{ 0x48 }, std::byte{ 0x67 }, std::byte{ 0x56 }, std::byte{ 0x1A }, std::byte{ 0x7B }, std::byte{ 0x87 }, std::byte{ 0x75 }, std::byte{ 0x5E }, std::byte{ 0xE1 }, std::byte{ 0x0D }, std::byte{ 0x9F }, std::byte{ 0xBB }, std::byte{ 0x8D }, std::byte{ 0x13 } },
        },
        { 0x00000890u, 0x00000894u, 0x00000898u, 0x00001084u, 0x00001088u, 0x0000108Cu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_c3c4e934_9276",
        DxbcIdentity{
            9276,
            { std::byte{ 0xC3 }, std::byte{ 0xC4 }, std::byte{ 0xE9 }, std::byte{ 0x34 }, std::byte{ 0x54 }, std::byte{ 0xEB }, std::byte{ 0x1F }, std::byte{ 0xBF }, std::byte{ 0xD2 }, std::byte{ 0x2B }, std::byte{ 0x35 }, std::byte{ 0x47 }, std::byte{ 0x31 }, std::byte{ 0x2B }, std::byte{ 0x35 }, std::byte{ 0xBB } },
        },
        { 0x000008ACu, 0x000008B0u, 0x000008B4u, 0x00001CECu, 0x00001CF0u, 0x00001CF4u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_c7851fe9_10140",
        DxbcIdentity{
            10140,
            { std::byte{ 0xC7 }, std::byte{ 0x85 }, std::byte{ 0x1F }, std::byte{ 0xE9 }, std::byte{ 0x0E }, std::byte{ 0x50 }, std::byte{ 0xB3 }, std::byte{ 0x0A }, std::byte{ 0x6B }, std::byte{ 0x30 }, std::byte{ 0xCB }, std::byte{ 0x98 }, std::byte{ 0x86 }, std::byte{ 0x80 }, std::byte{ 0x70 }, std::byte{ 0x03 } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001D20u, 0x00001D24u, 0x00001D28u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_cb69199d_7552",
        DxbcIdentity{
            7552,
            { std::byte{ 0xCB }, std::byte{ 0x69 }, std::byte{ 0x19 }, std::byte{ 0x9D }, std::byte{ 0x7E }, std::byte{ 0xDF }, std::byte{ 0xA4 }, std::byte{ 0x35 }, std::byte{ 0xE5 }, std::byte{ 0xE1 }, std::byte{ 0x3C }, std::byte{ 0xBA }, std::byte{ 0x95 }, std::byte{ 0xFE }, std::byte{ 0xF4 }, std::byte{ 0x52 } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001304u, 0x00001308u, 0x0000130Cu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_cbf41beb_10068",
        DxbcIdentity{
            10068,
            { std::byte{ 0xCB }, std::byte{ 0xF4 }, std::byte{ 0x1B }, std::byte{ 0xEB }, std::byte{ 0x05 }, std::byte{ 0x04 }, std::byte{ 0x23 }, std::byte{ 0x5B }, std::byte{ 0x9E }, std::byte{ 0xE8 }, std::byte{ 0x1E }, std::byte{ 0xB0 }, std::byte{ 0x47 }, std::byte{ 0x4A }, std::byte{ 0x01 }, std::byte{ 0x8D } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001CD8u, 0x00001CDCu, 0x00001CE0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_cc39d21d_31004",
        DxbcIdentity{
            31004,
            { std::byte{ 0xCC }, std::byte{ 0x39 }, std::byte{ 0xD2 }, std::byte{ 0x1D }, std::byte{ 0x04 }, std::byte{ 0xD8 }, std::byte{ 0x32 }, std::byte{ 0x70 }, std::byte{ 0x35 }, std::byte{ 0x51 }, std::byte{ 0xB3 }, std::byte{ 0xAA }, std::byte{ 0x94 }, std::byte{ 0xFA }, std::byte{ 0x63 }, std::byte{ 0x8C } },
        },
        { 0x0000472Cu, 0x00004730u, 0x00004734u, 0x00006EA0u, 0x00006EA4u, 0x00006EA8u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_d33a9470_48564",
        DxbcIdentity{
            48564,
            { std::byte{ 0xD3 }, std::byte{ 0x3A }, std::byte{ 0x94 }, std::byte{ 0x70 }, std::byte{ 0xD3 }, std::byte{ 0xFD }, std::byte{ 0xEB }, std::byte{ 0x4C }, std::byte{ 0xD6 }, std::byte{ 0xBF }, std::byte{ 0x62 }, std::byte{ 0xAA }, std::byte{ 0xDD }, std::byte{ 0x9E }, std::byte{ 0x52 }, std::byte{ 0x12 } },
        },
        { 0x000008E8u, 0x000008ECu, 0x000008F0u, 0x0000B338u, 0x0000B33Cu, 0x0000B340u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_da51d6a4_8760",
        DxbcIdentity{
            8760,
            { std::byte{ 0xDA }, std::byte{ 0x51 }, std::byte{ 0xD6 }, std::byte{ 0xA4 }, std::byte{ 0xAB }, std::byte{ 0xEB }, std::byte{ 0xCC }, std::byte{ 0x35 }, std::byte{ 0x67 }, std::byte{ 0x74 }, std::byte{ 0x68 }, std::byte{ 0x23 }, std::byte{ 0x03 }, std::byte{ 0x60 }, std::byte{ 0xD1 }, std::byte{ 0xCD } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x000017BCu, 0x000017C0u, 0x000017C4u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_e43a849a_4028",
        DxbcIdentity{
            4028,
            { std::byte{ 0xE4 }, std::byte{ 0x3A }, std::byte{ 0x84 }, std::byte{ 0x9A }, std::byte{ 0xD9 }, std::byte{ 0x1D }, std::byte{ 0x58 }, std::byte{ 0x91 }, std::byte{ 0x0B }, std::byte{ 0x8D }, std::byte{ 0x4B }, std::byte{ 0x8B }, std::byte{ 0xA5 }, std::byte{ 0x9E }, std::byte{ 0x8E }, std::byte{ 0x7B } },
        },
        { 0x0000080Cu, 0x00000810u, 0x00000814u, 0x00000EC8u, 0x00000ECCu, 0x00000ED0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_e73d66f6_9828",
        DxbcIdentity{
            9828,
            { std::byte{ 0xE7 }, std::byte{ 0x3D }, std::byte{ 0x66 }, std::byte{ 0xF6 }, std::byte{ 0x79 }, std::byte{ 0x44 }, std::byte{ 0x2E }, std::byte{ 0xFD }, std::byte{ 0x7E }, std::byte{ 0xD0 }, std::byte{ 0x35 }, std::byte{ 0x19 }, std::byte{ 0xA4 }, std::byte{ 0xA1 }, std::byte{ 0x45 }, std::byte{ 0x33 } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001BE8u, 0x00001BECu, 0x00001BF0u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_e96ff940_48492",
        DxbcIdentity{
            48492,
            { std::byte{ 0xE9 }, std::byte{ 0x6F }, std::byte{ 0xF9 }, std::byte{ 0x40 }, std::byte{ 0x53 }, std::byte{ 0x14 }, std::byte{ 0x12 }, std::byte{ 0x39 }, std::byte{ 0xBE }, std::byte{ 0x53 }, std::byte{ 0x95 }, std::byte{ 0x9D }, std::byte{ 0x4B }, std::byte{ 0xC3 }, std::byte{ 0x5B }, std::byte{ 0x3B } },
        },
        { 0x000008E8u, 0x000008ECu, 0x000008F0u, 0x0000B2F0u, 0x0000B2F4u, 0x0000B2F8u },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_f03e91f1_12260",
        DxbcIdentity{
            12260,
            { std::byte{ 0xF0 }, std::byte{ 0x3E }, std::byte{ 0x91 }, std::byte{ 0xF1 }, std::byte{ 0x2E }, std::byte{ 0x29 }, std::byte{ 0xD3 }, std::byte{ 0x4D }, std::byte{ 0x51 }, std::byte{ 0x65 }, std::byte{ 0x97 }, std::byte{ 0xDB }, std::byte{ 0x0C }, std::byte{ 0xF9 }, std::byte{ 0x49 }, std::byte{ 0x21 } },
        },
        { 0x000008ACu, 0x000008B0u, 0x000008B4u, 0x00002894u, 0x00002898u, 0x0000289Cu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_f442b3e1_7876",
        DxbcIdentity{
            7876,
            { std::byte{ 0xF4 }, std::byte{ 0x42 }, std::byte{ 0xB3 }, std::byte{ 0xE1 }, std::byte{ 0xAE }, std::byte{ 0x23 }, std::byte{ 0xCC }, std::byte{ 0xCD }, std::byte{ 0x4A }, std::byte{ 0x8A }, std::byte{ 0x72 }, std::byte{ 0x27 }, std::byte{ 0xDB }, std::byte{ 0xC8 }, std::byte{ 0x38 }, std::byte{ 0xA9 } },
        },
        { 0x000008ACu, 0x000008B0u, 0x000008B4u, 0x00001774u, 0x00001778u, 0x0000177Cu },
    },
    DFLightAmbientContractDefinition{
        "DFLightAmbient_ff111fbf_8832",
        DxbcIdentity{
            8832,
            { std::byte{ 0xFF }, std::byte{ 0x11 }, std::byte{ 0x1F }, std::byte{ 0xBF }, std::byte{ 0x00 }, std::byte{ 0x30 }, std::byte{ 0x15 }, std::byte{ 0xB7 }, std::byte{ 0x08 }, std::byte{ 0x8A }, std::byte{ 0x37 }, std::byte{ 0x35 }, std::byte{ 0xDF }, std::byte{ 0x14 }, std::byte{ 0xAA }, std::byte{ 0x5C } },
        },
        { 0x000008CCu, 0x000008D0u, 0x000008D4u, 0x00001804u, 0x00001808u, 0x0000180Cu },
    },
}};

static_assert(
    Runtime::kMaximumTrackedOriginalShadersPerContract >=
    6);

constexpr std::array<DFLightAmbientDescriptorContract,
    78> kDFLightAmbientDescriptorContracts{{
    DFLightAmbientDescriptorContract{ 0x00020000u, 6u },
    DFLightAmbientDescriptorContract{ 0x00020080u, 6u },
    DFLightAmbientDescriptorContract{ 0x00020201u, 23u },
    DFLightAmbientDescriptorContract{ 0x00020281u, 23u },
    DFLightAmbientDescriptorContract{ 0x00024201u, 25u },
    DFLightAmbientDescriptorContract{ 0x00024202u, 37u },
    DFLightAmbientDescriptorContract{ 0x00024281u, 25u },
    DFLightAmbientDescriptorContract{ 0x000A0202u, 38u },
    DFLightAmbientDescriptorContract{ 0x000A0282u, 38u },
    DFLightAmbientDescriptorContract{ 0x000A4202u, 13u },
    DFLightAmbientDescriptorContract{ 0x000B0202u, 28u },
    DFLightAmbientDescriptorContract{ 0x000B0282u, 28u },
    DFLightAmbientDescriptorContract{ 0x00120202u, 3u },
    DFLightAmbientDescriptorContract{ 0x00120282u, 3u },
    DFLightAmbientDescriptorContract{ 0x00124202u, 26u },
    DFLightAmbientDescriptorContract{ 0x00130202u, 11u },
    DFLightAmbientDescriptorContract{ 0x00130282u, 11u },
    DFLightAmbientDescriptorContract{ 0x00220202u, 17u },
    DFLightAmbientDescriptorContract{ 0x00220282u, 17u },
    DFLightAmbientDescriptorContract{ 0x00224202u, 16u },
    DFLightAmbientDescriptorContract{ 0x00230202u, 12u },
    DFLightAmbientDescriptorContract{ 0x00230282u, 12u },
    DFLightAmbientDescriptorContract{ 0x00420202u, 9u },
    DFLightAmbientDescriptorContract{ 0x00420282u, 9u },
    DFLightAmbientDescriptorContract{ 0x00424282u, 18u },
    DFLightAmbientDescriptorContract{ 0x00430282u, 24u },
    DFLightAmbientDescriptorContract{ 0x010A0202u, 32u },
    DFLightAmbientDescriptorContract{ 0x010A0282u, 32u },
    DFLightAmbientDescriptorContract{ 0x010B0282u, 28u },
    DFLightAmbientDescriptorContract{ 0x010F0282u, 15u },
    DFLightAmbientDescriptorContract{ 0x01120202u, 4u },
    DFLightAmbientDescriptorContract{ 0x01120282u, 4u },
    DFLightAmbientDescriptorContract{ 0x01124202u, 1u },
    DFLightAmbientDescriptorContract{ 0x01130282u, 11u },
    DFLightAmbientDescriptorContract{ 0x01170282u, 33u },
    DFLightAmbientDescriptorContract{ 0x01220202u, 20u },
    DFLightAmbientDescriptorContract{ 0x01220282u, 20u },
    DFLightAmbientDescriptorContract{ 0x01224202u, 21u },
    DFLightAmbientDescriptorContract{ 0x01230282u, 12u },
    DFLightAmbientDescriptorContract{ 0x01270282u, 19u },
    DFLightAmbientDescriptorContract{ 0x01420202u, 7u },
    DFLightAmbientDescriptorContract{ 0x08020202u, 5u },
    DFLightAmbientDescriptorContract{ 0x080A0202u, 27u },
    DFLightAmbientDescriptorContract{ 0x080A0282u, 27u },
    DFLightAmbientDescriptorContract{ 0x080B0202u, 28u },
    DFLightAmbientDescriptorContract{ 0x080B0282u, 28u },
    DFLightAmbientDescriptorContract{ 0x08120202u, 8u },
    DFLightAmbientDescriptorContract{ 0x08120282u, 8u },
    DFLightAmbientDescriptorContract{ 0x08130202u, 11u },
    DFLightAmbientDescriptorContract{ 0x08130282u, 11u },
    DFLightAmbientDescriptorContract{ 0x08220202u, 30u },
    DFLightAmbientDescriptorContract{ 0x08220282u, 30u },
    DFLightAmbientDescriptorContract{ 0x08230202u, 12u },
    DFLightAmbientDescriptorContract{ 0x08230282u, 12u },
    DFLightAmbientDescriptorContract{ 0x08420202u, 31u },
    DFLightAmbientDescriptorContract{ 0x08420282u, 31u },
    DFLightAmbientDescriptorContract{ 0x08424282u, 22u },
    DFLightAmbientDescriptorContract{ 0x08430282u, 24u },
    DFLightAmbientDescriptorContract{ 0x09020202u, 34u },
    DFLightAmbientDescriptorContract{ 0x090A0202u, 29u },
    DFLightAmbientDescriptorContract{ 0x090A0282u, 29u },
    DFLightAmbientDescriptorContract{ 0x090B0282u, 28u },
    DFLightAmbientDescriptorContract{ 0x090F0282u, 15u },
    DFLightAmbientDescriptorContract{ 0x09120202u, 0u },
    DFLightAmbientDescriptorContract{ 0x09120282u, 0u },
    DFLightAmbientDescriptorContract{ 0x09124202u, 36u },
    DFLightAmbientDescriptorContract{ 0x09130282u, 11u },
    DFLightAmbientDescriptorContract{ 0x09170282u, 33u },
    DFLightAmbientDescriptorContract{ 0x09220202u, 14u },
    DFLightAmbientDescriptorContract{ 0x09220282u, 14u },
    DFLightAmbientDescriptorContract{ 0x09224202u, 10u },
    DFLightAmbientDescriptorContract{ 0x09230282u, 12u },
    DFLightAmbientDescriptorContract{ 0x09270282u, 19u },
    DFLightAmbientDescriptorContract{ 0x09420202u, 35u },
    DFLightAmbientDescriptorContract{ 0x09820202u, 2u },
    DFLightAmbientDescriptorContract{ 0x10020000u, 6u },
    DFLightAmbientDescriptorContract{ 0x10020201u, 23u },
    DFLightAmbientDescriptorContract{ 0x11220202u, 20u },
}};
