// Generated by tools/generate_linear_lighting_runtime_contracts.py.
// Do not edit this file by hand.
constexpr std::array<ShaderContractDefinition, 37> kShaderContracts{ {
    {
        "DefaultProjectedFiveMrt_L4_00008002",
        IDR_LINEAR_LIGHTING_DEFAULT_PROJECTED_PS,
        {
            3052,
            {
                std::byte{ 0xDE }, std::byte{ 0x5B }, std::byte{ 0x08 }, std::byte{ 0xB8 },
                std::byte{ 0xA3 }, std::byte{ 0x77 }, std::byte{ 0x00 }, std::byte{ 0xC6 },
                std::byte{ 0xF0 }, std::byte{ 0xC1 }, std::byte{ 0x29 }, std::byte{ 0x77 },
                std::byte{ 0x9F }, std::byte{ 0x1E }, std::byte{ 0x25 }, std::byte{ 0x70 },
            },
        },
        {
            6184,
            {
                std::byte{ 0x54 }, std::byte{ 0x9A }, std::byte{ 0x49 }, std::byte{ 0xCF },
                std::byte{ 0x9F }, std::byte{ 0xEB }, std::byte{ 0xC2 }, std::byte{ 0x62 },
                std::byte{ 0xC6 }, std::byte{ 0xF4 }, std::byte{ 0x57 }, std::byte{ 0xDB },
                std::byte{ 0x63 }, std::byte{ 0x12 }, std::byte{ 0x91 }, std::byte{ 0x39 },
            },
        },
    },
    {
        "DefaultProjectedFiveMrt_L3_00008003",
        IDR_LINEAR_LIGHTING_DEFAULT_PROJECTED_VERTEX_COLOR_PS,
        {
            3120,
            {
                std::byte{ 0xD6 }, std::byte{ 0xAB }, std::byte{ 0xD2 }, std::byte{ 0x0B },
                std::byte{ 0x46 }, std::byte{ 0xCC }, std::byte{ 0x60 }, std::byte{ 0x9D },
                std::byte{ 0x2B }, std::byte{ 0x64 }, std::byte{ 0xA8 }, std::byte{ 0x8D },
                std::byte{ 0xF0 }, std::byte{ 0x23 }, std::byte{ 0x28 }, std::byte{ 0x3A },
            },
        },
        {
            6252,
            {
                std::byte{ 0x18 }, std::byte{ 0x23 }, std::byte{ 0x54 }, std::byte{ 0x97 },
                std::byte{ 0xE5 }, std::byte{ 0x5E }, std::byte{ 0xC0 }, std::byte{ 0x9A },
                std::byte{ 0x87 }, std::byte{ 0xE4 }, std::byte{ 0x06 }, std::byte{ 0x44 },
                std::byte{ 0x0A }, std::byte{ 0xFF }, std::byte{ 0x9D }, std::byte{ 0xBC },
            },
        },
    },
    {
        "DefaultSixMrt_L4_00000002",
        IDR_LINEAR_LIGHTING_DEFAULT_SIX_MRT_PS,
        {
            3336,
            {
                std::byte{ 0x33 }, std::byte{ 0xFA }, std::byte{ 0x39 }, std::byte{ 0x39 },
                std::byte{ 0x9B }, std::byte{ 0xC7 }, std::byte{ 0x9E }, std::byte{ 0xC9 },
                std::byte{ 0x4B }, std::byte{ 0xD6 }, std::byte{ 0x96 }, std::byte{ 0xE6 },
                std::byte{ 0xE7 }, std::byte{ 0x49 }, std::byte{ 0x0B }, std::byte{ 0x2E },
            },
        },
        {
            6524,
            {
                std::byte{ 0x96 }, std::byte{ 0x49 }, std::byte{ 0x20 }, std::byte{ 0xF9 },
                std::byte{ 0xCA }, std::byte{ 0x8B }, std::byte{ 0x73 }, std::byte{ 0x64 },
                std::byte{ 0x64 }, std::byte{ 0x04 }, std::byte{ 0x5F }, std::byte{ 0xE9 },
                std::byte{ 0xDB }, std::byte{ 0x6A }, std::byte{ 0x6F }, std::byte{ 0x3C },
            },
        },
    },
    {
        "DefaultSixMrt_L3_00000003",
        IDR_LINEAR_LIGHTING_DEFAULT_SIX_MRT_VERTEX_COLOR_PS,
        {
            3404,
            {
                std::byte{ 0xD9 }, std::byte{ 0x23 }, std::byte{ 0x89 }, std::byte{ 0x10 },
                std::byte{ 0xFE }, std::byte{ 0xF1 }, std::byte{ 0xA3 }, std::byte{ 0x9B },
                std::byte{ 0x64 }, std::byte{ 0x83 }, std::byte{ 0x76 }, std::byte{ 0x7F },
                std::byte{ 0x3B }, std::byte{ 0x4F }, std::byte{ 0x36 }, std::byte{ 0x07 },
            },
        },
        {
            6592,
            {
                std::byte{ 0x9E }, std::byte{ 0x4B }, std::byte{ 0xD0 }, std::byte{ 0xB4 },
                std::byte{ 0xEC }, std::byte{ 0xBD }, std::byte{ 0xFA }, std::byte{ 0x6A },
                std::byte{ 0x5E }, std::byte{ 0x5C }, std::byte{ 0x83 }, std::byte{ 0x72 },
                std::byte{ 0x1F }, std::byte{ 0x87 }, std::byte{ 0x24 }, std::byte{ 0x94 },
            },
        },
    },
    {
        "DefaultModelSpaceSixMrt_L4_00000006",
        IDR_LINEAR_LIGHTING_DEFAULT_MODEL_SPACE_SIX_MRT_PS,
        {
            3336,
            {
                std::byte{ 0x2D }, std::byte{ 0xB1 }, std::byte{ 0xCE }, std::byte{ 0xC1 },
                std::byte{ 0x90 }, std::byte{ 0x91 }, std::byte{ 0x30 }, std::byte{ 0xD3 },
                std::byte{ 0x7C }, std::byte{ 0xB4 }, std::byte{ 0xA0 }, std::byte{ 0x82 },
                std::byte{ 0x32 }, std::byte{ 0x40 }, std::byte{ 0x78 }, std::byte{ 0x21 },
            },
        },
        {
            6524,
            {
                std::byte{ 0xF8 }, std::byte{ 0xD3 }, std::byte{ 0x9B }, std::byte{ 0x92 },
                std::byte{ 0x7F }, std::byte{ 0x55 }, std::byte{ 0x69 }, std::byte{ 0x8E },
                std::byte{ 0x44 }, std::byte{ 0xCD }, std::byte{ 0x05 }, std::byte{ 0x95 },
                std::byte{ 0xC3 }, std::byte{ 0xA3 }, std::byte{ 0xE9 }, std::byte{ 0xB6 },
            },
        },
    },
    {
        "DefaultModelSpaceSixMrt_L3_00000007",
        IDR_LINEAR_LIGHTING_DEFAULT_MODEL_SPACE_SIX_MRT_VERTEX_COLOR_PS,
        {
            3404,
            {
                std::byte{ 0xFC }, std::byte{ 0xB8 }, std::byte{ 0x1B }, std::byte{ 0x8C },
                std::byte{ 0xF6 }, std::byte{ 0xE3 }, std::byte{ 0xB2 }, std::byte{ 0x1A },
                std::byte{ 0xF4 }, std::byte{ 0x4F }, std::byte{ 0xBB }, std::byte{ 0xBB },
                std::byte{ 0xC4 }, std::byte{ 0x23 }, std::byte{ 0xA4 }, std::byte{ 0x29 },
            },
        },
        {
            6592,
            {
                std::byte{ 0xE5 }, std::byte{ 0x39 }, std::byte{ 0xAD }, std::byte{ 0xA7 },
                std::byte{ 0x9C }, std::byte{ 0x4D }, std::byte{ 0x39 }, std::byte{ 0x8D },
                std::byte{ 0x54 }, std::byte{ 0xF9 }, std::byte{ 0x4D }, std::byte{ 0xD2 },
                std::byte{ 0x85 }, std::byte{ 0x14 }, std::byte{ 0x36 }, std::byte{ 0xD4 },
            },
        },
    },
    {
        "DefaultDefShadowSixMrt_L4_00004002",
        IDR_LINEAR_LIGHTING_DEFAULT_TEXTURED_EMISSION_SIX_MRT_PS,
        {
            3388,
            {
                std::byte{ 0xAE }, std::byte{ 0xD6 }, std::byte{ 0x70 }, std::byte{ 0xE5 },
                std::byte{ 0x73 }, std::byte{ 0x0D }, std::byte{ 0x65 }, std::byte{ 0x6A },
                std::byte{ 0xC7 }, std::byte{ 0xDC }, std::byte{ 0x56 }, std::byte{ 0xAA },
                std::byte{ 0x30 }, std::byte{ 0x61 }, std::byte{ 0x67 }, std::byte{ 0x19 },
            },
        },
        {
            6828,
            {
                std::byte{ 0x06 }, std::byte{ 0x66 }, std::byte{ 0xAA }, std::byte{ 0xC8 },
                std::byte{ 0xD5 }, std::byte{ 0x78 }, std::byte{ 0x91 }, std::byte{ 0xBE },
                std::byte{ 0x00 }, std::byte{ 0xEB }, std::byte{ 0x76 }, std::byte{ 0x53 },
                std::byte{ 0xD2 }, std::byte{ 0x29 }, std::byte{ 0x75 }, std::byte{ 0x97 },
            },
        },
    },
    {
        "DefaultDefShadowSixMrt_L3_00004003",
        IDR_LINEAR_LIGHTING_DEFAULT_TEXTURED_EMISSION_SIX_MRT_VERTEX_COLOR_PS,
        {
            3456,
            {
                std::byte{ 0x09 }, std::byte{ 0xC3 }, std::byte{ 0x95 }, std::byte{ 0x9B },
                std::byte{ 0xF0 }, std::byte{ 0x9D }, std::byte{ 0x71 }, std::byte{ 0xBF },
                std::byte{ 0x9B }, std::byte{ 0x8C }, std::byte{ 0x9B }, std::byte{ 0x27 },
                std::byte{ 0xF8 }, std::byte{ 0x97 }, std::byte{ 0xF7 }, std::byte{ 0xAC },
            },
        },
        {
            6896,
            {
                std::byte{ 0x83 }, std::byte{ 0xB6 }, std::byte{ 0xC9 }, std::byte{ 0x83 },
                std::byte{ 0xF3 }, std::byte{ 0x42 }, std::byte{ 0x7E }, std::byte{ 0xFD },
                std::byte{ 0xF9 }, std::byte{ 0xD2 }, std::byte{ 0x0E }, std::byte{ 0x1D },
                std::byte{ 0x7C }, std::byte{ 0xCD }, std::byte{ 0x69 }, std::byte{ 0x51 },
            },
        },
    },
    {
        "EnvmapSixMrt_L4_00000102",
        IDR_LINEAR_LIGHTING_ENVMAP_SIX_MRT_PS,
        {
            3384,
            {
                std::byte{ 0xFA }, std::byte{ 0xDE }, std::byte{ 0xDF }, std::byte{ 0x63 },
                std::byte{ 0xB6 }, std::byte{ 0xB5 }, std::byte{ 0x6F }, std::byte{ 0x34 },
                std::byte{ 0x39 }, std::byte{ 0xC3 }, std::byte{ 0xF6 }, std::byte{ 0x9F },
                std::byte{ 0x4E }, std::byte{ 0x8B }, std::byte{ 0xFC }, std::byte{ 0x48 },
            },
        },
        {
            6572,
            {
                std::byte{ 0x43 }, std::byte{ 0xE5 }, std::byte{ 0xF4 }, std::byte{ 0xCA },
                std::byte{ 0x3D }, std::byte{ 0xC8 }, std::byte{ 0xA2 }, std::byte{ 0xD6 },
                std::byte{ 0xE6 }, std::byte{ 0x0E }, std::byte{ 0x21 }, std::byte{ 0xFA },
                std::byte{ 0x53 }, std::byte{ 0xBD }, std::byte{ 0x81 }, std::byte{ 0xD4 },
            },
        },
    },
    {
        "EnvmapSixMrt_L3_00000103",
        IDR_LINEAR_LIGHTING_ENVMAP_SIX_MRT_VERTEX_COLOR_PS,
        {
            3460,
            {
                std::byte{ 0x82 }, std::byte{ 0x1A }, std::byte{ 0x19 }, std::byte{ 0xB1 },
                std::byte{ 0x4B }, std::byte{ 0x47 }, std::byte{ 0x6A }, std::byte{ 0xB6 },
                std::byte{ 0x7D }, std::byte{ 0x16 }, std::byte{ 0x0E }, std::byte{ 0x6B },
                std::byte{ 0x2F }, std::byte{ 0xD0 }, std::byte{ 0x63 }, std::byte{ 0x61 },
            },
        },
        {
            6648,
            {
                std::byte{ 0x41 }, std::byte{ 0xF7 }, std::byte{ 0xEC }, std::byte{ 0x34 },
                std::byte{ 0x65 }, std::byte{ 0x82 }, std::byte{ 0x05 }, std::byte{ 0x1C },
                std::byte{ 0x7A }, std::byte{ 0xFA }, std::byte{ 0x38 }, std::byte{ 0x18 },
                std::byte{ 0xE4 }, std::byte{ 0x56 }, std::byte{ 0x7C }, std::byte{ 0x52 },
            },
        },
    },
    {
        "EnvmapModelSpaceSixMrt_L4_00000106",
        IDR_LINEAR_LIGHTING_ENVMAP_MODEL_SPACE_SIX_MRT_PS,
        {
            3384,
            {
                std::byte{ 0x97 }, std::byte{ 0xD5 }, std::byte{ 0x8F }, std::byte{ 0xEA },
                std::byte{ 0xE0 }, std::byte{ 0x52 }, std::byte{ 0xD6 }, std::byte{ 0xEE },
                std::byte{ 0x17 }, std::byte{ 0x64 }, std::byte{ 0x03 }, std::byte{ 0x46 },
                std::byte{ 0x1D }, std::byte{ 0x7D }, std::byte{ 0x2B }, std::byte{ 0x2A },
            },
        },
        {
            6572,
            {
                std::byte{ 0xA4 }, std::byte{ 0x27 }, std::byte{ 0x81 }, std::byte{ 0x77 },
                std::byte{ 0x94 }, std::byte{ 0x3A }, std::byte{ 0xB6 }, std::byte{ 0xAC },
                std::byte{ 0x30 }, std::byte{ 0x95 }, std::byte{ 0xEF }, std::byte{ 0x0E },
                std::byte{ 0x90 }, std::byte{ 0xA1 }, std::byte{ 0xD9 }, std::byte{ 0x3B },
            },
        },
    },
    {
        "EnvmapModelSpaceSixMrt_L3_00000107",
        IDR_LINEAR_LIGHTING_ENVMAP_MODEL_SPACE_SIX_MRT_VERTEX_COLOR_PS,
        {
            3460,
            {
                std::byte{ 0x14 }, std::byte{ 0xA9 }, std::byte{ 0x15 }, std::byte{ 0x89 },
                std::byte{ 0x27 }, std::byte{ 0xB3 }, std::byte{ 0x07 }, std::byte{ 0xF9 },
                std::byte{ 0x7F }, std::byte{ 0x52 }, std::byte{ 0x41 }, std::byte{ 0xB8 },
                std::byte{ 0x8A }, std::byte{ 0x93 }, std::byte{ 0x6B }, std::byte{ 0xCD },
            },
        },
        {
            6648,
            {
                std::byte{ 0xE7 }, std::byte{ 0xCF }, std::byte{ 0xB0 }, std::byte{ 0x5C },
                std::byte{ 0xCF }, std::byte{ 0x85 }, std::byte{ 0xED }, std::byte{ 0x02 },
                std::byte{ 0xBB }, std::byte{ 0xE7 }, std::byte{ 0xE4 }, std::byte{ 0x3C },
                std::byte{ 0x73 }, std::byte{ 0x7A }, std::byte{ 0x50 }, std::byte{ 0xE1 },
            },
        },
    },
    {
        "EnvmapProjectedFiveMrt_L4_00008102",
        IDR_LINEAR_LIGHTING_ENVMAP_PROJECTED_FIVE_MRT_PS,
        {
            3100,
            {
                std::byte{ 0x62 }, std::byte{ 0x2B }, std::byte{ 0xB9 }, std::byte{ 0x29 },
                std::byte{ 0x10 }, std::byte{ 0xE7 }, std::byte{ 0xCA }, std::byte{ 0x5F },
                std::byte{ 0x3B }, std::byte{ 0x6E }, std::byte{ 0xEB }, std::byte{ 0x36 },
                std::byte{ 0x0C }, std::byte{ 0xA3 }, std::byte{ 0x5E }, std::byte{ 0xE3 },
            },
        },
        {
            6232,
            {
                std::byte{ 0x94 }, std::byte{ 0x8E }, std::byte{ 0xDF }, std::byte{ 0x6C },
                std::byte{ 0x10 }, std::byte{ 0xDB }, std::byte{ 0xCC }, std::byte{ 0xFC },
                std::byte{ 0xA7 }, std::byte{ 0x73 }, std::byte{ 0x78 }, std::byte{ 0xAF },
                std::byte{ 0xC7 }, std::byte{ 0x38 }, std::byte{ 0xBC }, std::byte{ 0xBF },
            },
        },
    },
    {
        "EnvmapProjectedFiveMrt_L3_00008103",
        IDR_LINEAR_LIGHTING_ENVMAP_PROJECTED_FIVE_MRT_VERTEX_COLOR_PS,
        {
            3176,
            {
                std::byte{ 0x23 }, std::byte{ 0x77 }, std::byte{ 0x66 }, std::byte{ 0x02 },
                std::byte{ 0x03 }, std::byte{ 0x7D }, std::byte{ 0xE9 }, std::byte{ 0xC2 },
                std::byte{ 0xAD }, std::byte{ 0x19 }, std::byte{ 0xD8 }, std::byte{ 0x7F },
                std::byte{ 0x83 }, std::byte{ 0x7D }, std::byte{ 0x8E }, std::byte{ 0x84 },
            },
        },
        {
            6308,
            {
                std::byte{ 0xE8 }, std::byte{ 0xE8 }, std::byte{ 0x51 }, std::byte{ 0x86 },
                std::byte{ 0x39 }, std::byte{ 0x02 }, std::byte{ 0x0C }, std::byte{ 0xE6 },
                std::byte{ 0x71 }, std::byte{ 0x8C }, std::byte{ 0x71 }, std::byte{ 0x40 },
                std::byte{ 0x3E }, std::byte{ 0x8F }, std::byte{ 0xB4 }, std::byte{ 0x89 },
            },
        },
    },
    {
        "EnvmapProjectedFiveMrt_L4_00008106",
        IDR_LINEAR_LIGHTING_ENVMAP_PROJECTED_FIVE_MRT_NO_EARLY_DEPTH_PS,
        {
            3100,
            {
                std::byte{ 0x6B }, std::byte{ 0xDE }, std::byte{ 0x08 }, std::byte{ 0xEE },
                std::byte{ 0x37 }, std::byte{ 0x9F }, std::byte{ 0x54 }, std::byte{ 0x3D },
                std::byte{ 0x1F }, std::byte{ 0x16 }, std::byte{ 0xC1 }, std::byte{ 0x70 },
                std::byte{ 0xE7 }, std::byte{ 0xE4 }, std::byte{ 0x2C }, std::byte{ 0xC3 },
            },
        },
        {
            6232,
            {
                std::byte{ 0x34 }, std::byte{ 0xBD }, std::byte{ 0x69 }, std::byte{ 0xE4 },
                std::byte{ 0x9B }, std::byte{ 0x84 }, std::byte{ 0x2F }, std::byte{ 0xE2 },
                std::byte{ 0xC9 }, std::byte{ 0xCD }, std::byte{ 0x27 }, std::byte{ 0xEF },
                std::byte{ 0xF6 }, std::byte{ 0x32 }, std::byte{ 0x88 }, std::byte{ 0x8F },
            },
        },
    },
    {
        "TexturedEmissionAlphaTestSixMrt_L4_00004102",
        IDR_LINEAR_LIGHTING_TEXTURED_EMISSION_ALPHA_TEST_SIX_MRT_PS,
        {
            3464,
            {
                std::byte{ 0x17 }, std::byte{ 0xD4 }, std::byte{ 0x08 }, std::byte{ 0xB7 },
                std::byte{ 0xDE }, std::byte{ 0xEB }, std::byte{ 0x31 }, std::byte{ 0x28 },
                std::byte{ 0xB0 }, std::byte{ 0xF7 }, std::byte{ 0xFD }, std::byte{ 0x7A },
                std::byte{ 0x7B }, std::byte{ 0xA3 }, std::byte{ 0xE1 }, std::byte{ 0x95 },
            },
        },
        {
            6904,
            {
                std::byte{ 0x1C }, std::byte{ 0x86 }, std::byte{ 0xBA }, std::byte{ 0x63 },
                std::byte{ 0xBC }, std::byte{ 0xA0 }, std::byte{ 0x87 }, std::byte{ 0x4B },
                std::byte{ 0x4E }, std::byte{ 0xFC }, std::byte{ 0x0D }, std::byte{ 0xEE },
                std::byte{ 0x42 }, std::byte{ 0x39 }, std::byte{ 0xEA }, std::byte{ 0x78 },
            },
        },
    },
    {
        "TexturedEmissionAlphaTestSixMrt_L3_00004103",
        IDR_LINEAR_LIGHTING_TEXTURED_EMISSION_ALPHA_TEST_SIX_MRT_VERTEX_COLOR_PS,
        {
            3540,
            {
                std::byte{ 0xB3 }, std::byte{ 0xCE }, std::byte{ 0x48 }, std::byte{ 0xD5 },
                std::byte{ 0x43 }, std::byte{ 0x81 }, std::byte{ 0x71 }, std::byte{ 0x69 },
                std::byte{ 0x2D }, std::byte{ 0xE2 }, std::byte{ 0x57 }, std::byte{ 0xA5 },
                std::byte{ 0xEB }, std::byte{ 0x1C }, std::byte{ 0x3D }, std::byte{ 0x94 },
            },
        },
        {
            6980,
            {
                std::byte{ 0xA7 }, std::byte{ 0x2F }, std::byte{ 0x30 }, std::byte{ 0x95 },
                std::byte{ 0xE7 }, std::byte{ 0x7B }, std::byte{ 0x19 }, std::byte{ 0x16 },
                std::byte{ 0xDC }, std::byte{ 0x8B }, std::byte{ 0xAC }, std::byte{ 0x42 },
                std::byte{ 0x66 }, std::byte{ 0x39 }, std::byte{ 0xFC }, std::byte{ 0x3F },
            },
        },
    },
    {
        "EnvmapModelSpaceSixMrt_RgbOnlyAlphaTest_54F53016",
        IDR_LINEAR_LIGHTING_ENVMAP_MODEL_SPACE_RGB_ONLY_ALPHA_TEST_PS,
        {
            3452,
            {
                std::byte{ 0x54 }, std::byte{ 0xF5 }, std::byte{ 0x30 }, std::byte{ 0x16 },
                std::byte{ 0xEB }, std::byte{ 0x2D }, std::byte{ 0xA3 }, std::byte{ 0x6E },
                std::byte{ 0xEA }, std::byte{ 0x5F }, std::byte{ 0x5A }, std::byte{ 0xC3 },
                std::byte{ 0xBF }, std::byte{ 0x10 }, std::byte{ 0xED }, std::byte{ 0x7B },
            },
        },
        {
            6640,
            {
                std::byte{ 0xF1 }, std::byte{ 0x25 }, std::byte{ 0xEE }, std::byte{ 0xDA },
                std::byte{ 0x79 }, std::byte{ 0x35 }, std::byte{ 0x6A }, std::byte{ 0xD6 },
                std::byte{ 0x19 }, std::byte{ 0x51 }, std::byte{ 0xBF }, std::byte{ 0x56 },
                std::byte{ 0xD8 }, std::byte{ 0x6C }, std::byte{ 0x1D }, std::byte{ 0x57 },
            },
        },
    },
    {
        "EnvmapProjectedFiveMrt_RgbOnlyAlphaTest_5A5E1AD5",
        IDR_LINEAR_LIGHTING_ENVMAP_PROJECTED_RGB_ONLY_ALPHA_TEST_PS,
        {
            3168,
            {
                std::byte{ 0x5A }, std::byte{ 0x5E }, std::byte{ 0x1A }, std::byte{ 0xD5 },
                std::byte{ 0xAF }, std::byte{ 0xE0 }, std::byte{ 0x49 }, std::byte{ 0xC3 },
                std::byte{ 0x02 }, std::byte{ 0x08 }, std::byte{ 0x9B }, std::byte{ 0x9A },
                std::byte{ 0xBB }, std::byte{ 0xC4 }, std::byte{ 0x68 }, std::byte{ 0xB8 },
            },
        },
        {
            6300,
            {
                std::byte{ 0x1F }, std::byte{ 0x1D }, std::byte{ 0xE1 }, std::byte{ 0xB5 },
                std::byte{ 0xBC }, std::byte{ 0x34 }, std::byte{ 0x40 }, std::byte{ 0x5C },
                std::byte{ 0xCA }, std::byte{ 0x51 }, std::byte{ 0xDB }, std::byte{ 0xF0 },
                std::byte{ 0xAD }, std::byte{ 0x29 }, std::byte{ 0x60 }, std::byte{ 0x2E },
            },
        },
    },
    {
        "EnvmapProjectedFiveMrt_VertexColorNoEarlyDepth_B4D2FE98",
        IDR_LINEAR_LIGHTING_ENVMAP_PROJECTED_VERTEX_COLOR_NO_EARLY_DEPTH_PS,
        {
            3176,
            {
                std::byte{ 0xB4 }, std::byte{ 0xD2 }, std::byte{ 0xFE }, std::byte{ 0x98 },
                std::byte{ 0x85 }, std::byte{ 0x1F }, std::byte{ 0x17 }, std::byte{ 0xEC },
                std::byte{ 0xB6 }, std::byte{ 0x36 }, std::byte{ 0xC2 }, std::byte{ 0x9B },
                std::byte{ 0xCF }, std::byte{ 0x7E }, std::byte{ 0x3A }, std::byte{ 0x13 },
            },
        },
        {
            6308,
            {
                std::byte{ 0x37 }, std::byte{ 0x20 }, std::byte{ 0x96 }, std::byte{ 0xAE },
                std::byte{ 0x99 }, std::byte{ 0xF8 }, std::byte{ 0x32 }, std::byte{ 0x62 },
                std::byte{ 0x37 }, std::byte{ 0x2D }, std::byte{ 0x8B }, std::byte{ 0x89 },
                std::byte{ 0x31 }, std::byte{ 0x27 }, std::byte{ 0x85 }, std::byte{ 0x1A },
            },
        },
    },
    {
        "DefaultProjectedFiveMrt_L4NoEarlyDepth_15E29A6C",
        IDR_LINEAR_LIGHTING_DEFAULT_PROJECTED_NO_EARLY_DEPTH_PS,
        {
            3052,
            {
                std::byte{ 0x15 }, std::byte{ 0xE2 }, std::byte{ 0x9A }, std::byte{ 0x6C },
                std::byte{ 0x23 }, std::byte{ 0x36 }, std::byte{ 0xBA }, std::byte{ 0xEC },
                std::byte{ 0x93 }, std::byte{ 0x01 }, std::byte{ 0x94 }, std::byte{ 0xE8 },
                std::byte{ 0x73 }, std::byte{ 0x80 }, std::byte{ 0xAE }, std::byte{ 0xFE },
            },
        },
        {
            6184,
            {
                std::byte{ 0x32 }, std::byte{ 0xC4 }, std::byte{ 0x27 }, std::byte{ 0x5F },
                std::byte{ 0xBE }, std::byte{ 0x7F }, std::byte{ 0x98 }, std::byte{ 0x25 },
                std::byte{ 0xF8 }, std::byte{ 0x8D }, std::byte{ 0x67 }, std::byte{ 0x3B },
                std::byte{ 0x73 }, std::byte{ 0xD2 }, std::byte{ 0xC5 }, std::byte{ 0xF9 },
            },
        },
    },
    {
        "DefaultProjectedFiveMrt_L3NoEarlyDepth_B80CA12A",
        IDR_LINEAR_LIGHTING_DEFAULT_PROJECTED_VERTEX_COLOR_NO_EARLY_DEPTH_PS,
        {
            3120,
            {
                std::byte{ 0xB8 }, std::byte{ 0x0C }, std::byte{ 0xA1 }, std::byte{ 0x2A },
                std::byte{ 0x39 }, std::byte{ 0x15 }, std::byte{ 0xE1 }, std::byte{ 0x03 },
                std::byte{ 0x08 }, std::byte{ 0x23 }, std::byte{ 0x73 }, std::byte{ 0xD0 },
                std::byte{ 0xF9 }, std::byte{ 0x7D }, std::byte{ 0x50 }, std::byte{ 0x87 },
            },
        },
        {
            6252,
            {
                std::byte{ 0x09 }, std::byte{ 0xAF }, std::byte{ 0xBC }, std::byte{ 0x4C },
                std::byte{ 0xD5 }, std::byte{ 0x5A }, std::byte{ 0x3B }, std::byte{ 0xBD },
                std::byte{ 0xB8 }, std::byte{ 0x3B }, std::byte{ 0x9F }, std::byte{ 0x61 },
                std::byte{ 0x8F }, std::byte{ 0x35 }, std::byte{ 0x1C }, std::byte{ 0xFB },
            },
        },
    },
    {
        "GlowmapSixMrt_L4NoEarlyDepth_00004006",
        IDR_LINEAR_LIGHTING_GLOWMAP_SIX_MRT_NO_EARLY_DEPTH_PS,
        {
            3388,
            {
                std::byte{ 0x80 }, std::byte{ 0xF8 }, std::byte{ 0xF2 }, std::byte{ 0xA4 },
                std::byte{ 0x46 }, std::byte{ 0xD7 }, std::byte{ 0x18 }, std::byte{ 0xE1 },
                std::byte{ 0x01 }, std::byte{ 0x81 }, std::byte{ 0xBB }, std::byte{ 0xA8 },
                std::byte{ 0xC8 }, std::byte{ 0x6E }, std::byte{ 0xA2 }, std::byte{ 0x5E },
            },
        },
        {
            6828,
            {
                std::byte{ 0x68 }, std::byte{ 0xB8 }, std::byte{ 0xFC }, std::byte{ 0x98 },
                std::byte{ 0x10 }, std::byte{ 0xE8 }, std::byte{ 0x67 }, std::byte{ 0x89 },
                std::byte{ 0x12 }, std::byte{ 0x32 }, std::byte{ 0xFB }, std::byte{ 0xF9 },
                std::byte{ 0xE8 }, std::byte{ 0x9B }, std::byte{ 0xDD }, std::byte{ 0x32 },
            },
        },
    },
    {
        "GlowmapSixMrt_L3NoEarlyDepth_00004007",
        IDR_LINEAR_LIGHTING_GLOWMAP_SIX_MRT_VERTEX_COLOR_NO_EARLY_DEPTH_PS,
        {
            3456,
            {
                std::byte{ 0x08 }, std::byte{ 0x3F }, std::byte{ 0xC9 }, std::byte{ 0x97 },
                std::byte{ 0x6C }, std::byte{ 0xC5 }, std::byte{ 0x44 }, std::byte{ 0x89 },
                std::byte{ 0x05 }, std::byte{ 0x3F }, std::byte{ 0xA3 }, std::byte{ 0x9E },
                std::byte{ 0x84 }, std::byte{ 0x93 }, std::byte{ 0x07 }, std::byte{ 0xE2 },
            },
        },
        {
            6896,
            {
                std::byte{ 0x60 }, std::byte{ 0xF6 }, std::byte{ 0x64 }, std::byte{ 0x91 },
                std::byte{ 0xC7 }, std::byte{ 0x92 }, std::byte{ 0xB4 }, std::byte{ 0xAE },
                std::byte{ 0xAA }, std::byte{ 0xE6 }, std::byte{ 0x40 }, std::byte{ 0xCE },
                std::byte{ 0xE9 }, std::byte{ 0x86 }, std::byte{ 0xEA }, std::byte{ 0x8E },
            },
        },
    },
    {
        "GlowmapAlphaTestSixMrt_L4NoEarlyDepth_00004106",
        IDR_LINEAR_LIGHTING_GLOWMAP_ALPHA_TEST_SIX_MRT_NO_EARLY_DEPTH_PS,
        {
            3464,
            {
                std::byte{ 0x99 }, std::byte{ 0x8C }, std::byte{ 0x9A }, std::byte{ 0xA8 },
                std::byte{ 0x7F }, std::byte{ 0xEF }, std::byte{ 0xD4 }, std::byte{ 0x75 },
                std::byte{ 0x32 }, std::byte{ 0x4D }, std::byte{ 0x9A }, std::byte{ 0x61 },
                std::byte{ 0x69 }, std::byte{ 0x01 }, std::byte{ 0x48 }, std::byte{ 0xB0 },
            },
        },
        {
            6904,
            {
                std::byte{ 0xCF }, std::byte{ 0x35 }, std::byte{ 0x2E }, std::byte{ 0x08 },
                std::byte{ 0xFA }, std::byte{ 0x01 }, std::byte{ 0x71 }, std::byte{ 0x4A },
                std::byte{ 0xA3 }, std::byte{ 0xEC }, std::byte{ 0x7D }, std::byte{ 0x82 },
                std::byte{ 0xFE }, std::byte{ 0x81 }, std::byte{ 0x68 }, std::byte{ 0xBF },
            },
        },
    },
    {
        "GlowmapAlphaTestSixMrt_L3NoEarlyDepth_00004107",
        IDR_LINEAR_LIGHTING_GLOWMAP_ALPHA_TEST_SIX_MRT_VERTEX_COLOR_NO_EARLY_DEPTH_PS,
        {
            3540,
            {
                std::byte{ 0x8A }, std::byte{ 0xA4 }, std::byte{ 0x3A }, std::byte{ 0x95 },
                std::byte{ 0xDE }, std::byte{ 0xCF }, std::byte{ 0x86 }, std::byte{ 0x87 },
                std::byte{ 0x73 }, std::byte{ 0xFB }, std::byte{ 0x95 }, std::byte{ 0x2B },
                std::byte{ 0x3B }, std::byte{ 0x37 }, std::byte{ 0xF2 }, std::byte{ 0x3F },
            },
        },
        {
            6980,
            {
                std::byte{ 0x2F }, std::byte{ 0xBE }, std::byte{ 0x87 }, std::byte{ 0xDA },
                std::byte{ 0x0D }, std::byte{ 0x70 }, std::byte{ 0x1B }, std::byte{ 0x92 },
                std::byte{ 0x64 }, std::byte{ 0x27 }, std::byte{ 0x7A }, std::byte{ 0xFD },
                std::byte{ 0x9D }, std::byte{ 0x86 }, std::byte{ 0x12 }, std::byte{ 0x6E },
            },
        },
    },
    {
        "GlowmapBlendFiveMrt_L4_0000C002",
        IDR_LINEAR_LIGHTING_GLOWMAP_BLEND_FIVE_MRT_PS,
        {
            3104,
            {
                std::byte{ 0x5D }, std::byte{ 0xBF }, std::byte{ 0xB6 }, std::byte{ 0x97 },
                std::byte{ 0x00 }, std::byte{ 0x4A }, std::byte{ 0x35 }, std::byte{ 0x30 },
                std::byte{ 0xE6 }, std::byte{ 0xC0 }, std::byte{ 0x9E }, std::byte{ 0xC0 },
                std::byte{ 0x2B }, std::byte{ 0x38 }, std::byte{ 0x72 }, std::byte{ 0x1B },
            },
        },
        {
            6488,
            {
                std::byte{ 0xAD }, std::byte{ 0xDF }, std::byte{ 0x92 }, std::byte{ 0x9E },
                std::byte{ 0xAD }, std::byte{ 0x04 }, std::byte{ 0x68 }, std::byte{ 0x7E },
                std::byte{ 0x54 }, std::byte{ 0x8E }, std::byte{ 0xD3 }, std::byte{ 0x42 },
                std::byte{ 0x80 }, std::byte{ 0x6F }, std::byte{ 0x34 }, std::byte{ 0xD0 },
            },
        },
    },
    {
        "GlowmapBlendFiveMrt_L3_0000C003",
        IDR_LINEAR_LIGHTING_GLOWMAP_BLEND_FIVE_MRT_VERTEX_COLOR_PS,
        {
            3172,
            {
                std::byte{ 0x7B }, std::byte{ 0x0C }, std::byte{ 0x4B }, std::byte{ 0xE1 },
                std::byte{ 0x3F }, std::byte{ 0x64 }, std::byte{ 0x45 }, std::byte{ 0xCA },
                std::byte{ 0xEE }, std::byte{ 0xFC }, std::byte{ 0x27 }, std::byte{ 0xB9 },
                std::byte{ 0x60 }, std::byte{ 0x40 }, std::byte{ 0xEB }, std::byte{ 0x4F },
            },
        },
        {
            6556,
            {
                std::byte{ 0x1C }, std::byte{ 0x9B }, std::byte{ 0xFA }, std::byte{ 0x31 },
                std::byte{ 0x5D }, std::byte{ 0x53 }, std::byte{ 0x50 }, std::byte{ 0x54 },
                std::byte{ 0x19 }, std::byte{ 0x15 }, std::byte{ 0xAD }, std::byte{ 0x96 },
                std::byte{ 0x62 }, std::byte{ 0x62 }, std::byte{ 0xFC }, std::byte{ 0xAF },
            },
        },
    },
    {
        "GlowmapBlendFiveMrt_L4NoEarlyDepth_0000C006",
        IDR_LINEAR_LIGHTING_GLOWMAP_BLEND_FIVE_MRT_NO_EARLY_DEPTH_PS,
        {
            3104,
            {
                std::byte{ 0xE4 }, std::byte{ 0xD7 }, std::byte{ 0xF5 }, std::byte{ 0x4E },
                std::byte{ 0x7D }, std::byte{ 0xC8 }, std::byte{ 0x6C }, std::byte{ 0xCF },
                std::byte{ 0x1E }, std::byte{ 0x85 }, std::byte{ 0xFB }, std::byte{ 0x9D },
                std::byte{ 0xDA }, std::byte{ 0x07 }, std::byte{ 0x77 }, std::byte{ 0x40 },
            },
        },
        {
            6488,
            {
                std::byte{ 0xEE }, std::byte{ 0x80 }, std::byte{ 0x30 }, std::byte{ 0xE0 },
                std::byte{ 0x02 }, std::byte{ 0x41 }, std::byte{ 0xC1 }, std::byte{ 0xC1 },
                std::byte{ 0xC6 }, std::byte{ 0xC5 }, std::byte{ 0x5E }, std::byte{ 0x23 },
                std::byte{ 0x7D }, std::byte{ 0x6F }, std::byte{ 0x20 }, std::byte{ 0xDF },
            },
        },
    },
    {
        "GlowmapBlendFiveMrt_L3NoEarlyDepth_0000C007",
        IDR_LINEAR_LIGHTING_GLOWMAP_BLEND_FIVE_MRT_VERTEX_COLOR_NO_EARLY_DEPTH_PS,
        {
            3172,
            {
                std::byte{ 0x0C }, std::byte{ 0x86 }, std::byte{ 0x79 }, std::byte{ 0x31 },
                std::byte{ 0x00 }, std::byte{ 0xEB }, std::byte{ 0xD6 }, std::byte{ 0x70 },
                std::byte{ 0x21 }, std::byte{ 0x2D }, std::byte{ 0xE2 }, std::byte{ 0x47 },
                std::byte{ 0x8E }, std::byte{ 0x6A }, std::byte{ 0x9C }, std::byte{ 0x58 },
            },
        },
        {
            6556,
            {
                std::byte{ 0xD3 }, std::byte{ 0x10 }, std::byte{ 0x53 }, std::byte{ 0xF1 },
                std::byte{ 0xEE }, std::byte{ 0x6D }, std::byte{ 0x56 }, std::byte{ 0x6F },
                std::byte{ 0x36 }, std::byte{ 0x67 }, std::byte{ 0x83 }, std::byte{ 0x60 },
                std::byte{ 0x59 }, std::byte{ 0xE0 }, std::byte{ 0x74 }, std::byte{ 0xF9 },
            },
        },
    },
    {
        "GlowmapAlphaTestBlendFiveMrt_L4_0000C102",
        IDR_LINEAR_LIGHTING_GLOWMAP_ALPHA_TEST_BLEND_FIVE_MRT_PS,
        {
            3208,
            {
                std::byte{ 0x9A }, std::byte{ 0x42 }, std::byte{ 0x47 }, std::byte{ 0x8E },
                std::byte{ 0xF4 }, std::byte{ 0x46 }, std::byte{ 0x72 }, std::byte{ 0xE4 },
                std::byte{ 0x34 }, std::byte{ 0x94 }, std::byte{ 0x28 }, std::byte{ 0x13 },
                std::byte{ 0xDB }, std::byte{ 0xC2 }, std::byte{ 0x3E }, std::byte{ 0x99 },
            },
        },
        {
            6564,
            {
                std::byte{ 0x55 }, std::byte{ 0x6E }, std::byte{ 0x53 }, std::byte{ 0x87 },
                std::byte{ 0xF1 }, std::byte{ 0x17 }, std::byte{ 0xB2 }, std::byte{ 0x21 },
                std::byte{ 0x99 }, std::byte{ 0x65 }, std::byte{ 0x2F }, std::byte{ 0x2C },
                std::byte{ 0x90 }, std::byte{ 0x04 }, std::byte{ 0xB6 }, std::byte{ 0x81 },
            },
        },
    },
    {
        "GlowmapAlphaTestBlendFiveMrt_L3_0000C103",
        IDR_LINEAR_LIGHTING_GLOWMAP_ALPHA_TEST_BLEND_FIVE_MRT_VERTEX_COLOR_PS,
        {
            3284,
            {
                std::byte{ 0x7F }, std::byte{ 0x58 }, std::byte{ 0xFF }, std::byte{ 0x38 },
                std::byte{ 0x02 }, std::byte{ 0xDF }, std::byte{ 0x3E }, std::byte{ 0x9E },
                std::byte{ 0xCF }, std::byte{ 0xB8 }, std::byte{ 0x73 }, std::byte{ 0x59 },
                std::byte{ 0x9B }, std::byte{ 0xA6 }, std::byte{ 0xC0 }, std::byte{ 0x2F },
            },
        },
        {
            6640,
            {
                std::byte{ 0x71 }, std::byte{ 0xC3 }, std::byte{ 0xE3 }, std::byte{ 0xAB },
                std::byte{ 0x8D }, std::byte{ 0xF6 }, std::byte{ 0x8A }, std::byte{ 0xB6 },
                std::byte{ 0x58 }, std::byte{ 0x68 }, std::byte{ 0xAB }, std::byte{ 0x06 },
                std::byte{ 0x29 }, std::byte{ 0xC8 }, std::byte{ 0x67 }, std::byte{ 0xE6 },
            },
        },
    },
    {
        "InstancedSixMrt_L4_08000002",
        IDR_LINEAR_LIGHTING_INSTANCED_SIX_MRT_PS,
        {
            3272,
            {
                std::byte{ 0xC5 }, std::byte{ 0x21 }, std::byte{ 0xA6 }, std::byte{ 0x7E },
                std::byte{ 0x8A }, std::byte{ 0xAB }, std::byte{ 0x04 }, std::byte{ 0x56 },
                std::byte{ 0xC4 }, std::byte{ 0x6A }, std::byte{ 0xFD }, std::byte{ 0x19 },
                std::byte{ 0x96 }, std::byte{ 0x70 }, std::byte{ 0xB2 }, std::byte{ 0xAE },
            },
        },
        {
            6624,
            {
                std::byte{ 0xDD }, std::byte{ 0x40 }, std::byte{ 0x66 }, std::byte{ 0xD0 },
                std::byte{ 0x9C }, std::byte{ 0x94 }, std::byte{ 0x9D }, std::byte{ 0x0C },
                std::byte{ 0x0D }, std::byte{ 0xB4 }, std::byte{ 0x0B }, std::byte{ 0x52 },
                std::byte{ 0xD0 }, std::byte{ 0xD5 }, std::byte{ 0xD7 }, std::byte{ 0x2B },
            },
        },
    },
    {
        "InstancedSixMrt_L3_08000003",
        IDR_LINEAR_LIGHTING_INSTANCED_SIX_MRT_VERTEX_COLOR_PS,
        {
            3336,
            {
                std::byte{ 0xB1 }, std::byte{ 0x33 }, std::byte{ 0x41 }, std::byte{ 0x2C },
                std::byte{ 0xE3 }, std::byte{ 0x31 }, std::byte{ 0xAD }, std::byte{ 0x7F },
                std::byte{ 0xE1 }, std::byte{ 0x1A }, std::byte{ 0x69 }, std::byte{ 0x05 },
                std::byte{ 0x06 }, std::byte{ 0x20 }, std::byte{ 0xD0 }, std::byte{ 0xBE },
            },
        },
        {
            6688,
            {
                std::byte{ 0xFD }, std::byte{ 0x5A }, std::byte{ 0x66 }, std::byte{ 0x63 },
                std::byte{ 0x6E }, std::byte{ 0x93 }, std::byte{ 0x32 }, std::byte{ 0xF2 },
                std::byte{ 0xBD }, std::byte{ 0x7A }, std::byte{ 0xAF }, std::byte{ 0x31 },
                std::byte{ 0x60 }, std::byte{ 0x42 }, std::byte{ 0xE3 }, std::byte{ 0x6E },
            },
        },
    },
    {
        "ModelSpaceNormalsSixMrt_L4_00002002",
        IDR_LINEAR_LIGHTING_MODEL_SPACE_NORMALS_SIX_MRT_PS,
        {
            3228,
            {
                std::byte{ 0xD2 }, std::byte{ 0xE6 }, std::byte{ 0x4F }, std::byte{ 0xAC },
                std::byte{ 0xCE }, std::byte{ 0x47 }, std::byte{ 0xB0 }, std::byte{ 0x51 },
                std::byte{ 0xA2 }, std::byte{ 0x01 }, std::byte{ 0x73 }, std::byte{ 0x0E },
                std::byte{ 0x2F }, std::byte{ 0x9E }, std::byte{ 0xCF }, std::byte{ 0xB9 },
            },
        },
        {
            6416,
            {
                std::byte{ 0x56 }, std::byte{ 0x6E }, std::byte{ 0xF7 }, std::byte{ 0x4A },
                std::byte{ 0x0F }, std::byte{ 0x12 }, std::byte{ 0xAC }, std::byte{ 0x87 },
                std::byte{ 0x66 }, std::byte{ 0x9E }, std::byte{ 0x49 }, std::byte{ 0x2F },
                std::byte{ 0x52 }, std::byte{ 0xA7 }, std::byte{ 0x96 }, std::byte{ 0x6F },
            },
        },
    },
    {
        "ModelSpaceNormalsSixMrt_L3_00002003",
        IDR_LINEAR_LIGHTING_MODEL_SPACE_NORMALS_SIX_MRT_VERTEX_COLOR_PS,
        {
            3296,
            {
                std::byte{ 0x91 }, std::byte{ 0x6E }, std::byte{ 0xBF }, std::byte{ 0xDB },
                std::byte{ 0x49 }, std::byte{ 0xCD }, std::byte{ 0xB5 }, std::byte{ 0xEE },
                std::byte{ 0xBD }, std::byte{ 0xF7 }, std::byte{ 0x1A }, std::byte{ 0x26 },
                std::byte{ 0xEE }, std::byte{ 0x64 }, std::byte{ 0x63 }, std::byte{ 0xDB },
            },
        },
        {
            6484,
            {
                std::byte{ 0xB8 }, std::byte{ 0x2E }, std::byte{ 0x52 }, std::byte{ 0x3D },
                std::byte{ 0xF3 }, std::byte{ 0xD4 }, std::byte{ 0x22 }, std::byte{ 0x75 },
                std::byte{ 0xAF }, std::byte{ 0x27 }, std::byte{ 0x2E }, std::byte{ 0xB5 },
                std::byte{ 0xA9 }, std::byte{ 0xC6 }, std::byte{ 0x40 }, std::byte{ 0xB0 },
            },
        },
    },
    {
        "ModelSpaceNormalsAlphaTestSixMrt_L4_00002102",
        IDR_LINEAR_LIGHTING_MODEL_SPACE_NORMALS_ALPHA_TEST_SIX_MRT_PS,
        {
            3276,
            {
                std::byte{ 0x0E }, std::byte{ 0xE6 }, std::byte{ 0x8A }, std::byte{ 0x78 },
                std::byte{ 0xC0 }, std::byte{ 0x65 }, std::byte{ 0xE2 }, std::byte{ 0xD2 },
                std::byte{ 0x9E }, std::byte{ 0xAB }, std::byte{ 0xEE }, std::byte{ 0x56 },
                std::byte{ 0xC4 }, std::byte{ 0xA0 }, std::byte{ 0x1C }, std::byte{ 0xCB },
            },
        },
        {
            6464,
            {
                std::byte{ 0x3B }, std::byte{ 0x33 }, std::byte{ 0x6A }, std::byte{ 0x81 },
                std::byte{ 0x45 }, std::byte{ 0x90 }, std::byte{ 0x50 }, std::byte{ 0x64 },
                std::byte{ 0xAF }, std::byte{ 0xC2 }, std::byte{ 0x47 }, std::byte{ 0xF7 },
                std::byte{ 0xD5 }, std::byte{ 0x7D }, std::byte{ 0x21 }, std::byte{ 0xD2 },
            },
        },
    },
} };
