// Generated by tools/generate_distant_tree_linear_lighting_contracts.py.
// Do not edit this file by hand.
constexpr DistantTreeShaderContractDefinition kDistantTreeShaderContract{
    "DistantTreeBlock_00000000",
    0u,
    IDR_LINEAR_LIGHTING_DISTANT_TREE_BLOCK_PS,
    {
        644,
        {
            std::byte{ 0xA1 }, std::byte{ 0x57 }, std::byte{ 0x84 }, std::byte{ 0x71 },
            std::byte{ 0xE3 }, std::byte{ 0x0E }, std::byte{ 0x8C }, std::byte{ 0x34 },
            std::byte{ 0x29 }, std::byte{ 0x10 }, std::byte{ 0x12 }, std::byte{ 0xBE },
            std::byte{ 0xEB }, std::byte{ 0xF8 }, std::byte{ 0x73 }, std::byte{ 0x89 },
        },
    },
    {
        4020,
        {
            std::byte{ 0x57 }, std::byte{ 0x16 }, std::byte{ 0x04 }, std::byte{ 0x5B },
            std::byte{ 0x0E }, std::byte{ 0x4A }, std::byte{ 0xFD }, std::byte{ 0x74 },
            std::byte{ 0xFB }, std::byte{ 0x01 }, std::byte{ 0xA9 }, std::byte{ 0x91 },
            std::byte{ 0x1F }, std::byte{ 0xB7 }, std::byte{ 0x30 }, std::byte{ 0xD3 },
        },
    },
};
