// Generated by tools/generate_effect_linear_lighting_contracts.py.
// Do not edit this file by hand.
constexpr std::array<EffectShaderContractDefinition, 1> kEffectShaderContracts{ {
    {
        "EffectDefault_00000000",
        0u,
        IDR_LINEAR_LIGHTING_EFFECT_DEFAULT_PS,
        {
            932,
            {
                std::byte{ 0xBD }, std::byte{ 0xA7 }, std::byte{ 0x02 }, std::byte{ 0x8E },
                std::byte{ 0x4D }, std::byte{ 0x02 }, std::byte{ 0x3D }, std::byte{ 0x80 },
                std::byte{ 0xB1 }, std::byte{ 0x25 }, std::byte{ 0x22 }, std::byte{ 0x29 },
                std::byte{ 0x24 }, std::byte{ 0x61 }, std::byte{ 0x73 }, std::byte{ 0xE7 },
            },
        },
        {
            4124,
            {
                std::byte{ 0xDF }, std::byte{ 0x46 }, std::byte{ 0xC6 }, std::byte{ 0xA2 },
                std::byte{ 0xC9 }, std::byte{ 0x8C }, std::byte{ 0x4D }, std::byte{ 0x1D },
                std::byte{ 0x50 }, std::byte{ 0x6E }, std::byte{ 0x7E }, std::byte{ 0xDB },
                std::byte{ 0x49 }, std::byte{ 0x06 }, std::byte{ 0x40 }, std::byte{ 0x44 },
            },
        },
    },
} };
