// Generated by tools/generate_water_linear_lighting_contracts.py.
// Do not edit this file by hand.
constexpr std::array<WaterShaderContractDefinition, 17> kWaterShaderContracts{ {
    {
        "WaterColor_00000000",
        0u,
        IDR_LINEAR_LIGHTING_WATER_00000000_PS,
        {
            6752,
            {
                std::byte{ 0x37 }, std::byte{ 0x67 }, std::byte{ 0xB1 }, std::byte{ 0x2F },
                std::byte{ 0xD5 }, std::byte{ 0xE5 }, std::byte{ 0x6F }, std::byte{ 0x68 },
                std::byte{ 0x18 }, std::byte{ 0x0E }, std::byte{ 0x61 }, std::byte{ 0x57 },
                std::byte{ 0x7E }, std::byte{ 0x03 }, std::byte{ 0x42 }, std::byte{ 0x38 },
            },
        },
        {
            7056,
            {
                std::byte{ 0x60 }, std::byte{ 0x0A }, std::byte{ 0xA8 }, std::byte{ 0x2B },
                std::byte{ 0xE4 }, std::byte{ 0x62 }, std::byte{ 0x89 }, std::byte{ 0xB1 },
                std::byte{ 0xCB }, std::byte{ 0xCD }, std::byte{ 0x37 }, std::byte{ 0x2C },
                std::byte{ 0x8B }, std::byte{ 0x23 }, std::byte{ 0xA7 }, std::byte{ 0xCD },
            },
        },
    },
    {
        "WaterColor_0000001C",
        28u,
        IDR_LINEAR_LIGHTING_WATER_0000001C_PS,
        {
            7928,
            {
                std::byte{ 0x68 }, std::byte{ 0x76 }, std::byte{ 0xAC }, std::byte{ 0xD6 },
                std::byte{ 0x51 }, std::byte{ 0x11 }, std::byte{ 0xB2 }, std::byte{ 0x54 },
                std::byte{ 0x47 }, std::byte{ 0xEF }, std::byte{ 0x9F }, std::byte{ 0x43 },
                std::byte{ 0xC1 }, std::byte{ 0xEB }, std::byte{ 0x88 }, std::byte{ 0xFD },
            },
        },
        {
            8232,
            {
                std::byte{ 0x3E }, std::byte{ 0xDE }, std::byte{ 0xBA }, std::byte{ 0x04 },
                std::byte{ 0x22 }, std::byte{ 0x54 }, std::byte{ 0x7B }, std::byte{ 0x1E },
                std::byte{ 0x55 }, std::byte{ 0x8E }, std::byte{ 0x12 }, std::byte{ 0x7B },
                std::byte{ 0x3B }, std::byte{ 0x5A }, std::byte{ 0x6C }, std::byte{ 0x85 },
            },
        },
    },
    {
        "WaterColor_0000005E",
        94u,
        IDR_LINEAR_LIGHTING_WATER_0000005E_PS,
        {
            8272,
            {
                std::byte{ 0x30 }, std::byte{ 0x6B }, std::byte{ 0x71 }, std::byte{ 0xFB },
                std::byte{ 0x76 }, std::byte{ 0xBF }, std::byte{ 0xCC }, std::byte{ 0x5E },
                std::byte{ 0x6F }, std::byte{ 0xE4 }, std::byte{ 0xB3 }, std::byte{ 0x48 },
                std::byte{ 0xBD }, std::byte{ 0xF2 }, std::byte{ 0x68 }, std::byte{ 0xB8 },
            },
        },
        {
            8576,
            {
                std::byte{ 0x44 }, std::byte{ 0xEB }, std::byte{ 0xC4 }, std::byte{ 0x52 },
                std::byte{ 0xE2 }, std::byte{ 0x09 }, std::byte{ 0x86 }, std::byte{ 0xD8 },
                std::byte{ 0x3C }, std::byte{ 0x57 }, std::byte{ 0xAD }, std::byte{ 0x19 },
                std::byte{ 0x79 }, std::byte{ 0x42 }, std::byte{ 0xA7 }, std::byte{ 0x4D },
            },
        },
    },
    {
        "WaterColor_0000009F",
        159u,
        IDR_LINEAR_LIGHTING_WATER_0000009F_PS,
        {
            6648,
            {
                std::byte{ 0xDB }, std::byte{ 0x81 }, std::byte{ 0x77 }, std::byte{ 0x87 },
                std::byte{ 0xF5 }, std::byte{ 0x41 }, std::byte{ 0x11 }, std::byte{ 0x07 },
                std::byte{ 0x8E }, std::byte{ 0x59 }, std::byte{ 0x87 }, std::byte{ 0xFC },
                std::byte{ 0xEC }, std::byte{ 0x5D }, std::byte{ 0xE7 }, std::byte{ 0x36 },
            },
        },
        {
            6952,
            {
                std::byte{ 0xE0 }, std::byte{ 0xE0 }, std::byte{ 0x83 }, std::byte{ 0xDC },
                std::byte{ 0xE7 }, std::byte{ 0x3C }, std::byte{ 0xE9 }, std::byte{ 0x44 },
                std::byte{ 0x5D }, std::byte{ 0x48 }, std::byte{ 0xC9 }, std::byte{ 0xE1 },
                std::byte{ 0x1D }, std::byte{ 0x0C }, std::byte{ 0x57 }, std::byte{ 0x86 },
            },
        },
    },
    {
        "WaterColor_0000021C",
        540u,
        IDR_LINEAR_LIGHTING_WATER_0000021C_PS,
        {
            8228,
            {
                std::byte{ 0x53 }, std::byte{ 0x7B }, std::byte{ 0x31 }, std::byte{ 0xE6 },
                std::byte{ 0xE8 }, std::byte{ 0x24 }, std::byte{ 0xB1 }, std::byte{ 0x00 },
                std::byte{ 0xA5 }, std::byte{ 0x57 }, std::byte{ 0xF3 }, std::byte{ 0x04 },
                std::byte{ 0x61 }, std::byte{ 0x3D }, std::byte{ 0x7F }, std::byte{ 0xF2 },
            },
        },
        {
            8532,
            {
                std::byte{ 0x67 }, std::byte{ 0x73 }, std::byte{ 0x67 }, std::byte{ 0x17 },
                std::byte{ 0x3B }, std::byte{ 0x0A }, std::byte{ 0x36 }, std::byte{ 0x95 },
                std::byte{ 0x63 }, std::byte{ 0x77 }, std::byte{ 0x0F }, std::byte{ 0x20 },
                std::byte{ 0xBC }, std::byte{ 0xA3 }, std::byte{ 0xF5 }, std::byte{ 0x88 },
            },
        },
    },
    {
        "WaterColor_0000025E",
        606u,
        IDR_LINEAR_LIGHTING_WATER_0000025E_PS,
        {
            8572,
            {
                std::byte{ 0xB4 }, std::byte{ 0x9B }, std::byte{ 0x66 }, std::byte{ 0x9B },
                std::byte{ 0xFC }, std::byte{ 0x2C }, std::byte{ 0xE2 }, std::byte{ 0x18 },
                std::byte{ 0x3D }, std::byte{ 0x89 }, std::byte{ 0xFF }, std::byte{ 0x49 },
                std::byte{ 0xE6 }, std::byte{ 0x1D }, std::byte{ 0xB5 }, std::byte{ 0x41 },
            },
        },
        {
            8876,
            {
                std::byte{ 0x2C }, std::byte{ 0xCF }, std::byte{ 0xE6 }, std::byte{ 0x56 },
                std::byte{ 0x96 }, std::byte{ 0xA2 }, std::byte{ 0x23 }, std::byte{ 0x2B },
                std::byte{ 0x70 }, std::byte{ 0x2B }, std::byte{ 0xDE }, std::byte{ 0xD5 },
                std::byte{ 0x65 }, std::byte{ 0xDF }, std::byte{ 0xDE }, std::byte{ 0x7B },
            },
        },
    },
    {
        "WaterColor_0000029F",
        671u,
        IDR_LINEAR_LIGHTING_WATER_0000029F_PS,
        {
            6948,
            {
                std::byte{ 0x48 }, std::byte{ 0x46 }, std::byte{ 0xD7 }, std::byte{ 0xE5 },
                std::byte{ 0xE4 }, std::byte{ 0x9A }, std::byte{ 0x5B }, std::byte{ 0xE1 },
                std::byte{ 0x34 }, std::byte{ 0x9D }, std::byte{ 0xC3 }, std::byte{ 0xA1 },
                std::byte{ 0x53 }, std::byte{ 0x60 }, std::byte{ 0x14 }, std::byte{ 0x8B },
            },
        },
        {
            7252,
            {
                std::byte{ 0x27 }, std::byte{ 0x2C }, std::byte{ 0xDB }, std::byte{ 0x1B },
                std::byte{ 0xE9 }, std::byte{ 0x76 }, std::byte{ 0x60 }, std::byte{ 0x58 },
                std::byte{ 0x76 }, std::byte{ 0x9D }, std::byte{ 0xCD }, std::byte{ 0xD8 },
                std::byte{ 0x3C }, std::byte{ 0x06 }, std::byte{ 0x96 }, std::byte{ 0x04 },
            },
        },
    },
    {
        "WaterColor_00001002",
        4098u,
        IDR_LINEAR_LIGHTING_WATER_00001002_PS,
        {
            3292,
            {
                std::byte{ 0x4A }, std::byte{ 0xB2 }, std::byte{ 0x5F }, std::byte{ 0xA0 },
                std::byte{ 0x74 }, std::byte{ 0x37 }, std::byte{ 0x29 }, std::byte{ 0x9F },
                std::byte{ 0xBF }, std::byte{ 0x3F }, std::byte{ 0x16 }, std::byte{ 0x0E },
                std::byte{ 0x24 }, std::byte{ 0xFD }, std::byte{ 0xF4 }, std::byte{ 0x00 },
            },
        },
        {
            3596,
            {
                std::byte{ 0xEC }, std::byte{ 0x5E }, std::byte{ 0x76 }, std::byte{ 0xFF },
                std::byte{ 0x89 }, std::byte{ 0x58 }, std::byte{ 0x53 }, std::byte{ 0xFC },
                std::byte{ 0xD4 }, std::byte{ 0x52 }, std::byte{ 0xA4 }, std::byte{ 0x5B },
                std::byte{ 0x99 }, std::byte{ 0x44 }, std::byte{ 0x6B }, std::byte{ 0x2E },
            },
        },
    },
    {
        "WaterColor_0000105E",
        4190u,
        IDR_LINEAR_LIGHTING_WATER_0000105E_PS,
        {
            3636,
            {
                std::byte{ 0x96 }, std::byte{ 0x4A }, std::byte{ 0x87 }, std::byte{ 0x9D },
                std::byte{ 0x56 }, std::byte{ 0x53 }, std::byte{ 0x90 }, std::byte{ 0x7F },
                std::byte{ 0x3E }, std::byte{ 0x23 }, std::byte{ 0x3F }, std::byte{ 0x6C },
                std::byte{ 0xF0 }, std::byte{ 0x0C }, std::byte{ 0x4C }, std::byte{ 0xB0 },
            },
        },
        {
            3940,
            {
                std::byte{ 0xC6 }, std::byte{ 0xF7 }, std::byte{ 0xAB }, std::byte{ 0x0F },
                std::byte{ 0x3F }, std::byte{ 0xF9 }, std::byte{ 0x49 }, std::byte{ 0xBB },
                std::byte{ 0xF6 }, std::byte{ 0x8D }, std::byte{ 0xB5 }, std::byte{ 0xBA },
                std::byte{ 0xF7 }, std::byte{ 0x98 }, std::byte{ 0x4B }, std::byte{ 0x49 },
            },
        },
    },
    {
        "WaterColor_0000109F",
        4255u,
        IDR_LINEAR_LIGHTING_WATER_0000109F_PS,
        {
            3316,
            {
                std::byte{ 0xCF }, std::byte{ 0xEB }, std::byte{ 0x98 }, std::byte{ 0x27 },
                std::byte{ 0xD2 }, std::byte{ 0x3C }, std::byte{ 0x0E }, std::byte{ 0xCF },
                std::byte{ 0x93 }, std::byte{ 0x34 }, std::byte{ 0x18 }, std::byte{ 0x05 },
                std::byte{ 0x0A }, std::byte{ 0xD3 }, std::byte{ 0x2C }, std::byte{ 0x5F },
            },
        },
        {
            3620,
            {
                std::byte{ 0xAF }, std::byte{ 0x80 }, std::byte{ 0xE5 }, std::byte{ 0x40 },
                std::byte{ 0x65 }, std::byte{ 0xC7 }, std::byte{ 0x30 }, std::byte{ 0xF7 },
                std::byte{ 0xCA }, std::byte{ 0x14 }, std::byte{ 0x79 }, std::byte{ 0x72 },
                std::byte{ 0xD9 }, std::byte{ 0x0F }, std::byte{ 0xF1 }, std::byte{ 0x84 },
            },
        },
    },
    {
        "WaterColor_0000121E",
        4638u,
        IDR_LINEAR_LIGHTING_WATER_0000121E_PS,
        {
            3592,
            {
                std::byte{ 0x20 }, std::byte{ 0x3D }, std::byte{ 0xEA }, std::byte{ 0x50 },
                std::byte{ 0xD2 }, std::byte{ 0xB7 }, std::byte{ 0xBE }, std::byte{ 0xDB },
                std::byte{ 0x3B }, std::byte{ 0x13 }, std::byte{ 0x65 }, std::byte{ 0xE7 },
                std::byte{ 0x84 }, std::byte{ 0x9C }, std::byte{ 0x49 }, std::byte{ 0xCC },
            },
        },
        {
            3896,
            {
                std::byte{ 0xEE }, std::byte{ 0x09 }, std::byte{ 0xF7 }, std::byte{ 0xD9 },
                std::byte{ 0x7F }, std::byte{ 0x5B }, std::byte{ 0x6D }, std::byte{ 0xD4 },
                std::byte{ 0xC3 }, std::byte{ 0x86 }, std::byte{ 0x1D }, std::byte{ 0xBA },
                std::byte{ 0xD2 }, std::byte{ 0x75 }, std::byte{ 0x38 }, std::byte{ 0x7C },
            },
        },
    },
    {
        "WaterColor_0000125E",
        4702u,
        IDR_LINEAR_LIGHTING_WATER_0000125E_PS,
        {
            3936,
            {
                std::byte{ 0x35 }, std::byte{ 0x13 }, std::byte{ 0xEB }, std::byte{ 0xCA },
                std::byte{ 0xC7 }, std::byte{ 0xEE }, std::byte{ 0x4D }, std::byte{ 0xA3 },
                std::byte{ 0xC7 }, std::byte{ 0x22 }, std::byte{ 0x14 }, std::byte{ 0x55 },
                std::byte{ 0xA1 }, std::byte{ 0xA6 }, std::byte{ 0xD9 }, std::byte{ 0xF4 },
            },
        },
        {
            4240,
            {
                std::byte{ 0xC6 }, std::byte{ 0x3E }, std::byte{ 0x35 }, std::byte{ 0x4A },
                std::byte{ 0x26 }, std::byte{ 0x16 }, std::byte{ 0xCE }, std::byte{ 0xA7 },
                std::byte{ 0x83 }, std::byte{ 0xCB }, std::byte{ 0x9F }, std::byte{ 0xDC },
                std::byte{ 0x25 }, std::byte{ 0x9C }, std::byte{ 0x7C }, std::byte{ 0x54 },
            },
        },
    },
    {
        "WaterColor_00001A8F",
        6799u,
        IDR_LINEAR_LIGHTING_WATER_00001A8F_PS,
        {
            3616,
            {
                std::byte{ 0xDE }, std::byte{ 0x6D }, std::byte{ 0x57 }, std::byte{ 0x63 },
                std::byte{ 0x7A }, std::byte{ 0x7A }, std::byte{ 0x9B }, std::byte{ 0x7B },
                std::byte{ 0x34 }, std::byte{ 0x0E }, std::byte{ 0x66 }, std::byte{ 0x41 },
                std::byte{ 0x69 }, std::byte{ 0xC4 }, std::byte{ 0xA4 }, std::byte{ 0xD9 },
            },
        },
        {
            3920,
            {
                std::byte{ 0x50 }, std::byte{ 0xA3 }, std::byte{ 0x53 }, std::byte{ 0x07 },
                std::byte{ 0x8B }, std::byte{ 0x07 }, std::byte{ 0x4B }, std::byte{ 0x94 },
                std::byte{ 0x00 }, std::byte{ 0xDF }, std::byte{ 0x97 }, std::byte{ 0x42 },
                std::byte{ 0xF7 }, std::byte{ 0x43 }, std::byte{ 0x77 }, std::byte{ 0x41 },
            },
        },
    },
    {
        "WaterColor_00010000",
        65536u,
        IDR_LINEAR_LIGHTING_WATER_00010000_PS,
        {
            3600,
            {
                std::byte{ 0x44 }, std::byte{ 0x77 }, std::byte{ 0x35 }, std::byte{ 0x9A },
                std::byte{ 0x3F }, std::byte{ 0x58 }, std::byte{ 0x68 }, std::byte{ 0x47 },
                std::byte{ 0xF0 }, std::byte{ 0x40 }, std::byte{ 0x6F }, std::byte{ 0xD9 },
                std::byte{ 0x28 }, std::byte{ 0x8B }, std::byte{ 0x66 }, std::byte{ 0x3B },
            },
        },
        {
            3904,
            {
                std::byte{ 0x64 }, std::byte{ 0xA9 }, std::byte{ 0xC4 }, std::byte{ 0x2E },
                std::byte{ 0x93 }, std::byte{ 0x56 }, std::byte{ 0x44 }, std::byte{ 0xD2 },
                std::byte{ 0xD4 }, std::byte{ 0x94 }, std::byte{ 0x5D }, std::byte{ 0x61 },
                std::byte{ 0x46 }, std::byte{ 0xF5 }, std::byte{ 0xDC }, std::byte{ 0xB2 },
            },
        },
    },
    {
        "WaterColor_00010204",
        66052u,
        IDR_LINEAR_LIGHTING_WATER_00010204_PS,
        {
            3948,
            {
                std::byte{ 0x66 }, std::byte{ 0x99 }, std::byte{ 0x6F }, std::byte{ 0x7C },
                std::byte{ 0x78 }, std::byte{ 0xB9 }, std::byte{ 0x57 }, std::byte{ 0x70 },
                std::byte{ 0xC6 }, std::byte{ 0xA8 }, std::byte{ 0xE8 }, std::byte{ 0x08 },
                std::byte{ 0xCF }, std::byte{ 0x38 }, std::byte{ 0xC2 }, std::byte{ 0xF7 },
            },
        },
        {
            4252,
            {
                std::byte{ 0x33 }, std::byte{ 0x30 }, std::byte{ 0x5A }, std::byte{ 0x87 },
                std::byte{ 0x2F }, std::byte{ 0xA1 }, std::byte{ 0xC6 }, std::byte{ 0x16 },
                std::byte{ 0xC4 }, std::byte{ 0x58 }, std::byte{ 0x09 }, std::byte{ 0xBC },
                std::byte{ 0xA7 }, std::byte{ 0x49 }, std::byte{ 0x69 }, std::byte{ 0x18 },
            },
        },
    },
    {
        "WaterColor_00018010",
        98320u,
        IDR_LINEAR_LIGHTING_WATER_00018010_PS,
        {
            2496,
            {
                std::byte{ 0xC4 }, std::byte{ 0x62 }, std::byte{ 0x2B }, std::byte{ 0x94 },
                std::byte{ 0xC4 }, std::byte{ 0xBC }, std::byte{ 0x5C }, std::byte{ 0x0D },
                std::byte{ 0xB3 }, std::byte{ 0xD6 }, std::byte{ 0x24 }, std::byte{ 0xBD },
                std::byte{ 0x93 }, std::byte{ 0x41 }, std::byte{ 0xE1 }, std::byte{ 0x32 },
            },
        },
        {
            2796,
            {
                std::byte{ 0xAE }, std::byte{ 0xB1 }, std::byte{ 0x55 }, std::byte{ 0x3F },
                std::byte{ 0x37 }, std::byte{ 0x8E }, std::byte{ 0x95 }, std::byte{ 0x6B },
                std::byte{ 0xA4 }, std::byte{ 0xDC }, std::byte{ 0x81 }, std::byte{ 0xD8 },
                std::byte{ 0xDA }, std::byte{ 0x09 }, std::byte{ 0x3B }, std::byte{ 0x5B },
            },
        },
    },
    {
        "WaterColor_00020204",
        131588u,
        IDR_LINEAR_LIGHTING_WATER_00020204_PS,
        {
            7052,
            {
                std::byte{ 0x41 }, std::byte{ 0x5F }, std::byte{ 0x86 }, std::byte{ 0xAE },
                std::byte{ 0x52 }, std::byte{ 0xC1 }, std::byte{ 0x71 }, std::byte{ 0x87 },
                std::byte{ 0xD4 }, std::byte{ 0x1F }, std::byte{ 0x91 }, std::byte{ 0x0A },
                std::byte{ 0xD9 }, std::byte{ 0xDA }, std::byte{ 0xC3 }, std::byte{ 0x13 },
            },
        },
        {
            7356,
            {
                std::byte{ 0x7C }, std::byte{ 0x27 }, std::byte{ 0x32 }, std::byte{ 0xC0 },
                std::byte{ 0x32 }, std::byte{ 0x7F }, std::byte{ 0x22 }, std::byte{ 0x82 },
                std::byte{ 0xD5 }, std::byte{ 0xFC }, std::byte{ 0x22 }, std::byte{ 0xA5 },
                std::byte{ 0x07 }, std::byte{ 0x40 }, std::byte{ 0xEA }, std::byte{ 0xB7 },
            },
        },
    },
} };
