from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import census_linear_lighting_fxp as census
from generate_complex_material_producer_contracts import (
    FAMILY_ENVIRONMENT_MAP,
    build_contracts,
)


EXPECTED_LINEAR_CONTRACTS = 288
EXPECTED_ENVIRONMENT_IDENTITIES = 86
EXPECTED_ORDINARY_OPAQUE_IDENTITIES = 33
UNSUPPORTED_TAG_TOKENS = (
    "Projected",
    "FiveMrt",
    "Hair",
    "FaceDetail",
    "SkinTint",
    "Combined",
    "MeatCuff",
    "Pipboy",
)


class ContractError(RuntimeError):
    pass


@dataclass(frozen=True)
class Contract:
    index: int
    name: str
    producer_contract_plus_one: int
    source: Path
    packaged: Path
    assembly: Path


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true")
    group.add_argument("--write-assets", action="store_true")
    return parser.parse_args()


def identity(data: bytes) -> tuple[int, str]:
    if len(data) < 32 or data[:4] != b"DXBC":
        raise ContractError("input is not a DXBC container")
    return len(data), data[4:20].hex()


def build_inventory(root: Path) -> tuple[list[Contract], list[int]]:
    producer_contracts, aliases = build_contracts(
        (root / "Shaders012_VR.fxp").read_bytes()
    )
    environment_contracts = {
        alias.contract_plus_one
        for alias in aliases
        if alias.family == FAMILY_ENVIRONMENT_MAP
    }
    if len(environment_contracts) != EXPECTED_ENVIRONMENT_IDENTITIES:
        raise ContractError(
            "environment producer identity count changed: "
            f"{len(environment_contracts)}"
        )
    producer_by_identity = {
        producer_contracts[index - 1].identity: index
        for index in environment_contracts
    }

    manifest = json.loads(
        (
            root
            / "package"
            / "Shaders"
            / "Community"
            / "LinearLightingContracts.json"
        ).read_text(encoding="utf-8")
    )
    if not isinstance(manifest, list) or len(manifest) != EXPECTED_LINEAR_CONTRACTS:
        raise ContractError("Linear Lighting contract inventory changed")

    reconstruction = (
        root / "package" / "Shaders" / "Community" / "Reconstruction"
    )
    verified = (
        root / "package" / "Shaders" / "Community" / "VerifiedLinearLighting"
    )
    mapping = [0] * len(manifest)
    supported: list[Contract] = []
    mapped_environment = 0
    for index, entry in enumerate(manifest):
        name = str(entry["name"])
        original = (verified / f"{name}.dxbc").read_bytes()
        producer = producer_by_identity.get(identity(original), 0)
        if producer == 0:
            continue
        mapped_environment += 1
        if any(token in name for token in UNSUPPORTED_TAG_TOKENS):
            continue
        mapping[index] = producer
        supported.append(
            Contract(
                index,
                name,
                producer,
                reconstruction / f"{name}.LinearLightingCandidate.hlsl",
                reconstruction / f"{name}.LinearLightingCandidate.dxbc",
                reconstruction / f"{name}.LinearLightingCandidate.asm",
            )
        )
    if mapped_environment != EXPECTED_ENVIRONMENT_IDENTITIES:
        raise ContractError(
            "not every environment producer maps to a Linear Lighting "
            f"contract: {mapped_environment}"
        )
    if len(supported) != EXPECTED_ORDINARY_OPAQUE_IDENTITIES:
        raise ContractError(
            "ordinary opaque environment identity count changed: "
            f"{len(supported)}"
        )
    return supported, mapping


def render(mapping: list[int]) -> str:
    rows = [
        "// Generated by tools/generate_complex_environment_contracts.py.",
        "// Do not edit this file by hand.",
        "inline constexpr std::array<std::uint16_t, 288>",
        "    kComplexEnvironmentProducerByLinearContract{ {",
    ]
    for start in range(0, len(mapping), 12):
        values = ", ".join(
            f"{value}u" for value in mapping[start : start + 12]
        )
        rows.append(f"        {values},")
    rows.extend(
        (
            "    } };",
            "",
            "inline constexpr std::size_t",
            "    kComplexEnvironmentShaderContractCount = 33;",
            "",
        )
    )
    return "\n".join(rows)


def compile_shader(
    fxc: Path,
    contract: Contract,
    output: Path,
    assembly: Path,
) -> None:
    command = [
        str(fxc),
        "/nologo",
        "/T",
        "ps_5_0",
        "/E",
        "PSMain",
        "/O3",
        "/D",
        "LINEAR_LIGHTING_COMPLEX_ENVIRONMENT=1",
        "/Fo",
        str(output),
        "/Fc",
        str(assembly),
        str(contract.source),
    ]
    completed = subprocess.run(
        command,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise ContractError(
            f"{contract.name} compilation failed:\n"
            f"{completed.stdout}{completed.stderr}"
        )


def main() -> int:
    options = arguments()
    try:
        root = options.root.resolve()
        supported, mapping = build_inventory(root)
        generated = render(mapping)
        output = options.output.resolve()
        fxc = census.find_fxc(None)
        with tempfile.TemporaryDirectory(
            prefix="fo4vr_cs_complex_environment_"
        ) as directory:
            temporary = Path(directory)
            for contract in supported:
                compiled = temporary / f"{contract.name}.dxbc"
                assembly = temporary / f"{contract.name}.asm"
                compile_shader(fxc, contract, compiled, assembly)
                data = compiled.read_bytes()
                assembly_text = "\n".join(
                    line.rstrip()
                    for line in assembly.read_text(
                        encoding="utf-8"
                    ).splitlines()
                ) + "\n"
                if options.write_assets:
                    contract.packaged.write_bytes(data)
                    contract.assembly.write_text(
                        assembly_text,
                        encoding="utf-8",
                        newline="\n",
                    )
                elif (
                    not contract.packaged.is_file()
                    or contract.packaged.read_bytes() != data
                    or not contract.assembly.is_file()
                    or contract.assembly.read_text(encoding="utf-8")
                    != assembly_text
                ):
                    raise ContractError(
                        "complex environment replacement is stale: "
                        f"{contract.packaged}"
                    )
        if options.write_assets:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(generated, encoding="utf-8", newline="\n")
        elif (
            not output.is_file()
            or output.read_text(encoding="utf-8") != generated
        ):
            raise ContractError(
                f"generated complex environment contract is stale: {output}"
            )
        print(
            "Complex environment contracts verified: 33 ordinary opaque "
            "identities, descriptor-gated from 86 ENVMAP identities."
        )
    except (
        OSError,
        ValueError,
        KeyError,
        json.JSONDecodeError,
        census.CensusError,
        ContractError,
    ) as error:
        print(
            f"Complex environment contract generation failed: {error}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
