from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path


def fail(message: str) -> None:
    raise RuntimeError(message)


def read_dxbc(path: Path) -> bytes:
    data = path.read_bytes()
    if len(data) < 32 or data[:4] != b"DXBC":
        fail(f"invalid DXBC container: {path}")
    declared_size = struct.unpack_from("<I", data, 24)[0]
    if declared_size != len(data):
        fail(
            f"DXBC size mismatch for {path}: "
            f"declared {declared_size}, actual {len(data)}"
        )
    return data


def format_identity(data: bytes, indent: str) -> list[str]:
    checksum = data[4:20]
    rows = [f"{indent}{{", f"{indent}    {len(data)},", f"{indent}    {{"]
    for offset in range(0, len(checksum), 4):
        values = ", ".join(
            f"std::byte{{ 0x{value:02X} }}" for value in checksum[offset : offset + 4]
        )
        rows.append(f"{indent}        {values},")
    rows.extend((f"{indent}    }},", f"{indent}}},"))
    return rows


def render(root: Path) -> str:
    manifest_path = (
        root / "package" / "Shaders" / "Community" / "LinearLightingContracts.json"
    )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(manifest, list) or not 0 < len(manifest) <= 320:
        fail("Linear Lighting manifest must contain between 1 and 320 contracts")

    verified = (
        root / "package" / "Shaders" / "Community" / "VerifiedLinearLighting"
    )
    reconstruction = (
        root / "package" / "Shaders" / "Community" / "Reconstruction"
    )
    names: set[str] = set()
    resources: set[str] = set()
    rows = [
        "// Generated by tools/generate_linear_lighting_runtime_contracts.py.",
        "// Do not edit this file by hand.",
        f"constexpr std::array<ShaderContractDefinition, {len(manifest)}> kShaderContracts{{ {{",
    ]
    for index, entry in enumerate(manifest):
        if not isinstance(entry, dict):
            fail(f"manifest entry {index} is not an object")
        name = entry.get("name")
        resource = entry.get("resource")
        if not isinstance(name, str) or not name:
            fail(f"manifest entry {index} has an invalid name")
        if not isinstance(resource, str) or not resource.startswith("IDR_"):
            fail(f"manifest entry {index} has an invalid resource symbol")
        if name in names:
            fail(f"duplicate contract name: {name}")
        if resource in resources:
            fail(f"duplicate resource symbol: {resource}")
        names.add(name)
        resources.add(resource)

        original = read_dxbc(verified / f"{name}.dxbc")
        replacement = read_dxbc(
            reconstruction / f"{name}.LinearLightingCandidate.dxbc"
        )
        rows.extend(("    {", f'        "{name}",', f"        {resource},"))
        rows.extend(format_identity(original, "        "))
        rows.extend(format_identity(replacement, "        "))
        rows.append("    },")
    rows.extend(("} };", ""))
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        expected = render(arguments.root.resolve())
        output = arguments.output.resolve()
        if arguments.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != expected:
                fail(
                    f"generated Linear Lighting runtime contracts are stale: {output}"
                )
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(expected, encoding="utf-8", newline="\n")
    except (OSError, RuntimeError, json.JSONDecodeError) as error:
        print(f"Linear Lighting contract generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
