from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path

import census_linear_lighting_fxp as census


AMBIENT_DESCRIPTOR_BIT = 1 << 17
CHARACTER_DESCRIPTOR_BIT = 1 << 26
VANILLA_GAMMA = 2.2
EXPECTED_GAMMA_FLOATS = 6
EXPECTED_GAMMA_INSTRUCTIONS = 2
RUNTIME_INSTANCE_CAPACITY = 8


class ContractError(RuntimeError):
    pass


def dxbc_identity(data: bytes) -> tuple[int, str]:
    if len(data) < 32 or data[:4] != b"DXBC":
        raise ContractError("input is not a DXBC container")
    declared_size = struct.unpack_from("<I", data, 24)[0]
    if declared_size != len(data):
        raise ContractError(
            f"DXBC declares {declared_size} bytes but contains {len(data)}"
        )
    return len(data), data[4:20].hex()


def gamma_offsets(data: bytes) -> list[int]:
    needle = struct.pack("<f", VANILLA_GAMMA)
    offsets: list[int] = []
    cursor = 0
    while True:
        offset = data.find(needle, cursor)
        if offset < 0:
            break
        offsets.append(offset)
        cursor = offset + len(needle)
    if len(offsets) != EXPECTED_GAMMA_FLOATS:
        raise ContractError(
            f"expected {EXPECTED_GAMMA_FLOATS} vanilla gamma floats, "
            f"found {len(offsets)}"
        )
    return offsets


def verify_ambient_pow_semantics(assembly: str, label: str) -> None:
    lines = [line.strip() for line in assembly.splitlines() if line.strip()]
    hits = [
        index
        for index, line in enumerate(lines)
        if "l(2.200000, 2.200000, 2.200000" in line
        or "0.000000, 2.200000, 2.200000, 2.200000)" in line
    ]
    if len(hits) != EXPECTED_GAMMA_INSTRUCTIONS:
        raise ContractError(
            f"{label}: expected {EXPECTED_GAMMA_INSTRUCTIONS} ambient gamma "
            f"instructions, found {len(hits)}"
        )
    for hit in hits:
        context = lines[max(0, hit - 10) : hit]
        joined = "\n".join(context)
        if (
            sum(line.startswith("log ") for line in context) < 3
            or "cb2[8]" not in joined
            or "cb2[9]" not in joined
            or "cb2[10]" not in joined
        ):
            raise ContractError(
                f"{label}: gamma instruction is not fed by the verified "
                "DirectionalAmbient cb2[8..10] log triplet"
            )
        if hit + 1 >= len(lines) or not lines[hit + 1].startswith("exp "):
            raise ContractError(
                f"{label}: gamma instruction is not followed by exp"
            )


def byte_array(checksum: str) -> str:
    values = ", ".join(
        f"std::byte{{ 0x{checksum[index:index + 2].upper()} }}"
        for index in range(0, len(checksum), 2)
    )
    return f"{{ {values} }}"


def render_generated(manifest: dict[str, object]) -> str:
    contracts = manifest["contracts"]
    assert isinstance(contracts, list)
    descriptor_rows: list[tuple[int, int]] = []
    lines = [
        "// Generated by tools/generate_dflight_ambient_contracts.py.",
        "// Do not edit by hand.",
        "constexpr std::array<DFLightAmbientContractDefinition,",
        f"    {len(contracts)}> kDFLightAmbientContracts{{{{",
    ]
    for contract_index, contract_object in enumerate(contracts):
        assert isinstance(contract_object, dict)
        checksum = str(contract_object["checksum"])
        offsets = contract_object["gammaOffsets"]
        keys = contract_object["descriptorKeys"]
        assert isinstance(offsets, list)
        assert isinstance(keys, list)
        lines.extend(
            [
                "    DFLightAmbientContractDefinition{",
                f'        "{contract_object["name"]}",',
                "        DxbcIdentity{",
                f"            {int(contract_object['size'])},",
                f"            {byte_array(checksum)},",
                "        },",
                "        { "
                + ", ".join(f"0x{int(offset):08X}u" for offset in offsets)
                + " },",
                "    },",
            ]
        )
        descriptor_rows.extend((int(key, 16), contract_index) for key in keys)
    lines.extend(["}};", ""])

    maximum_instances = int(manifest["maximumInstancesPerIdentity"])
    lines.extend(
        [
            "static_assert(",
            "    Runtime::kMaximumTrackedOriginalShadersPerContract >=",
            f"    {maximum_instances});",
            "",
        ]
    )

    descriptor_rows.sort()
    lines.extend(
        [
            "constexpr std::array<DFLightAmbientDescriptorContract,",
            f"    {len(descriptor_rows)}> kDFLightAmbientDescriptorContracts{{{{",
        ]
    )
    for descriptor, contract_index in descriptor_rows:
        lines.append(
            "    DFLightAmbientDescriptorContract{ "
            f"0x{descriptor:08X}u, {contract_index}u }},"
        )
    lines.extend(["}};", ""])
    return "\n".join(lines)


def build_manifest(
    fxp_path: Path,
    asset_directory: Path,
    fxc: Path,
) -> dict[str, object]:
    inventory = census.parse_fxp(fxp_path.read_bytes())
    ambient = [
        item
        for item in inventory.containers
        if item.family == "DFLight"
        and item.stage == "PS"
        and item.key is not None
        and item.key & AMBIENT_DESCRIPTOR_BIT
        and not item.key & CHARACTER_DESCRIPTOR_BIT
    ]
    by_identity: dict[tuple[int, str], list[census.DxbcContainer]] = {}
    for item in ambient:
        by_identity.setdefault(item.identity, []).append(item)
    if len(ambient) != 78 or len(by_identity) != 39:
        raise ContractError(
            "FO4VR DFLight ambient inventory changed: expected 78 records/39 "
            f"unique shaders, found {len(ambient)}/{len(by_identity)}"
        )

    maximum_instances = max(len(occurrences) for occurrences in by_identity.values())
    if maximum_instances > RUNTIME_INSTANCE_CAPACITY:
        raise ContractError(
            "DFLight ambient identity instance capacity is insufficient: "
            f"need {maximum_instances}, have {RUNTIME_INSTANCE_CAPACITY}"
        )

    asset_directory.mkdir(parents=True, exist_ok=True)
    contracts: list[dict[str, object]] = []
    for identity, occurrences in sorted(
        by_identity.items(), key=lambda item: (item[0][1], item[0][0])
    ):
        size, checksum = identity
        witness = occurrences[0]
        name = f"DFLightAmbient_{checksum[:8]}_{size}"
        file_name = f"{name}.dxbc"
        asset_path = asset_directory / file_name
        asset_path.write_bytes(witness.data)
        offsets = gamma_offsets(witness.data)
        verify_ambient_pow_semantics(
            census.disassemble(fxc, asset_path), name
        )
        contracts.append(
            {
                "name": name,
                "file": file_name,
                "size": size,
                "checksum": checksum,
                "gammaOffsets": offsets,
                "descriptorKeys": sorted(
                    f"0x{int(item.key):08X}" for item in occurrences
                ),
            }
        )

    return {
        "schemaVersion": 1,
        "sourceFxpSha256": hashlib.sha256(fxp_path.read_bytes()).hexdigest(),
        "ambientDescriptorBit": "0x00020000",
        "characterDescriptorBit": "0x04000000",
        "recordCount": len(ambient),
        "uniqueShaderCount": len(contracts),
        "maximumInstancesPerIdentity": maximum_instances,
        "contracts": contracts,
    }


def validate_manifest(
    manifest: dict[str, object], asset_directory: Path, fxc: Path
) -> None:
    if manifest.get("schemaVersion") != 1:
        raise ContractError("unsupported DFLight ambient manifest schema")
    if manifest.get("recordCount") != 78 or manifest.get("uniqueShaderCount") != 39:
        raise ContractError("DFLight ambient manifest inventory is incomplete")
    contracts = manifest.get("contracts")
    if not isinstance(contracts, list) or len(contracts) != 39:
        raise ContractError("DFLight ambient manifest contracts are incomplete")

    descriptors: set[int] = set()
    maximum_instances = 0
    for contract in contracts:
        if not isinstance(contract, dict):
            raise ContractError("DFLight ambient contract is not an object")
        asset_path = asset_directory / str(contract["file"])
        data = asset_path.read_bytes()
        size, checksum = dxbc_identity(data)
        if size != int(contract["size"]) or checksum != str(contract["checksum"]):
            raise ContractError(f"{asset_path.name}: DXBC identity mismatch")
        offsets = gamma_offsets(data)
        if offsets != [int(value) for value in contract["gammaOffsets"]]:
            raise ContractError(f"{asset_path.name}: gamma offsets changed")
        verify_ambient_pow_semantics(
            census.disassemble(fxc, asset_path), asset_path.name
        )
        keys = contract.get("descriptorKeys")
        if not isinstance(keys, list) or not keys:
            raise ContractError(f"{asset_path.name}: descriptor keys are missing")
        for key_text in keys:
            key = int(str(key_text), 16)
            if not key & AMBIENT_DESCRIPTOR_BIT or key & CHARACTER_DESCRIPTOR_BIT:
                raise ContractError(
                    f"{asset_path.name}: invalid ambient descriptor 0x{key:08X}"
                )
            if key in descriptors:
                raise ContractError(
                    f"duplicate ambient descriptor 0x{key:08X}"
                )
            descriptors.add(key)
        maximum_instances = max(maximum_instances, len(keys))
    if len(descriptors) != 78:
        raise ContractError(
            f"expected 78 ambient descriptors, found {len(descriptors)}"
        )
    if maximum_instances > RUNTIME_INSTANCE_CAPACITY:
        raise ContractError(
            "DFLight ambient identity instance capacity is insufficient: "
            f"need {maximum_instances}, have {RUNTIME_INSTANCE_CAPACITY}"
        )
    if manifest.get("maximumInstancesPerIdentity") != maximum_instances:
        raise ContractError(
            "DFLight ambient maximum instance count is stale: expected "
            f"{maximum_instances}"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--extract-from", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    manifest_path = (
        root
        / "package"
        / "Shaders"
        / "Community"
        / "DFLightAmbientContracts.json"
    )
    asset_directory = (
        root
        / "package"
        / "Shaders"
        / "Community"
        / "VerifiedDFLightAmbient"
    )
    fxc = census.find_fxc(None)

    if args.extract_from:
        manifest = build_manifest(
            args.extract_from.resolve(), asset_directory, fxc
        )
        manifest_path.write_text(
            json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
        )
    else:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    validate_manifest(manifest, asset_directory, fxc)
    generated = render_generated(manifest)
    output = args.output.resolve()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != generated:
            raise ContractError(
                f"generated DFLight ambient contracts are stale: {output}"
            )
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(generated, encoding="utf-8")
    print(
        "DFLight ambient contracts verified: 78 descriptors, 39 unique shaders"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ContractError, census.CensusError, OSError, ValueError) as error:
        print(f"DFLight ambient contract generation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
